### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by dhonx** [cweijan/vscode-database-client#10]
- Issue Type: `Performance`
- Extension Name: `vscode-mysql-client`
- Extension Version: `1.7.22`
- OS Version: `Linux x64 5.6.2-050602-generic`
- VSCode version: `1.44.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/don/cweijan.vscode-mysql-client-unresponsive.cpuprofile.txt`
[cweijan.vscode-mysql-client-unresponsive.cpuprofile.txt](https://github.com/cweijan/vscode-mysql/files/4498435/cweijan.vscode-mysql-client-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by cweijan** [comment]
Since 2.1.5, open setting in vscode to enable lazy mode.
```jsonc
{
 // Load database meta info when connected, If your machine's performance is low, turn it off.
  "vscode-mysql.loadMetaOnConnect":false
}
```
