### ISSUE TITLE
[BUG] unexpectedly not seeing all of multiline sql statement when a double dash commented out line is included

### ISSUE THREAD

**Issue by myusrn** [cweijan/vscode-database-client#106]
- OS INFO : windows 10 20H2 (build 19042.746)

A typical practice in mysql workbench, ssms (sql server mgmt studio), and vscode sql extensions is to simply double dash comment out a line in order to test execution of statement with an alternative version of that line.  

I've got an existing case of this where using curernt mysql 3.2.1 extension it isn't seeing that as a comment and allowing me to run that entire sql statement using the clickable "Run SQL" watermark or the f9 / ctrl+enter keyboard shortcut.  

In order to run it i have to select the entire statement first and then use f9 / ctrl+enter keyboard shortcut.

![mysql extension issue](https://user-images.githubusercontent.com/3043446/105666816-f09b2b00-5e8e-11eb-81b1-7feb0f774447.png)
![mysql extension issue 2](https://user-images.githubusercontent.com/3043446/105667123-9b134e00-5e8f-11eb-8f92-4edfdd6e98b3.png)

**Comment by cweijan** [comment]
Fit at version 3.3.0.

**Comment by myusrn** [comment]
yes i can confirm updating to 3.3.0 addresses this issue on my setup, thank you for quick turn around.

![image](https://user-images.githubusercontent.com/3043446/105798950-2b14ce80-5f48-11eb-8c5a-70b0c8720c67.png)
