### ISSUE TITLE
[BUG] Settings to disable Run SQL shortcut

### ISSUE THREAD

**Issue by franklinkf** [cweijan/vscode-database-client#107]
- OS INFO :
After recent update under every line a shortcut to Run SQL appears. This appears in all procedures and functions. How to hide it?

**Comment by franklinkf** [comment]
Forgot to mention. It is a great extension

**Comment by cweijan** [comment]
![image](https://user-images.githubusercontent.com/27798227/106146204-5c440780-61b1-11eb-990c-ccfc9d012d57.png)
Support disable on 3.4.3.

**Comment by franklinkf** [comment]
Thanks
