### ISSUE TITLE
[BUG]添加数据库的时候提示`command 'mysql.connection.add' not found`

### ISSUE THREAD

**Issue by pylist** [cweijan/vscode-database-client#108]
- OS INFO :

**Comment by cweijan** [comment]
你升级vscode版本, 旧版本用不了

**Comment by pylist** [comment]
我重装了最新版的vscode, 还是一样的错误

**Comment by cweijan** [comment]
阿这... 可能是其他扩展和这个扩展的命令冲突了.
你方便的话在vscode内按下ctrl+shift+i, 把控制台的信息截图发给我看看.

**Comment by brianinna** [comment]
> 阿这... 可能是其他扩展和这个扩展的命令冲突了.
> 你方便的话在vscode内按下ctrl+shift+i, 把控制台的信息截图发给我看看.

mac 最新版本vs code 出现同样的问题 刷新啊什么按键也都是not found 你说的这个指令我按了没反应 这个是干嘛的我快捷键不是很熟悉 我 shift command i也没反应

**Comment by cweijan** [comment]
![image](https://user-images.githubusercontent.com/27798227/105956209-68956b00-60b2-11eb-9f02-38d4f408254a.png)
@brianinna

**Comment by brianinna** [comment]
> ![image](https://user-images.githubusercontent.com/27798227/105956209-68956b00-60b2-11eb-9f02-38d4f408254a.png)
> @brianinna

![image](https://user-images.githubusercontent.com/22986729/105956333-9bd7fa00-60b2-11eb-863c-b33e51f5449d.png)

**Comment by brianinna** [comment]
![image](https://user-images.githubusercontent.com/22986729/105956433-c1fd9a00-60b2-11eb-9067-8e3b03535bca.png)

**Comment by cweijan** [comment]
https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-mysql-client2 
@brianinna 老哥安装这个

**Comment by brianinna** [comment]
> https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-mysql-client2
> @brianinna 老哥安装这个

阿巴阿巴阿巴 装都装错了  我是废物

**Comment by siyu7866** [comment]
老哥，我更新您的插件到最新版本后，也遇到了相似的错误，提示“command 'mysql.connection.add' not found”。我恢复到5.4.2版本后可以正常工作了。

**Comment by cweijan** [comment]
@siyu7866 Hi, 我发布了5.4.9解决这个问题了.

**Comment by wangquanqing** [comment]
从8.1.0开始报错command 'mysql.connection.add' not found安装8.0.9就可以
