### ISSUE TITLE
when click connect ,then show the msg "connect success",but connection haven`t saved

### ISSUE THREAD

**Issue by heyiconan** [cweijan/vscode-database-client#109]
- OS Info:Mac
-
<img width="1389" alt="企业微信截图_577c0304-98b6-45b9-8043-d4c16c7e0150" src="https://user-images.githubusercontent.com/6457192/105931028-741e6d00-6085-11eb-9c9a-8540e73c6b6d.png">

**Comment by ttqtuan** [comment]
the same!!

**Comment by cweijan** [comment]
Fix at version 3.3.2 @amournet  @heyiconan

**Comment by collingridge** [comment]
@cweijan I have this problem with version 3.3.2 on Windows 10

**Comment by dake0505** [comment]
@cweijan I have this problem with version 3.3.2 on Windows 10 too.

**Comment by Fiki6640** [comment]
@cweijan I have this problem with version 3.3.5 on Windows 10.

**Comment by ttqtuan** [comment]
@cweijan thank for your support, but i still have this problem on Win10 with version 3.3.5

**Comment by cweijan** [comment]
Fix at version 3.4.1.

**Comment by ttqtuan** [comment]
@cweijan awesome, it's working fine on 3.4.1
