### ISSUE TITLE
[BUG] Only first row values are shown in the table.

### ISSUE THREAD

**Issue by rostislav-palivoda** [cweijan/vscode-database-client#1104]
![2024-04-13_190848](https://github.com/cweijan/vscode-database-client/assets/83497443/5b9b2276-cd59-47d0-95e8-fe2ac832da74)
- Database type and version:
Postgres 15.5

**Comment by cweijan** [comment]
Thanks feedback. The field "children" in the table was incorrectly parsed as child data. I have released version 7.2.3 to fix it, please update the extension!
