### ISSUE TITLE
[BUG]点击链接按钮之后没反应

### ISSUE THREAD

**Issue by brianinna** [cweijan/vscode-database-client#111]
- OS INFO : mac
![image](https://user-images.githubusercontent.com/22986729/105970148-0180b200-60c4-11eb-9249-121abb517ef5.png)

是我哪里操作不对吗

**Comment by brianinna** [comment]
![image](https://user-images.githubusercontent.com/22986729/105970304-2d039c80-60c4-11eb-9207-9cf82cf0e4c6.png)

**Comment by cweijan** [comment]
抱歉, 在3.4.1版本修复了.

**Comment by brianinna** [comment]
可以了
