### ISSUE TITLE
ReadMe 英文版本单词勘误 后续有没有开发数据导入的计划

### ISSUE THREAD

**Issue by brianinna** [cweijan/vscode-database-client#113]
英文单词用错了 提了PR
https://github.com/cweijan/vscode-database-client/pull/112#issue-562386014

后续有没有开发数据导入的计划？[](url)

**Comment by cweijan** [comment]
![image](https://user-images.githubusercontent.com/27798227/105979702-ecf5e700-60ce-11eb-8d28-e3037b334b04.png)
现在支持sql导入.

**Comment by brianinna** [comment]
好吧 My bad. 后续有导入数据的开发计划吗？ xlsx csv之类的

**Comment by cweijan** [comment]
这个有应用场景吗, 我个人没有这个需求, 所以就没做了
