### ISSUE TITLE
How to adjust the timeout for MySQL Connections

### ISSUE THREAD

**Issue by raul-medina-nussbaum** [cweijan/vscode-database-client#114]
- OS Info:
Ubuntu 20.04

My question is quite simple, is there a way to increase the connection timeout for MySQL? I'm on a VPN that is a bit slow so it breaks every now and then. However, using something like MySQL Workbench works fine, it takes more time to connect, but it does (but I don't like it! hahaha) Thanks!

**Comment by cweijan** [comment]
![image](https://user-images.githubusercontent.com/27798227/106237971-eab09b80-623a-11eb-8e8a-7f5b47eebda9.png)
Version 3.4.4 has been support.
