### ISSUE TITLE
[BUG] It does not display the created database.

### ISSUE THREAD

**Issue by Kusigeri** [cweijan/vscode-database-client#116]
- OS INFO : Windows 10 Pro

MySQL is work correctly, but MSSQL and PostgreSQL not refresh db list but it is created.
image
![image](https://user-images.githubusercontent.com/15726805/106640716-aa2c8700-6586-11eb-9bcc-13e072e46bbe.png)

**Comment by cweijan** [comment]
Now only schema is listed, it will display on next version,

**Comment by cweijan** [comment]
Version 3.5.0 has support show database.
