### ISSUE TITLE
[BUG] Run MySQL Query executes entire *.sql file script instead of just line cursor is sitting on

### ISSUE THREAD

**Issue by myusrn** [cweijan/vscode-database-client#119]
- OS INFO : windows 10 20h2 (os build 19042.789) = latest
- VSCODE INFO: 1.53.0 Jan21 = latest
- EXTENSION INFO: 3.5.2 = latest 

When I try and execute a simple line of sql in my sql script using "Run MySQL Query" [ / f9 mysql.runQuery keyboard shortcut ] it tries to run my all statements similar to mysql workbench's "Execute All or Selection" [ / ctrl+shift+enter keyboard shortcut ] command.  

```
select DATE_ADD(curdate(), INTERVAL 14 DAY), DATE_SUB(curdate() , INTERVAL 60 DAY);
select DATE_ADD(utc_date(), INTERVAL 14 DAY), DATE_SUB(utc_date() , INTERVAL 60 DAY);
```

I'm expecting it to run just the current command defined by whatever the cursor is sitting on similar to mysql workbench's "Execute Current Statement" [ / ctrl+enter keyboard shortcut ] command.

If i put those same commands in a simpler shorter sql file the "Run MySQL Query" [ / f9 mysql.runQuery keyboard shortcut ] command produces the expected result and runs just that line that the cursor is currently on.   

See [mysql-extension-issue-repro](https://mysawestus.blob.core.windows.net/public/mysql-extension-issue-repro.sql) download for sql file that repros this unexpected result in the event that you have an interest in determining why.

p.s. would it be a lot of work to enable extension with both f1 / ctrl+shift+p > MySQL: Run MySQL Query [ / mysql.runQuery ] AND MySQL: Run MySQL All or Selection Query [ / mysql.runAllOrSelectionQuery ] command pallet options allowing one to have similar pair of commands as those in the mysql [ / mariadb ] workbench?  I see that currently you've dual purposed mysql.runQuery command to be a run current statement defined by cursor location or run selection if one has selected a chunk of statements so i guess only need for a second command would be to enable them msql.runAll case which i guess can also be accomplished using ctrl+a [ / select all ] keyboard shortcut followed by mysql.runQuery command.

![image](https://user-images.githubusercontent.com/3043446/106976624-94959980-670d-11eb-918a-d9c4cf925a3d.png)

**Comment by cweijan** [comment]
Hi, version 3.9.1 has been able to correctly identify the SQL of each statement, and bind the shortcut as `ctrl+enter`(run current or selected sql) and `ctrl+shift+enter`(run all sql).

**Comment by myusrn** [comment]
Tested and now seeing just those command lines vs running entire script.

Thanks for the updates to include by default bound keyboard shortcuts that align with the mysql workbench experience for folks transitioning to your vscode extension from there.

Was it a deliberate choice to enable `ctrl+enter` shortcut for `or selected sql` processing and not the `ctrl+shift+enter` shortcut which is the shortcut attached to that behavior in mysql workbench?  It does make more logical sense to be attached to `ctrl+enter` shortcut and aligns with that shortcut behavior in things like python and R environments.

**Comment by cweijan** [comment]
The modification to ctrl+enter is not to be compatible with MySQL workbench, but because many software uses ctrl+enter, this shortcut key is obviously more reasonable.
Run current or selected SQL is inspired by SQLyog, and also does not intend to refer to MySQL workbench.

**Comment by myusrn** [comment]
Got it thanks for clarification and additional details.  

Is there a keyboard shortcut or extension UI element in the query pane that will allow one to clear the results view before executing another statement?

**Comment by cweijan** [comment]
Not have, why do you need clear result view?

**Comment by myusrn** [comment]
Sometimes i'll execute a piece of sql [ or entire script ] that produces errors, and i guess its just a housekeeping obsession to want to be able to want to clear the "EXECUTE FAIL:" error text before running again with correction in place in the case the correction still has errors.  

Without that cleared its sometimes hard to tell quickly, unless you trust that you hit ctrl+enter correctly, that you still have problems vs it still displaying previous execution failure text. 

Not a big deal probably just a feature i've seen in other results output pane view experiences where it also isn't critical that a clear before doing next run test be done.
