### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by Weidaicheng** [cweijan/vscode-database-client#12]
Hi,

I got the following error when I tried to connect to localhost mysql:

```
Connection error! ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client.
```

Can you please advise how to solve this? Thanks.

**Comment by cweijan** [comment]
What's your mysql version?

**Comment by Weidaicheng** [comment]
> What's your mysql version?

8.0

You replied so quick🤣

**Comment by cweijan** [comment]
淡定淡定

**Comment by cweijan** [comment]
Since version 1.8.1, I update mysql client lib to newest version , you can retry connect to mysql server.

**Comment by Weidaicheng** [comment]
> Since version 1.8.1, I update mysql client lib to newest version , you can retry connect to mysql server.

Thanks, I'll try again.
I closed this issue because I have changed mysql to 5.6, it worked.

**Comment by Weidaicheng** [comment]
I still got the same issue with 8.0

**Comment by cweijan** [comment]
node/mysql not support 8.0 new auth plugin , you need change to old auth plugin manual.
reference: https://stackoverflow.com/questions/50373427/node-js-cant-authenticate-to-mysql-8-0

**Comment by Weidaicheng** [comment]
> node/mysql not support 8.0 new auth plugin , you need change to old auth plugin manual.
> reference: https://stackoverflow.com/questions/50373427/node-js-cant-authenticate-to-mysql-8-0

Gotche, thank you.
