### ISSUE TITLE
[Question] Is there a way to open/view an existing stored procedure in SqlServer?

### ISSUE THREAD

**Issue by Hephaistos87** [cweijan/vscode-database-client#121]
OS: Mac
VSCode version: 1.53.0
vscode-database-client version: 3.5.2

Hey guys, might be a stupid question but did not really find the answer anywhere: is there a way to open an existing stored procedure in SqlServer and view the creation script there?

**Comment by cweijan** [comment]
- Procedure: Click it.
- View : Right click then `show table source`

**Comment by Hephaistos87** [comment]
Hi @cweijan, many thanks for the swift response. I have tried to do so, but unfortunately here is what I got for "Procedure":

- Left single-click: nothing happened
- Left double-click: nothing happened
- Right click: only two options "Copy name" and "Drop procedure"

For views, I do see the "show table source" option and can also see the creation script of the view.

Any ideas?
