### ISSUE TITLE
Allow database connections to be disabled

### ISSUE THREAD

**Issue by bafonso** [cweijan/vscode-database-client#123]
- OS Info: Linux

I connect remotely to aws and DBs are only accessible if I'm remotely connected to an EC2 and it depends on the aws account (I use several). Right now it seems that it tries to connect all of them but maybe I'm mistaken? It would be nice to select one and press disable if we don't want to even accidentally connect if we press on it.

**Comment by cweijan** [comment]
Right click connection then click `close connection`.
