### ISSUE TITLE
I can not save connection 

### ISSUE THREAD

**Issue by EsmaeelZekaee** [cweijan/vscode-database-client#124]
![image](https://user-images.githubusercontent.com/26879330/108621202-7e464800-7446-11eb-95e0-cec7079a49d5.png)
There is no way to save connection 

VsCode Version 
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:44.518Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.8.0-43-generic snap

**Comment by rendaoer** [comment]
this nosql , check out the database

**Comment by cweijan** [comment]
![image](https://user-images.githubusercontent.com/27798227/108651397-a2646080-74fc-11eb-9f97-1f5d64b7112d.png)
Yes, this plugin create two panel, database and nosql, you need chose database panel.
