### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xiying** [cweijan/vscode-database-client#128]
OS INFO : windows 10 20h2 (os build 19042.804) / Windows_NT x64 10.0.19042 = latest
VSCODE INFO: 1.53.2 = latest
EXTENSION INFO: 3.5.3 = latest

### BUG反馈一：查询显示错误
**详细描述**
数据为：
![image](https://user-images.githubusercontent.com/17631196/109133140-a360f080-778f-11eb-8c65-1773fe765189.png)

代码为：
```sql
SELECT scA.*, scB.*, scA.Cid, scB.Cid
FROM ( SELECT SId, CId, score FROM sc1 WHERE CId = 01 ) AS scA
INNER JOIN ( SELECT SId, CId, score FROM sc1 WHERE CId = 02 ) AS scB
ON scA.SId = scB.SId
```

此插件运行结果为：
![image](https://user-images.githubusercontent.com/17631196/109237772-32601e00-780d-11eb-9552-34cffd6cbcb6.png)

Navicat运行结果为：
![image](https://user-images.githubusercontent.com/17631196/109133809-56314e80-7790-11eb-8c36-5e815277b2cb.png)

**补充**
```sql
# 上述代码第一行修改为此，第二个错误的方框会正确显示为 01
SELECT scA.*, scB.*, scA.Cid AS c1, scB.Cid
```

### BUG反馈二：导出数据不全
上面的例子，输出结果用插件导出，excel文件中为：
![image](https://user-images.githubusercontent.com/17631196/109237812-502d8300-780d-11eb-98f2-d5efbf21e2f1.png)

![image](https://user-images.githubusercontent.com/17631196/109237417-7141a400-780c-11eb-8232-da4b575d385e.png)

以上是一些发现，请修复，谢谢！

**Comment by cweijan** [comment]
目前的JS库都是无法处理重名列的, 你只能通过对列名设置别名来解决.
