### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by HacoK** [cweijan/vscode-database-client#129]
- VS Code INFO : 
Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
- Problem:
The extension can't open connections with version 3.5.3...
It's just waiting for loading for a long time without any connection shown...
And when I rollback to version 3.5.2, the mysql connection turned out as soon as I opened the view page...

**Comment by webdeveloper001** [comment]
Same for me. 
it keeps loading on the explorer panel. 

though when I create a new connection and click connect button the success message displays.

**Comment by cweijan** [comment]
Hey, try version 3.5.4.

**Comment by HacoK** [comment]
> Hey, try version 3.5.4.

Now it works :D
