### ISSUE TITLE
使用SQL Server导出数据和表结构后int型数据多出三个单引号

### ISSUE THREAD

**Issue by disvegetable** [cweijan/vscode-database-client#1295]
你好，我使用SQL Server时导出数据和表结构后，在sql文件发现在insert语句中，整型数据多出三个单引号，导致无法将该sql文件导入到其他数据库中，请问如何解决？谢谢
![swappy-20241009-222710](https://github.com/user-attachments/assets/27f2c745-b299-4210-951f-379e28569f06)

**Comment by cweijan** [comment]
谢谢反馈, 已在版本7.6.5修复.
