### ISSUE TITLE
[Bug] redis connection not save "Connection Name"

### ISSUE THREAD

**Issue by YannLex** [cweijan/vscode-database-client#130]
- OS INFO :
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:45:54.515Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

I filled "Connection Name", but not saved, and NOSQL EXPLORER not display it.

![image](https://user-images.githubusercontent.com/3049310/109629381-b7856300-7b7e-11eb-8292-98efbaf4a7b1.png)

**Comment by cweijan** [comment]
Fix at version 3.5.5.
