### ISSUE TITLE
set default database

### ISSUE THREAD

**Issue by wrishel** [cweijan/vscode-database-client#1327]
When I reopen vscode the default database for SQL statements seems to be the first one listed under the connection. When there are several variants of the same database this can lead to errors. MySQL workbench has a feature where it is possible to right click on a database and select default that designation persists across sessions.

Would it be possible to make the right-click->active function persist or else to add right-click->default to the accelerator menu when clicking in a database?

Thank you!

**Comment by cweijan** [comment]
The recovered database is the last active database, not the first database, and I don't plan to modify it. If the SQL file has an active mark, then the mark-bound database will be set to active.

<img width="622" alt="image" src="https://github.com/user-attachments/assets/a6cc28cf-dc66-4452-b01d-e956eda3797b">
