### ISSUE TITLE
[BUG]mysql不显示表

### ISSUE THREAD

**Issue by jiangwu10057** [cweijan/vscode-database-client#133]
- OS INFO :
自3.5.0版本起，mysql视图就不显示数据库和表；之前的版本显示正常
![image](https://user-images.githubusercontent.com/6183367/110039639-807ca080-7d7c-11eb-81bb-db038e064d2f.png)
<img width="385" alt="QQ20210305-062955@2x" src="https://user-images.githubusercontent.com/6183367/110039597-6e9afd80-7d7c-11eb-9969-bf46b728f928.png">

正常版本
![image](https://user-images.githubusercontent.com/6183367/110039779-b588f300-7d7c-11eb-88d6-df9ea437cc1c.png)
![image](https://user-images.githubusercontent.com/6183367/110039745-ac982180-7d7c-11eb-9320-d1306caa739e.png)

**Comment by cweijan** [comment]
你的mysql版本多少, 同时按下ctrl+shift+i把控制台的信息截图看下.

**Comment by jiangwu10057** [comment]
mysql版本是8.0.20
![image](https://user-images.githubusercontent.com/6183367/110089257-d713ca00-7dd0-11eb-8504-82b2bb8a212f.png)

**Comment by jiangwu10057** [comment]
找到问题了，前后版本数据不兼容。
查配置路径
mac系统：/Users/miluyu/Library/Application Support/Code/User/globalStorage

3.5.0开始的数据结构是
```json
{
    "host":"127.0.0.1",
    "port":"3306",
    "user":"username",
    "password":"pwd",
    "database":null,
    "usingSSH":false,
    "includeDatabases":null,
    "dbType":"MySQL",
    "encrypt":true,
    "global":true,
    "scheme":"http",
    "timezone":"+00:00",
    "ssh":{
        "host":"",
        "port":22,
        "username":"root",
        "algorithms":{
            "cipher":[

            ]
        }
    },
    "name":"本地",
    "context":null,
    "parent":null,
    "provider":null,
    "command":null
}
```
之前的版本
```json
{
    "host":"127.0.0.1",
    "port":"3306",
    "user":"username",
    "password":"pwd",
    "database":null,
    "usingSSH":false,
    "global":true,
    "excludeDatabases":"mysql,performance_schema,information_schema,sys",
    "timezone":"+00:00",
    "ssh":{
        "host":"",
        "port":22,
        "username":"root"
    },
    "name":"本地",
    "parent":null
}
```
缺少dbType属性，导致无法connectionNode.ts文件getChildren函数hasCatalog变量取值错误！

**Comment by cweijan** [comment]
那你删除连接后重新连接

**Comment by jiangwu10057** [comment]
> 那你删除连接后重新连接

已删除重联， 正常了
