### ISSUE TITLE
Access to connection's settings

### ISSUE THREAD

**Issue by demmonico** [cweijan/vscode-database-client#134]
Hey there!
Thanks for really useful extension!

I tried to find out the way to access/manage data of DB connections. Is there any chance to do it?

For example in `sqltools` extension there is ability to have them in `/Users/username/Library/Application Support/Code/User/settings.json` file (I'm using Mac).
It looks like:
```
"sqltools.connections": [
        {
            "mysqlOptions": {
                "authProtocol": "default"
            },
            "previewLimit": 50,
            "server": "asd",
            "port": 123,
            "driver": "MySQL",
            "name": "release",
            "group": "pp",
            "database": "pp",
            "username": "qa_pp",
            "password": ""
        }
    ],
```

It's very useful in terms of backing up or sharing connections etc...

**Comment by cweijan** [comment]
Sorry, for security reasons, the configuration is stored inside vscode and you cannot view it.

**Comment by cweijan** [comment]
I will add backup of config in feature.

**Comment by iongion** [comment]
What is the security issue, users adding this configuration to git and hardcoding passwords/keys ?

Can't they do the same with `.env` files ? But with good practices, they can know storing secrets in SCM is bad!

Can't we better inform them of good practices instead of blocking the ability to share settings across teams ?

If the extension would support sourcing `.env` (scm) and `.env.local`(scm ignore) - just like VSCode does in many extensions, then what @demmonico proposes above could become:

```"sqltools.connections": [
        {
            "mysqlOptions": {
                "authProtocol": "default"
            },
            "previewLimit": 50,
            "server": "asd",
            "port": 123,
            "driver": "MySQL",
            "name": "release",
            "group": "pp",
            "database": "pp",
            "username": "qa_pp",
            "password": "$ASD_PASSWORD"
        }
    ]
```

where `.env` file could contain
```
ASD_PASSWORD=
```
and `.env.local` file contains
```
ASD_PASSWORD=********
```

* `.env` files are to be loaded if found
* `.env.local` files are to be loaded if found
* The `.env.local` override file name could be configurable
* Env format could be `key = val` lines, could be `.ini`, `.json` or `.yml`

**Comment by cweijan** [comment]
Since version 3.9.0 has support edit config, I think putting the configuration file in the project directory will cause security problems, So there is no plan to support @iongion .
![image](https://user-images.githubusercontent.com/27798227/132534559-662f269e-9cfc-4fc9-a879-9e21a84a075f.png)

**Comment by cweijan** [comment]
Since version 3.9.0 has support edit config, I think putting the configuration file in the project directory will cause security problems, So there is no plan to support @iongion .
![image](https://user-images.githubusercontent.com/27798227/132534559-662f269e-9cfc-4fc9-a879-9e21a84a075f.png)

**Comment by iongion** [comment]
Don't t agree with this security issue, but wholeheartedly understand your design and drive and obide to it, your project is awesomene and we can find other ways to share settings across develeopers. Even if they are more tedious that just being present somewhere in the workspace settings. Thanks for all your dedication and effort that we all benefit for free!

**Comment by demmonico** [comment]
Basically there are 2 things to respond from my side:
- taking care about security is great, but you (plugin I mean) always can store passwords separately (as you're doing now internally) and/or ignore passwords field on import settings. Thus all other boring settings will be shareable except secrets.
- issue is not only related to sharing itself. Just imaging that you have 10+ DBses and you just ... change your laptop. I guess you'll have nice evening restoring all accesses. And even better if you'll lost your laptop...

**Comment by iongion** [comment]
@demmonico You are so right, this is another one - but @cweijan ' s stance is also to be taken, in his way, if you have no way to store, you also have no security risk :) - quite radical in my opinion, but true nevertheless.

Is not like you can control whatever developers put in their git repos, but at least you know is not coming from your side.

**Comment by demmonico** [comment]
(c) It's not on our side, it's yours! :)

**Comment by cweijan** [comment]
Version 3.5.2 has support for storing configuration to workspace
![image](https://user-images.githubusercontent.com/27798227/150482505-7954b800-760c-4386-baff-a7246412e179.png)

**Comment by cweijan** [comment]
A security risk means that there will be users who upload configuration files to the git repository.
I didn't encrypt the password, and it doesn't make sense for open source projects to encrypt.

**Comment by bilogic** [comment]
> Sorry, for security reasons, the configuration is stored inside vscode and you cannot view it.

Hi, can confirm that connection settings are stored locally and not sent to cloud?

**Comment by bilogic** [comment]
> Sorry, for security reasons, the configuration is stored inside vscode and you cannot view it.

@cweijan can confirm that connection settings are stored locally and not sent to cloud? Thank you.
