### ISSUE TITLE
希望合并侧边栏的Database Explorer和NoSQL Explorer按钮

### ISSUE THREAD

**Issue by Faputa** [cweijan/vscode-database-client#135]
- OS Info: Windows 10 x64 20H2

如题，vscode的侧边栏对于安装了许多插件的人来说是一项很紧张的资源，一个插件占用两个按钮的位置没有必要且浪费

**Comment by cweijan** [comment]
不需要的话在侧边栏右键隐藏, 大部分情况下nosql和数据库需要同时查看数据, 合在一起后查看是不方便的.
![image](https://user-images.githubusercontent.com/27798227/110196293-8ce92200-7e7e-11eb-812a-058e5a4c597c.png)

**Comment by Faputa** [comment]
> 不需要的话在侧边栏右键隐藏, 大部分情况下nosql和数据库需要同时查看数据, 合在一起后查看是不方便的.
> ![image](https://user-images.githubusercontent.com/27798227/110196293-8ce92200-7e7e-11eb-812a-058e5a4c597c.png)

因为我确实是需要同时连接数据库和redis，所以不能隐藏其中任一按钮。至于合并之后查看是否会不方便，我认为因为有图标作为区分所以不会存在这种问题；或者可以参考资源管理器，在一个Explorer视图内创建两个子菜单，分别为Database和NoSQL，并放置对应的按钮在菜单上。

**Comment by cweijan** [comment]
这确实是个好主意, 我以后试试.

**Comment by cweijan** [comment]
我想错了, 之前就是弄了个分组, 但在数据库表多的时候, 查看Redis要不停的拖动, 所以才拆开了, 不打算再合并了.
