### ISSUE TITLE
Extension issue :Not able to Load database and able

### ISSUE THREAD

**Issue by AnilUchadiya** [cweijan/vscode-database-client#136]
- Issue Type: `Bug`
- Extension Name: `vscode-postgresql-client2`
- Extension Version: `3.5.4`
- OS Version: `Linux x64 5.8.0-44-generic`
- VSCode version: `1.54.1`
- Extension issue :Not able to Load database and table  ```json  { 	"messages": [], 	"activationTimes": { 		"codeLoadingTime": 117, 		"activateCallTime": 9, 		"activateResolvedTime": 0, 		"activationReason": { 			"startup": true, 			"extensionId": { 				"value": "cweijan.vscode-postgresql-client2", 				"_lower": "cweijan.vscode-postgresql-client2" 			}, 			"activationEvent": "*" 		} 	}, 	"runtimeErrors": [] } ```

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by cweijan** [comment]
I need to know how this is caused.

**Comment by AnilUchadiya** [comment]
I was working on my course assignment which required making a Database and querying it so first when I  installed it, it was working fine and then for the next assignment  I hade to make another database for so it worked for the first time than after it now always shows loading, I am attaching a screenshot which may help, feel free to  ask any extra information, the loading in left extension is still on for 1 hours
![Screenshot from 2021-03-06 12-38-04](https://user-images.githubusercontent.com/32511023/110198481-cfa7fb80-7e78-11eb-9532-3eeb3d4c757c.png)



Thank you.

**Comment by cweijan** [comment]
Is it normal now? I have tried many times, but none of your situation has appeared.

**Comment by AnilUchadiya** [comment]
Yeah now it's working fine, I don't know what was the problem, maybe I did a recursion on a 1.5Million rows table and the results was >10GB  or I used up all cache memory of my database so it stopped loading the view. BTW Thank you for your concerns

**Comment by cweijan** [comment]
Yes, your guess is correct, query and tree view using same connection.
