### ISSUE TITLE
[BUG] Redis SETBIT response with incorrect encoding

### ISSUE THREAD

**Issue by YannLex** [cweijan/vscode-database-client#137]
- OS INFO :
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:45:54.515Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

![image](https://user-images.githubusercontent.com/3049310/110225697-ed319f80-7f22-11eb-9153-ed398200e711.png)

**Comment by cweijan** [comment]
It always get key value as utf8 encoding, not support hex.
