### ISSUE TITLE
[BUG]  Using SSH 这个功能不能使用

### ISSUE THREAD

**Issue by jfinal** [cweijan/vscode-database-client#138]
- OS INFO :
正在使用 vscode-database-client ，发现 Using SSH 这个功能不能使用

**Comment by cweijan** [comment]
不能使用什么意思, 连接ssh失败了吗

**Comment by cweijan** [comment]
你尝试修改一下cipher以及确认Host没有填错, 你显示超时的话我认为你host写错的可能性比较大.
![image](https://user-images.githubusercontent.com/27798227/110441728-10ac4400-80f5-11eb-92f4-a846ed07fbb7.png)

**Comment by cweijan** [comment]
那尴尬了, 这问题比较难定位,  ssh出错的原因有很多可能性😂.

**Comment by jfinal** [comment]
> 那尴尬了, 这问题比较难定位, ssh出错的原因有很多可能性😂.

关键是目前没有输出更详尽的错误信息，超时也可以输出原因，例如是不是因为 host 错误产生的超时之类

我还是很希望能用上你的作品的，可惜 SSH 不行

一直用的  Sequel Pro 这个 mysql 客户端的 SSH 通道登录的远程 mysql，所以本地系统环境上是没问题的

希望你们能改进改进 👍👍👍

**Comment by cweijan** [comment]
你方便的话加下我qq 1443931123.

**Comment by jfinal** [comment]
问题已确认，vscode-database-client 的 SSH 链接要求 rsa 密钥必须通过 -m PEM  参数来生成，例如：
ssh-keygen -m PEM  -t rsa -C "test"

建议改进这里

**Comment by cweijan** [comment]
感谢反馈, 由于使用第三方库, 仅能支持PEM格式, 将在新版本增加说明.

**Comment by jfinal** [comment]
> 感谢反馈, 由于使用第三方库, 仅能支持PEM格式, 将在新版本增加说明.

为啥不换个第三方库，功能不能受限于第三方

**Comment by stjava** [comment]
Error: Cannot parse privateKey: Unsupported key format 估计是同一个问题。

**Comment by cweijan** [comment]
@stjava 需要修改密钥格式, 将openssh改为rsa.

**Comment by jfinal** [comment]
> @stjava 需要修改密钥格式, 将openssh改为rsa.

ssh-keygen 生成密钥的时候，默认就是 rsa ，可选项有：rsa rsa1 dsa，不存在 openssh 这一说

我提的这个 issue 后来解决没有？

**Comment by cweijan** [comment]
发issue的老哥换了密钥格式就可以连接了
















At 2021-04-13 22:46:42, "James Zhan" ***@***.***> wrote:

@stjava 需要修改密钥格式, 将openssh改为rsa.

ssh-keygen 生成密钥的时候，默认就是 rsa ，可选项有：rsa rsa1 dsa，不存在 openssh 这一说

我提的这个 issue 后来解决没有？
