### ISSUE TITLE
[BUG] Issue connectiong on same DB server with different users

### ISSUE THREAD

**Issue by m0t1x** [cweijan/vscode-database-client#139]
- `Issue Type:` Bug
- `Extension Name:` vscode-postgresql-client2
- `Extension Version:` 3.5.6
- `OS Version:` Linux (5.10.18-200.fc33.x86_64)
- `VSCode version:` 1.54.1
- `Extension issue:`  Error is observed with 2 connection (conn1, conn2) on the same database server and with 2 different users (user1, user2) and 2 different databases (db1, db2), but probably the same issue will appear with more connections on the same database server. Each user can access only it's own database (user1 -> db1, user2 -> db2 ).  When, for example,conn1 is refreshed, conn2 tries to connect to db1 instead of db2, and vice versa. After first refresh, the other connection database is shadowed with the selected one. The only possibility to switch between connections is to restart VSCode and than select different connection first.

See picture - `notary-signer` connection  should have access to `notarysigner` database, but instead `notaryserver` popups.

![vscode_client_error](https://user-images.githubusercontent.com/80338020/110490849-fd977500-80f0-11eb-9bc7-fe004db3da74.png)

**Comment by cweijan** [comment]
Fix at version 3.6.0.

**Comment by m0t1x** [comment]
Version 3.6.0 has fixed the issue.
Thank You :-)
