### ISSUE TITLE
`UNSIGEND` keyword support

### ISSUE THREAD

**Issue by Bit0r** [cweijan/vscode-database-client#14]
Can you add support for the `UNSIGNED` keyword? This keyword is very commonly used

**Comment by Bit0r** [comment]
If possible, you can additionally add `FOREIGN`,` REFERENCES`, `CASCADE`,` RESTRICT` and `CHECK` keywords

**Comment by Bit0r** [comment]
for instance:
```mysql
  orderid int UNSIGNED NOT NULL
  REFERENCES orders(orderid)
  ON UPDATE CASCADE
  ON DELETE CASCADE
```

**Comment by cweijan** [comment]
OK, new version will released on 4.28.

**Comment by Bit0r** [comment]
There are also `CALL` keywords for stored procedures.
This plugin is great, is the best mysql plugin on vscode

**Comment by cweijan** [comment]
new version 1.9.0 is added.
