### ISSUE TITLE
[BUG] mysql和redis添加新连接失败

### ISSUE THREAD

**Issue by devguo** [cweijan/vscode-database-client#141]
连接mysql如果使用同一个ssh host，也会导致新加的连接覆盖掉老的。
版本： v3.5.6
复现步骤：
1. 添加一个连接A，使用的ssh host为 192.168.2.33, 添加成功的话，左侧面板会显示192.168.2.33@22 A;
2. 添加一个连接B， 使用的ssh host为 192.168.2.33, 添加成功的话，左侧面板会显示192.168.2.33@22 B;
 这个时候B把A覆盖了，实际上应该分别是两个连接；
 补充说明（不太清楚Using SSH旁边的 Global的作用，不管打开或者关闭，都是新连接覆盖老连接）
redis也同样存在这个问题， 看了下代码，估计其他类型的连接也存在这个问题。 
建议：
用自定义的连接名称作为key，这样即使同一个数据库地址，使用不同的用户名也不会出现问题。

**Comment by cweijan** [comment]
下版本会区分不同用户.

**Comment by devguo** [comment]
感谢写出这么好用的插件。
区分不同用户的话，我觉得还是没有从根源解决问题。就拿通过ssh这个场景来说，通过ssh tunnel可以连接到两套不同环境，如果两套环境用户名一样，还是会存在添加失败的问题。如果能用Connection Name来区分不同连接，对用户会更友好一些。:)

**Comment by cweijan** [comment]
版本3.6.0修复了.
