### ISSUE TITLE
Rename extension name MySQL to Database Client?

### ISSUE THREAD

**Issue by MurzNN** [cweijan/vscode-database-client#144]
At now extension in VS Code lists represented with "MySQL" name, that's very confusing, because it have support for many other database types. 

Maybe rename the `displayName` to "Database Client" or even something like "Multi-database client"?

Also will be good to add other database names to "description" text in `package.json`, and maybe more detailed description of advantages.

**Comment by emil14** [comment]
Why was it closed?

I wasn't using this extension because of its name for years!

**Comment by cweijan** [comment]
This extension was re-released under the name Database Client, but it didn't get very high installs.
https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-database-client2

**Comment by emil14** [comment]
@cweijan Maybe you should mark "MySQL" as deprecated and add link to "Database Client" to readme and to extension's description. And add some note to "Database Client" - tell that this is ex "MySQL" extension. This could bring more users and more commits to the repo
