### ISSUE TITLE
大数据量，大字段的表格滚动的时候非常的卡顿。

### ISSUE THREAD

**Issue by joyous-coder** [cweijan/vscode-database-client#145]
- OS INFO : win10 64bit

**Comment by cweijan** [comment]
优化过几次, 现在的速度已经是最快了.

**Comment by cweijan** [comment]
减少分页数量或者升级你的机器.

**Comment by joyous-coder** [comment]
问题是cpu和内存的使用率都不高啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chen ***@***.***&gt;; 
发送时间: 2021年3月17日(星期三) 下午2:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cweijan/vscode-database-client] 大数据量，大字段的表格滚动的时候非常的卡顿。 (#145)





 
减少分页数量或者升级你的机器.
 
&mdash;

**Comment by joyous-coder** [comment]
@cweijan  我又试着用鼠标进行了滚动，发现很流畅。之前一直用触摸板滚动的，用触摸板滚动的时候就很卡。两个在操作系统上滚动的逻辑不一样么？？

**Comment by joyous-coder** [comment]
@cweijan   可能是vscode的问题？？ https://github.com/microsoft/vscode/issues/53199#event-1706959672

**Comment by cweijan** [comment]
试试开启vscode的平滑滚动, 在vscode配置文件中加入以下内容.
```json
"editor.smoothScrolling": true,
"workbench.list.smoothScrolling": true,
```
