### ISSUE TITLE
How to Create/Run query on selected table

### ISSUE THREAD

**Issue by PaulDokken** [cweijan/vscode-database-client#146]
How can I run a query that I can immediately edit that uses the current table I have selected.

**Comment by cweijan** [comment]
I don’t understand what you mean, if it means editing, press ctrl+s after editing the result page to save .

**Comment by PaulDokken** [comment]
<img width="733" alt="Screen Shot 2021-03-24 at 8 12 48 AM" src="https://user-images.githubusercontent.com/75853422/112310437-f89efd80-8c7a-11eb-9501-136265224023.png">
The documentation shows clicking on an icon to open a query.  I do not seem to have that icon.

**Comment by PaulDokken** [comment]
I didn't mean to close the issue

**Comment by cweijan** [comment]
Query button show on database node.
![image](https://user-images.githubusercontent.com/27798227/112315575-3a648e00-8ce5-11eb-88a0-e1188045db29.png)

**Comment by cweijan** [comment]
You need scroll up to database node.

**Comment by PaulDokken** [comment]
That answers my question.  Thanks for the great tool!
