### ISSUE TITLE
[BUG]删除特定无效连接始终报`connnet EHOSTUNREACH ip:port`,编辑也只生成新连接

### ISSUE THREAD

**Issue by sth4me** [cweijan/vscode-database-client#147]
- OS INFO :
UOS 1031 professional

删除某个无效的连接，会尝试连接，报`connnet EHOSTUNREACH ip:port`，但其他比如我本地特意停止服务的数据库删除并没有该错误。如果只是特例，需要找到一个可以彻底删除该无效连接的方案，因为即使是在该无效连接进行编辑，结果也只是生成新的连接。

**Comment by cweijan** [comment]
这个连接是多久前添加的, 有可能是在旧版本加的, 新版本不太兼容了.

**Comment by cweijan** [comment]
插件的新版本不会造成该错误, 考虑下更新版本.
