### ISSUE TITLE
Bug report "EXECUTE FAIL: Message :   ER_EMPTY_QUERY: Query was empty"

### ISSUE THREAD

**Issue by 2664139264** [cweijan/vscode-database-client#15]
I do like this plug-in with its beautiful visual interface but there's a frustrating bug when I run queries, the Query board always shows me "EXECUTE FAIL:
Message :
  ER_EMPTY_QUERY: Query was empty"

although my query is not empty at all.
I hope this bug be repaired soon.
Thanks for your effort.

**Comment by cweijan** [comment]
version 1.9.0 is fixed this bug.
