### ISSUE TITLE
[BUG] menu items are doubled

### ISSUE THREAD

**Issue by palansher** [cweijan/vscode-database-client#151]
- OS INFO :
Windows 10 x64

VS Cover ver - latest.

Hello ! The menu items are always doubles. Pls look at screenshot.

![image](https://user-images.githubusercontent.com/24850253/112689277-1e025600-8e8b-11eb-832c-6e776ca8f2ae.png)

**Comment by cweijan** [comment]
I think you install double extension, uninstall one.

**Comment by alex2022cci** [comment]
> 

For example, if you (or me ) install the extension ' SQLTools' https://vscode-sqltools.mteixeira.dev/en/home + the extension 'MySQLDatabase' https://database-client.com/#/ in the same VS Code environment you get everything doubled.  
![VSCode Database plugin](https://github.com/cweijan/vscode-database-client/assets/113517120/1026d1db-ec09-4e3d-b44f-581e35088f21)

Thanks for the answer.

**Comment by cweijan** [comment]
Please check the extensions you have installed. I believe you have installed multiple extensions that I have published and found duplicate ones to uninstall




--
发自我的网易邮箱手机智能版



在 2023-05-13 19:32:08，Alex2022CCI ***@***.***> 写道：


For example, if you (or me ) install the extension ' SQLTools' https://vscode-sqltools.mteixeira.dev/en/home + the extension 'MySQLDatabase' https://database-client.com/#/ in the same VS Code environment you get everything doubled.


Thanks for the answer.
