### ISSUE TITLE
[BUG] sometimes a table rows is not shown  by double click

### ISSUE THREAD

**Issue by palansher** [cweijan/vscode-database-client#152]
- OS INFO :

Windows 10 x64

Infinity hourglass is shown when I open a table the first time after VS Code started..  No errors are shown.
How to fix that: switch to another table and then open the first table. After that, I can see the table's rows.
When: always.

![image](https://user-images.githubusercontent.com/24850253/112689070-d2e84300-8e8a-11eb-877a-87778f1f5bcd.png)

**Comment by cweijan** [comment]
Install this https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-mysql-client2 and uninstall other.

**Comment by palansher** [comment]
Thank you so much @cweijan !

1) 
Do all your VS Code Database extensions (that support MySQL/MariaDB) have equal functionality and new feature implementations for MySQL/MariaDB?
I mean "MySQL" and "Database Client". 
Or some extensions are more obsolete than others? Are they equally preferable for  MySQL/MariaDB?

2) Do you plan the SQLLite support in the future?

**Comment by palansher** [comment]
Thank you so much @cweijan !

1)
Do all your VS Code Database extensions (that support MySQL/MariaDB) have equal functionality and new feature implementations for MySQL/MariaDB?
I mean "MySQL" and "Database Client".
Or some extensions are more obsolete than others? Are they equally preferable for MySQL/MariaDB?
Would you please clarify it more certainly?

2)
Do you plan the SQLLite support in the future?

**Comment by palansher** [comment]
> Install this https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-mysql-client2 and uninstall other.

I did that and have the same issue: the first click on any table results in an infinity hourglass.
No other DB extensions are installed.

I connected to the remote MariaDB server thru ssh.

PS: Not a big issue but annoying.

**Comment by palansher** [comment]
If you need I can demonstrate it in a video.

**Comment by cweijan** [comment]
You need uninstall and restart vscode.
