### ISSUE TITLE
[BUG] table rows count in explorer is not updated

### ISSUE THREAD

**Issue by palansher** [cweijan/vscode-database-client#153]
- OS INFO : Windows 10 x64

The remote server (ssh Remote): Ubuntu 18.04

Hello!

After the table truncates and refresh, the table rows count still shows the previous value.

![image](https://user-images.githubusercontent.com/24850253/112706963-d8f51880-8eb8-11eb-9feb-5043096da69d.png)

**Comment by cweijan** [comment]
You need refresh database node, table node refresh is reload column.

**Comment by palansher** [comment]
Thank you, it works, but not easy to guess.
