### ISSUE TITLE
[BUG] Cannot drop table from explorer

### ISSUE THREAD

**Issue by palansher** [cweijan/vscode-database-client#154]
- OS INFO : Windows 10 x64

ssh remote: Ubuntu 18.04

SQL Server version: 10.4.13-MariaDB-1:10.4.13+maria~bionic-log mariadb.org binary distribution

```
CREATE TABLE `bkphoto_auto` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `driver_id` int(11) NOT NULL,
  `autopark` text DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8
```

![image](https://user-images.githubusercontent.com/24850253/112707125-eb238680-8eb9-11eb-9a58-237a91d9a92c.png)

![image](https://user-images.githubusercontent.com/24850253/112707116-dcd56a80-8eb9-11eb-9673-35b3c4ba4fc9.png)

![image](https://user-images.githubusercontent.com/24850253/112707132-fa0a3900-8eb9-11eb-8d31-b3de9704500b.png)

![image](https://user-images.githubusercontent.com/24850253/112707281-443fea00-8ebb-11eb-9fe9-56c1360025b9.png)

**Comment by cweijan** [comment]
Fix at version 3.6.1.
