### ISSUE TITLE
[BUG] Postgres connection don't use SSL by default

### ISSUE THREAD

**Issue by jekuno** [cweijan/vscode-database-client#155]
Trying to connect to a Heroku database fails with `Connection error! ... SSL off`

Heroku enforces the use of SSL (see https://devcenter.heroku.com/articles/heroku-postgresql#heroku-postgres-ssl) for security reasons. However I don't see any option to activate SSL in the database connection settings.

IMO it would be good if vscode-database-client would default to using SSL connections.

**Comment by cweijan** [comment]
Do you use SSL certificate to connect?

**Comment by jekuno** [comment]
No. No tunnel, no SSL certificate.

The Heroku docs say
> Most clients will connect over SSL by default, but on occasion it is necessary to set the `sslmode=require` parameter on a Postgres connection. Please add this parameter in code rather than editing the config var directly.

**Comment by cweijan** [comment]
I added enable ssl option to postgresql on version [3.6.7](https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-database-client2), but I don't know if it works.

**Comment by abrahammurciano** [comment]
I tried with v3.6.4, and after getting this issue I found this. I updated to 3.6.7 and now it says "Connection error! self signed certificate"
![image](https://user-images.githubusercontent.com/25041135/114318711-f829b200-9b16-11eb-873d-03e7b2d72929.png)

**Comment by cweijan** [comment]
This mean ssl must using ssl certificate.
















At 2021-04-12 03:41:44, "Abraham Murciano" ***@***.***> wrote:

I tried with v3.6.4, and after getting this issue I found this. I updated to 3.6.7 and now it says "Connection error! self signed certificate"

**Comment by abrahammurciano** [comment]
> This mean ssl must using ssl certificate.

So is there anything I can do to connect?

**Comment by jekuno** [comment]
I tested with v3.6.7
When I disable the Encrypt switch, I get the following error:
`Connection error! no pg_hba.conf entry for host "xxx.xx.xxx.xx", user "yyy", database "zzz", SSL off`

When I enable the Encrypt switch, I get the following error:
`Connection error! self signed certificate`

In my case enabling the switch is the first right step to do, as I connect to Heroku where SSL connections are enforced by default. The connection still fails because it checks against the list of supplied CAs when connecting without success.

To resolve this, best would be to add a further toggle "Verify Certificate" to the addon (which gets visible when the Encrypt switch is active and is disabled by default). Activating this "Verify Certificate" toggle, internally sets the `rejectUnauthorized` option to false in your connection string:

```js
const config = {
  connectionString: process.env.DATABASE_URL,
  ssl: {
    rejectUnauthorized: false
  }
}
const client = new Client(config);
```

@cweijan As soon as you have done this, connecting to those databases, should work for your addon.

BTW I would recommend to rename the "Encrypt" switch to "SSL" and have it active by default. And IMO you can also remove the hint "If connect DatabaseServer fail, try change this option." from the toggle as there are many reasons why a connection can fail.

**Comment by vixson** [comment]
@jekuno This right here...
Please what are the steps for resolving
**Connection error! no pg_hba.conf entry for host "xxx.xx.xxx.xx", user "yyy", database "zzz", SSL off**

The solution you gave was not clear enough. Thanks

> I tested with v3.6.7 When I disable the Encrypt switch, I get the following error: `Connection error! no pg_hba.conf entry for host "xxx.xx.xxx.xx", user "yyy", database "zzz", SSL off`
> 
> When I enable the Encrypt switch, I get the following error: `Connection error! self signed certificate`
> 
> In my case enabling the switch is the first right step to do, as I connect to Heroku where SSL connections are enforced by default. The connection still fails because it checks against the list of supplied CAs when connecting without success.
> 
> To resolve this, best would be to add a further toggle "Verify Certificate" to the addon (which gets visible when the Encrypt switch is active and is disabled by default). Activating this "Verify Certificate" toggle, internally sets the `rejectUnauthorized` option to false in your connection string:
> 
> ```js
> const config = {
>   connectionString: process.env.DATABASE_URL,
>   ssl: {
>     rejectUnauthorized: false
>   }
> }
> const client = new Client(config);
> ```
> 
> @cweijan As soon as you have done this, connecting to those databases, should work for your addon.
> 
> BTW I would recommend to rename the "Encrypt" switch to "SSL" and have it active by default. And IMO you can also remove the hint "If connect DatabaseServer fail, try change this option." from the toggle as there are many reasons why a connection can fail.
