### ISSUE TITLE
feature request for elasticsearch

### ISSUE THREAD

**Issue by ttbadr** [cweijan/vscode-database-client#156]
1. It would be better to add an option like `ignore SSL error` when creating an es connection to support self-signed certification.
2. My ES server behind a proxy, the URL like this `http://es.com:8080/esnodes/`. For now, the plugin just provides host and port two parameters to connect es.

thanks for your consideration of my feature request.

**Comment by cweijan** [comment]
The current design is a mistake, try set port as `8080/esnodes`.

**Comment by ttbadr** [comment]
seem the port only accepts a numeric value

**Comment by cweijan** [comment]
Version [3.6.7](https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-database-client2) Has been support special url.
