### ISSUE TITLE
[BUG] Custom Delimiter Ignored

### ISSUE THREAD

**Issue by KateYoak** [cweijan/vscode-database-client#157]
- OS INFO : Windows 10 Pro
- database-client.enableDelimiter set to true
- enableDelimiter is seemingly ignored

Run SQLsplits the file on semicolons ignoring delimiter.

![image](https://user-images.githubusercontent.com/1856012/113198026-4509b080-921a-11eb-972e-1fb15cf02ce7.png)

This results in an error:

![image](https://user-images.githubusercontent.com/1856012/113198102-59e64400-921a-11eb-973f-238000dc08c0.png)

There is a work-around:

Select whole file => F9 appears to work, though prints no console output.

**Comment by cweijan** [comment]
Hi, try version 3.6.7.

**Comment by KateYoak** [comment]
Missed your first message.  Will try and get back to you. Thank you!
