### ISSUE TITLE
[BUG] MySQL - Multiple updates/inserts/queries not getting executed in F9

### ISSUE THREAD

**Issue by franklinkf** [cweijan/vscode-database-client#158]
- OS INFO : Windows
- Data Base - MySQL

Earlier the multiple updates/inserts/queries are executed in a single F9.  Now it not getting executed.  Ex:

UPDATE PARAM_SA_ENGINE_MASTER SET SEM_DISPLAY_ORDER = 100 WHERE SEM_WORKSHEET_ID = 1001;
UPDATE PARAM_SA_ENGINE_MASTER SET SEM_DISPLAY_ORDER = 200 WHERE SEM_WORKSHEET_ID = 1017;
UPDATE PARAM_SA_ENGINE_MASTER SET SEM_DISPLAY_ORDER = 300 WHERE SEM_WORKSHEET_ID = 1002;
UPDATE PARAM_SA_ENGINE_MASTER SET SEM_DISPLAY_ORDER = 1100 WHERE SEM_WORKSHEET_ID = 1003;
UPDATE PARAM_SA_ENGINE_MASTER SET SEM_DISPLAY_ORDER = 1200 WHERE SEM_WORKSHEET_ID = 1004;

Earlier if I select the five lines and press F9, the updates gets executed in a single go. Now I have to select each record one by one and press F9

**Comment by cweijan** [comment]
Do you have select it?
Like that:
![image](https://user-images.githubusercontent.com/27798227/113373581-bc1b8200-939d-11eb-8cf1-79811602c910.png)

**Comment by franklinkf** [comment]
Batch update not happening with or without selecting. For both executions mouse icon transforms to working mode and stays like that.

Thank you for the light weight application

**Comment by franklinkf** [comment]
Sir, Can you guide us on this issue.  Thank you

**Comment by franklinkf** [comment]
Sir, I code in MySQL using functions and procedure.  Earlier the function/procedure gets executed wonderfully by a single F9.  It executes both the drop function line and create function block in a single F9.  Execution happens without selecting any text.  But now it doesn't happen in a single F9.  First I need to drop the function by selecting the drop function line.  Then I need to execute by selecting Create function block.  Same issue which exists while executing multiple update scripts is happening  for procedure and function also. A sample file is enclosed.  Please rectify the issue.  I am using this extension for all my MySQL coding.  Thank you

[BS INSPECTION FUNCTION FN_GET_AUDIT_DATE.txt](https://github.com/cweijan/vscode-database-client/files/6285601/BS.INSPECTION.FUNCTION.FN_GET_AUDIT_DATE.txt)

**Comment by cweijan** [comment]
The previous version can be batch edited, but the results are not displayed, version 3.6.9 fix it.
I will add a new command to execute all SQL in later versions.

**Comment by franklinkf** [comment]
Thank you very much.  Now it is working.

Is there any way that you can extend support for Oracle also?
