### ISSUE TITLE
[BUG] Ignoring "" around table names

### ISSUE THREAD

**Issue by NoahCardoza** [cweijan/vscode-database-client#159]
![image](https://user-images.githubusercontent.com/10343470/113305641-1b06cb80-92b8-11eb-86df-a1339900cc54.png)
![image](https://user-images.githubusercontent.com/10343470/113305686-235f0680-92b8-11eb-9980-14cdff965cae.png)

**Comment by cweijan** [comment]
Why need ""
















在 2021-04-01 22:02:16，"Noah Cardoza" ***@***.***> 写道：
