### ISSUE TITLE
bug report :command 'mysql.addConnection' not found

### ISSUE THREAD

**Issue by luozhiyun993** [cweijan/vscode-database-client#16]
![image](https://user-images.githubusercontent.com/23306701/80437611-99cee800-8934-11ea-8b53-9cad96a6fcc8.png)

**Comment by cweijan** [comment]
I can't locate this error. Can you tell me your version of vscode?
This bug is caused by extension initialization fail, have two possibility:
1. extension using API higher than your vscode version.
2. Conflicts with other extensions

**Comment by sleepm** [comment]
ubuntu 18.04.4 lts
vscode 1.44.2
workbench.desktop.main.js:sourcemap:3826 激活扩展“cweijan.vscode-mysql-client”失败: Cannot find module '../../common/constants

**Comment by sleepm** [comment]
linux是大小写敏感的。。

**Comment by cweijan** [comment]
原来如此... 抱歉是因为我重构代码改了文件名大小写, 你更新到1.9.1试试

**Comment by sleepm** [comment]
还是不行。。
ts中require 的文件大小写必须和资源管理器看到的文件大小写一致
比如 require("Abc") 那文件必须叫Abc.ts， 任意一个大小写不同都不行
windows是不敏感的，所以abc.txt 和ABC.txt不能在同一个目录下，会报已有同名文件
我是通过vscode帮助 切换开发人员工具看到console里的报错发现的

**Comment by bingoIsCoder** [comment]
same issue, is there any update?

**Comment by bingoIsCoder** [comment]
environment：
system: wsl 18.04
vscode: 1.44.2
MySQL Client for vscode: 1.9.1

**Comment by cweijan** [comment]
@bingoIsCoder Yes, I got it, fix at tonight, 搬砖中.

**Comment by bingoIsCoder** [comment]
> @bingoIsCoder Yes, I got it, fix at tonight, 搬砖中.

thanks.

**Comment by Bit0r** [comment]
大佬加油，kubuntu 20.04表示唯一能指望的mysql gui就是这个了

**Comment by cweijan** [comment]
1.9.3 has been fixed.

**Comment by opoloko** [comment]
Still having same issue, 1.9.6 and VSC 1.44.2 on MacOS Mojave.
