### ISSUE TITLE
[BUG]你好，我在使用中发现无法删除一个connect

### ISSUE THREAD

**Issue by GIWTO** [cweijan/vscode-database-client#160]
- OS INFO :
![image](https://user-images.githubusercontent.com/40267153/113848821-701c7300-97cb-11eb-9f9a-242790d3e68e.png)

**Comment by GIWTO** [comment]
跳到3.3.6版本可以正常删除连接

**Comment by cweijan** [comment]
你安装这个扩展, 卸载掉其他的,  我发布了多个扩展

https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-mysql-client2
















在 2021-04-07 18:17:52，"GIWTO" ***@***.***> 写道：

跳到3.3.6版本可以正常删除连接

**Comment by NuclearMop** [comment]
我使用这个链接中的扩展，同样无法删除connection。效果是点击delete connection之后无事发生。
![0f85d81a34d6cd980eca62718392d8d](https://user-images.githubusercontent.com/22350132/113957529-fa0f1f00-9851-11eb-847e-ded678ddefed.png)

**Comment by NuclearMop** [comment]
> 我使用这个链接中的扩展，同样无法删除connection。效果是点击delete connection之后无事发生。
> ![0f85d81a34d6cd980eca62718392d8d](https://user-images.githubusercontent.com/22350132/113957529-fa0f1f00-9851-11eb-847e-ded678ddefed.png)

![image](https://user-images.githubusercontent.com/22350132/113957680-42c6d800-9852-11eb-9dcf-cdc73afe4f75.png)
这是我安装的全部extension
