### ISSUE TITLE
Support for SQLite

### ISSUE THREAD

**Issue by tolgaberk** [cweijan/vscode-database-client#161]
- OS Info: Mac OS Big Sur Version 11.2.3
## Sqlite support for this extension would be awesome. 
- I am a mobile developer and most of the time i work with sqlite.
- i use this extension for looking up data on servers but for mobile i am forced to use different db explorer app because they are in sqlite.

**Comment by cweijan** [comment]
1. SQLite has been support on newest version, but I just test by windows, not sure work on other system.
2. At present, simple crud is provided. If there are frequent functions that need to be implemented, please consider contacting me.
