### ISSUE TITLE
[BUG] MySQL Syntax error on attempt to explore tables with space in their name

### ISSUE THREAD

**Issue by yemikudaisi** [cweijan/vscode-database-client#162]
# VERSION INFO :

- Windows 10 Pro, version 10.0.19042 Build 19042
- VSCode, Version 1.55.1.
- MySQL  Version 15.1 Distrib 10.3.28-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- MySQL database client for VSCode, version 3.6.7

# Steps to reproduce

- From VSCode.
- Open The Database Explorer navigator.
- Double click any database with space (" ") within the name (assuming you've configured a database with tables that have space in them).

# Result
In the example below, I double clicked on `tabNumber Card` as shown in snip and SQL query below:

![image](https://user-images.githubusercontent.com/3257276/114297184-13f56f80-9aa7-11eb-813e-64bafb316090.png)

```sql
EXECUTE FAIL:

  SELECT * FROM tabNumber Card LIMIT 100

Message :

  Table '_b886f4548cfdeea6.tabNumber' doesn't exist
```

# Comment

I suspect it is as a result of the extension not back quoting table names and columns.

**Comment by cweijan** [comment]
I think it's MariaDB's problem.

**Comment by yemikudaisi** [comment]
> I think it's MariaDB's problem.

I don't think so, because I'm able to run the below query from you extension when I back quote the table name (to cater for the space character)

```sql
SELECT * FROM `tabNumber Card` LIMIT 100; -- This would be successful
```
However, double clicking on `tabNumber Card` table from the DB explorer yields a similar but different query from the above. The difference being the back quote (`) character.
```sql
SELECT * FROM tabNumber Card LIMIT 100; -- This would fail.
```

**Comment by cweijan** [comment]
Sorry, I read it wrong, because I don't add quotation marks to spaces now. I will fix it in the next version.

**Comment by rrmagnuson** [comment]
I have a MariaDb table called show, which happens to be a reserved word. How can I cause this extension to always `quote` table names and columns?
