### ISSUE TITLE
[BUG] MySQL - SSL connection is required. Please specify SSL options and retry.

### ISSUE THREAD

**Issue by JamesBewley** [cweijan/vscode-database-client#164]
- OS INFO : Mac OS

Trying to connect to an azure hosted MySQL instance which has SSL enabled but the client doesn't appear to support it?

**Comment by cweijan** [comment]
Yes, it not support now, maybe later support.

**Comment by JamesBewley** [comment]
Can confirm this is working in my case (Azure MySQL PaaS).

Brilliant, thank you!
