### ISSUE TITLE
SQL Server Connection Config

### ISSUE THREAD

**Issue by ddiehlpdx** [cweijan/vscode-database-client#168]
- OS Info: Ubuntu 20.04 (home) / Windows 10 Professional (work)

- Connection config for SQL Server does not allow setting parameters for encrypt or trustServerCertificate. Being able to specify these params (and other commonly used connection params, really) when configuring a connection would make this already great extension a lot more useful.

**Comment by metalshanked** [comment]
Since TDS driver supports Windows Auth, would be awesome if that can be added as well

**Comment by cweijan** [comment]
I has set trustServerCertificate default as true, and I don't intend to open the configuration of it, If you have other recommended configuration, please let me know @ddiehlpdx.

I has add domain option to version 3.7.4, but when i using ntlm, it thrrow `The user is not associated with a trusted SQL Server connection`, If you are familiar with tedious, please tell me what to do. @metalshanked 
![image](https://user-images.githubusercontent.com/27798227/117744567-89d22f80-b23b-11eb-8ede-76cbb7e77747.png)

**Comment by metalshanked** [comment]
@cweijan  Thank you!! it is working now with domain and windows auth.

Sorry one more request.  Is it possible to auto suggest data objects as we type?


![image](https://user-images.githubusercontent.com/57646596/117848813-838e8400-b238-11eb-8c47-61ff1cf7be89.png)

**Comment by ddiehlpdx** [comment]
Can confirm that I am able to connect now as well. Much appreciated!
