### ISSUE TITLE
[BUG] Can't save any connectiond

### ISSUE THREAD

**Issue by spraguey** [cweijan/vscode-database-client#169]
- OS INFO : Mac 10.15.7

Maybe I am missing something, but I can't seem to use or save any a connection. I get the form to fill in, enter my info and click connect. I get a green bar that says "connect success!", but that is all. I can't save the connect and nothing appears in the left column for me to navigate or use the connection. I've tried MySQL and MSSQL connections, and they both do the same thing.

**Comment by cweijan** [comment]
Maybe you didn't upgrade the extension version.













At 2021-04-20 22:49:39, "spraguey" ***@***.***> wrote:

OS INFO : Mac 10.15.7

Maybe I am missing something, but I can't seem to use or save any a connection. I get the form to fill in, enter my info and click connect. I get a green bar that says "connect success!", but that is all. I can't save the connect and nothing appears in the left column for me to navigate or use the connection. I've tried MySQL and MSSQL connections, and they both do the same thing.

**Comment by spraguey** [comment]
@cweijan What version should I be at? It is 3.6.8 and this is a new install.

**Comment by spraguey** [comment]
@cweijan I uninstalled and reinstalled and it seems to work now.
