### ISSUE TITLE
Feature Request: SSH key authentication for SSH tunneling

### ISSUE THREAD

**Issue by janosmiko** [cweijan/vscode-database-client#17]
I think it's pretty clear, currently the SSH tunneling only supports password authentication.
Could you add support for pubkey authentication?

And let me use this FR to thank you for your work on this extension!

**Comment by cweijan** [comment]
OK. I add it in next version.
Additional : What is FR? I think star this project is best support.

**Comment by janosmiko** [comment]
> OK. I add it in next version.
> Additional : What is FR? I think star this project is best support.

Feature Request

**Comment by cweijan** [comment]
1.9.4 is supported private key connect.

**Comment by janosmiko** [comment]
I updated and tried the plugin, but I get the following error message:

`Ssh tunel occur eror : Error: All configured authentication methods failed`

(If you let me know how could I configure this plugin to log more verbose, that would probably help to find the solution.)

On the server I see these messages in the secure logo:
```
Apr 29 09:28:52 prod sshd[9099]: Connection from 123.123.123.123 port 52519 on 321.321.321.321 port 22
Apr 29 09:28:52 prod sshd[9099]: Received disconnect from 123.123.123.123 port 52519:11:  [preauth]
Apr 29 09:28:52 prod sshd[9099]: Disconnected from 123.123.123.123 port 52519 [preauth]
```

However, if I connect using password the plugin works well.

**Comment by cweijan** [comment]
Maybe your input path have white space , I didn't call `trim()`

**Comment by janosmiko** [comment]
I found the cause of the issue.
Previously I used `~/.ssh/id_rsa`. I changed it to `/Users/username/.ssh/id_rsa` and now it works.

Thank you for the update!
