### ISSUE TITLE
[BUG]SSH connection with private key cannot persist

### ISSUE THREAD

**Issue by hzn942** [cweijan/vscode-database-client#170]
- OS INFO : MAC 11.2.3
- Step to reproduce:
      - add new ssh connection with a private key(provided private key file path), and connection worked as expected.
      - close vscode
      - restart vscode
      - try to connect again,  but cannot connect

Seems like the private key info is not persisted.

**Comment by cweijan** [comment]
Maybe you changed the location of the key or deleted it.

**Comment by hzn942** [comment]
No, the private key file has not been moved or deleted.

**Comment by hzn942** [comment]
PS:  我安装的拓展是https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-database-client2

我注意到你好像推荐安装https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-mysql-client2

请问有什么区别么? 谢谢🙏

**Comment by cweijan** [comment]
引流用的, 没区别.

**Comment by hzn942** [comment]
谢谢, 这两个拓展我都测试了, 都有问题.. 就是新建链接时能够连上, 完全退出vscode以后, 再连就不行. 
只是用private key文件的时候有这问题. 我如果换成密码登陆, 就没问题.

**Comment by hzn942** [comment]
Made a video to demonstrate the issue:
https://youtu.be/yZS3wyi4tVw

**Comment by cweijan** [comment]
之前以为是ssh隧道呢, 在版本3.7.1修复了这个问题.
