### ISSUE TITLE
Add MongoDB support

### ISSUE THREAD

**Issue by SuspiciousLookingOwl** [cweijan/vscode-database-client#173]

**Comment by SuspiciousLookingOwl** [comment]
Just realized you have [mongo branch](https://github.com/cweijan/vscode-database-client/tree/mongo) 😅. Excited to see it getting merged.

**Comment by cweijan** [comment]
Mongodb is not perfect yet, later.

**Comment by cweijan** [comment]
Version 3.8.3 has been add MongoDB, only basic crud is provided.
