### ISSUE TITLE
增加只读模式

### ISSUE THREAD

**Issue by xtuer** [cweijan/vscode-database-client#175]
- OS Info: Windows 10
目前显示表格数据后是编辑模式，修改数据后会自动更新到数据库，容易造成误操作导致数据错误。

能否增加只读模式，不可以修改数据。
或者修改数据后需要明确的进行保存才能更新到数据库。

**Comment by cweijan** [comment]
修改后会在你按回车或者ctrl+s的时候保存, 没有计划取消.
