### ISSUE TITLE
[BUG] Not active database connection found!

### ISSUE THREAD

**Issue by miksch27** [cweijan/vscode-database-client#176]
- OS INFO : Windows 10 , VS Studio and your Database Client for vscode.
- I can open MySQL tables. I can see  and update data inside of the "DATABASE EXPLORER"
- I can click to define a new query.  But as soon as I want to RUN SQL on my own project I get the error message: "Not active database connection found!"

Where can I define this active database connection? 

TIA!

![image](https://user-images.githubusercontent.com/27285353/116563442-51aa2300-a904-11eb-9497-622ce82ef329.png)

**Comment by cweijan** [comment]
Click this.
![image](https://user-images.githubusercontent.com/27798227/116578752-4ecf2280-a944-11eb-871d-d97641abc6e9.png)

**Comment by miksch27** [comment]
okay, thank you! I haven't seen it before. The schema icon switches to blue. Thank you!
![image](https://user-images.githubusercontent.com/27285353/116618977-22b1a280-a940-11eb-9188-d071b1754697.png)
