### ISSUE TITLE
Can not connect to sql server with named instance

### ISSUE THREAD

**Issue by Serria117** [cweijan/vscode-database-client#177]
I can successfully connect to the server with default instance, but when I setup a new sql server with named instance (through port 1533 which is allowed in the firewall setting), I don't know how to connect to it (in the SQL Server Management Studio everything work fine). Did I do something wrong?
The connecting screen stucks like this:
![image](https://user-images.githubusercontent.com/80811210/116886420-4122e100-ac53-11eb-9e97-89db66904fb7.png)
While SSMS successfully connected to the database with this parameters:
![image](https://user-images.githubusercontent.com/80811210/116948106-b7056780-aca8-11eb-80cc-d248b5340c04.png)

**Comment by dagovin** [comment]
Hi, i have the same problem, I can't connect to mssql

**Comment by dagovin** [comment]
But, what should I write there? I wrote the ip server, the name server, the hostname, and not working

**Comment by cweijan** [comment]
Version 3.7.4 has support it.
![image](https://user-images.githubusercontent.com/27798227/117744431-4081e000-b23b-11eb-94a2-a8a414c9dcd0.png)

**Comment by dagovin** [comment]
hi, sorry, still not working, the actual version is 3.7.6 the error is in image, thanks
![Captura de Pantalla 2021-05-12 a la(s) 5 45 36 p  m](https://user-images.githubusercontent.com/80778421/118053488-3b5f8680-b34a-11eb-8865-40b17275a63e.png)

**Comment by cweijan** [comment]
Change encrypt to false @dagovin.

**Comment by cweijan** [comment]
Change the encrypt to false @dagovin .
