### ISSUE TITLE
[BUG] png icons are broken

### ISSUE THREAD

**Issue by SeluMesu** [cweijan/vscode-database-client#181]
- OS INFO :
It seems that vs code can't display .png icons.
![Screenshot from 2021-05-08 21-03-31](https://user-images.githubusercontent.com/50427240/117557482-33010600-b041-11eb-972d-34c35124581f.png)
![Screenshot from 2021-05-08 21-03-56](https://user-images.githubusercontent.com/50427240/117557486-35636000-b041-11eb-8dd1-3106b5c829b9.png)
I tried by replacing png icons with svg and it worked.

**Comment by cweijan** [comment]
It's because the pixels are too big. I'll fix it in the next version.

**Comment by cweijan** [comment]
Fix at version 3.7.3.
