### ISSUE TITLE
Which VS Code version is main - cweijan.vscode-mysql-client2 or cweijan.vscode-database-client2 ?

### ISSUE THREAD

**Issue by MurzNN** [cweijan/vscode-database-client#182]
There are two active VS Code Extensions published with same link to this repo and similar description:

1. https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-mysql-client2 
- Name: MySQL
- Version 3.8.1
- Last updated 5/13/2021

2. https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-database-client2
- Name: Database Client
- Version 3.7.4
- Last updated 5/11/2021

Having two very similar versions is very confusing! Seems the first version is fresh, and additionally have support for SQLite, regarding to description, but its name is only "MySQL", will other database types be dropped in further releases? Hovewer the second version have more generic name, matching all database types, but have lower version number... So which to choose? :confused: 

Can you please clarify (and update description of extensions in VS Code repo) which one to choose for have the main version, that will be regulary updated?

**Comment by cweijan** [comment]
The two functions are the same. The purpose of publishing multiple extensions is to let more people discover the extension, [mysql](https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-mysql-client2) Always released first.
