### ISSUE TITLE
[BUG] Missing table name from trigger definition

### ISSUE THREAD

**Issue by janosroden** [cweijan/vscode-database-client#183]
When I select a trigger the extension correctly shows trigger definition except the table name:

```sql
DROP TRIGGER t on [table_name];
CREATE TRIGGER t AFTER INSERT ON public.x FOR EACH ROW EXECUTE FUNCTION fx()
```

Not a big deal, but the trailing semicolon is missing too.

Steps to reproduce:
1. `docker run --rm -it -e POSTGRES_PASSWORD=password -p 5432:5432 --name pg  postgres:12`
1. `docker exec  pg /usr/bin/psql -U postgres -c 'create table x (id int)' -c "create function fx() returns trigger as 'begin return record; end;' language plpgsql" -c 'create trigger t after insert on x for each row execute procedure fx()'`
1. Create connection to the new local postgres (default settings)
1. Select the trigger in the database explorer.

Still, the best pg extension I've seen, great job!

**Comment by cweijan** [comment]
PostgreSQL has no easy way to get the table name, so I'm not going to implement it.

**Comment by janosroden** [comment]
I see, looking into a code it's not a quick fix. Okay then, I can live without it.
Cheers
