### ISSUE TITLE
[BUG] Duplicates Postgres tables and columns - Schema support?

### ISSUE THREAD

**Issue by obambrough** [cweijan/vscode-database-client#184]
- OS INFO : MacOS Catalina 10.15.7
- Database Client 3.8.2
- VS Code 1.56.2

I create a connection to a Postgres database (running in a local container.) Database Client lists the tables within each schema twice. And if I expand each table it shows the columns multiple times each. Other VS Code Postgres extensions (e.g. ckolkman.vscode-postgres) are not showing the duplicate tables or repeated column names.

Is this an issue with supporting schemas?

On the investigations table the primary key is a combination of the id, org_id and type fields, so maybe the way Database Client is showing that is causing the type to be shown 3 times and then due to having two schemas that's causing it to be shown twice for a total of 6 entries.

Duplicate table names
![dup tables](https://user-images.githubusercontent.com/1922249/118416438-b348ec00-b67d-11eb-8c7c-7f74d38c82dc.png)

Expand a table, shows the column names repeated multiple times
![duplicate tabes or fields](https://user-images.githubusercontent.com/1922249/118416441-b5ab4600-b67d-11eb-8a1d-c90feb9e62e3.png)

**Comment by cweijan** [comment]
Fix at version 3.8.3.

**Comment by obambrough** [comment]
Awesome - it does look like its fixed with 3.8.3
