### ISSUE TITLE
[BUG] Could not register service workers

### ISSUE THREAD

**Issue by dongshimou** [cweijan/vscode-database-client#185]
- OS INFO :
windows 10
ts project

### bug

When i open a new connect.

加载 Web 视图时出错: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

**Comment by cweijan** [comment]
是vscode还是在线IDE.

**Comment by dongshimou** [comment]
> 是vscode还是在线IDE.

@cweijan vscode. 重启window之后就没有这个问题了。

**Comment by cweijan** [comment]
那就奇怪了, 目前还没有遇到过这个问题, 建议更新到最新版本vscode并重启电脑.
