### ISSUE TITLE
[BUG] Database showing up in 'other explorer' panel

### ISSUE THREAD

**Issue by obambrough** [cweijan/vscode-database-client#188]
- OS INFO : MacOS Catalina 10.15.7
- Database Client 3.8.3
- VS Code 1.56.2

I added a Postgres connection. It shows up under the 'other explorer' panel next to a redis connection - I believe with Database Client 3.8.2 it was showing up under the other panel provided by the 'Database Explorer' panel.

![image](https://user-images.githubusercontent.com/1922249/118665856-abde2b80-b7c0-11eb-9b92-c47aaeda04d9.png)

**Comment by cweijan** [comment]
Fix at 3.8.4.

**Comment by mhkb** [comment]
@cweijan are you able to push 3.8.4 through to open vsx so this bug can be fixed in the VSCodium extension?

**Comment by cweijan** [comment]
@mhkb has been publish.

**Comment by mhkb** [comment]
@cweijan thank you!
