### ISSUE TITLE
[BUG] Missing names for panels

### ISSUE THREAD

**Issue by obambrough** [cweijan/vscode-database-client#189]
- OS INFO : MacOS Catalina 10.15.7
- Database Client 3.8.3
- VS Code 1.56.2

VS Code allows you to hide panels. When I click on the triple dots for the panel it doesn't show any names. My OS is configured with English US (if this is a missing translations issue.)

![image](https://user-images.githubusercontent.com/1922249/118666074-de882400-b7c0-11eb-98f6-661233e841f5.png)

**Comment by cweijan** [comment]
There is a contrast between having a name and not having a name, which is deliberately removed.
![image](https://user-images.githubusercontent.com/27798227/118744946-d34bfb80-b887-11eb-9fae-2d391780a7ec.png)
![image](https://user-images.githubusercontent.com/27798227/118744956-d810af80-b887-11eb-8634-83fcad15b415.png)

**Comment by obambrough** [comment]
I see your point and understand. It was surprising not seeing the names in the panel selection (hence the issue.) I do combine panels as I've got a lot of extensions installed :) so just pointing out they can appear in other contexts (not just the two panels together), like this:

![image](https://user-images.githubusercontent.com/1922249/118823794-443ee380-b887-11eb-954d-8c875d540824.png)

Just for comparison here's a couple of other extensions in a separate panel. Maybe there's a common pattern to name the panel 'Explorer' followed by the more specific explorer type, so for Database Client maybe it'd be 'Explorer: Database' and 'Explorer: Other'

![image](https://user-images.githubusercontent.com/1922249/118824615-fecee600-b887-11eb-8643-482303f5bdb6.png)

Great extension and feel free to close this if you want to keep the names as you have them.

**Comment by cweijan** [comment]
Add name at version 3.8.5.
