### ISSUE TITLE
redis 不支持ssl 是吗？

### ISSUE THREAD

**Issue by gongxic** [cweijan/vscode-database-client#190]
- OS Info:

**Comment by cweijan** [comment]
我还不知道redis有ssl呢, 你用的redis6吗.

**Comment by gongxic** [comment]
@cweijan  用的azure上的 redis 版本写的是 4.0.13

**Comment by cweijan** [comment]
在版本3.8.6支持了ssl.

**Comment by Thetiso** [comment]
参照azure的文档，https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-nodejs-get-started  
azure虽然也需要ssl, 但他使用的是host+key的方式链接redis, 插件里面好像不支持这种链接方式 @cweijan

**Comment by cweijan** [comment]
@Thetiso 看起来key就是密码, 你勾选User SSL, 不填证书就行.

**Comment by Thetiso** [comment]
> @Thetiso 看起来key就是密码, 你勾选User SSL, 不填证书就行.
@cweijan   Get it!  感谢~  我后来发现是自己搞错了  这个应该是tls  不是ssl,  sorry~

**Comment by PetrusZ** [comment]
Hi，虽然已经close很久了，但我还是需要问一下，怎么使用tls呢？

**Comment by cweijan** [comment]
@PetrusZ 我上面的回复就说了啊

**Comment by PetrusZ** [comment]
@cweijan 谢谢，发现好像不是tls的问题。。
