### ISSUE TITLE
[Feature Request] Workspace Level Connection Profiles

### ISSUE THREAD

**Issue by fahimalizain** [cweijan/vscode-database-client#191]
It would be great if we could have the DB Connection Profiles defined at workspace level. This is useful for custom redis-servers that gets run only during debug sessions.

Another use case is to have different specific database connections when working in different workspaces.

**Comment by cweijan** [comment]
You can set connection target  as workspace.
![image](https://user-images.githubusercontent.com/27798227/118931777-e9d27f80-b979-11eb-93ac-64b93bea4f89.png)
The edit connection configuration is planned and will be opened in later versions.
