### ISSUE TITLE
[BUG] Forced html string parsing, into plain text

### ISSUE THREAD

**Issue by ghost** [cweijan/vscode-database-client#192]
- OS INFO : Windows 10
- Database Client: 3.8.4
- Vs Code: 1.56v

The string variable (nvarchar | varchar) that contain html code, always being parsed in text plain, at ( update | create) query

![image](https://user-images.githubusercontent.com/38162485/119130946-890e7a00-ba41-11eb-8ced-34b9f172e537.png)

**Comment by cweijan** [comment]
Fix at version 3.8.5.
