### ISSUE TITLE
[BUG] sqlite exec file is not executable on Linux

### ISSUE THREAD

**Issue by dkja** [cweijan/vscode-database-client#194]
- OS INFO :
Arch Linux

getSqliteBinariesPath() returns path to executable but it's not executable.
However maybe you should use OS's sqlite3 if exists and version is ok?

But if not exists draw error notification.
Or you can use settings' property to define sqlite path.

**Comment by cweijan** [comment]
I used SQLite3 command by path in version 3.8.5, but I couldn't test it because I didn't use Linux GUI.
