### ISSUE TITLE
[BUG] Ssh tunel occur error : Error: All configured authentication methods failed

### ISSUE THREAD

**Issue by haodi** [cweijan/vscode-database-client#195]
- OS INFO :
![image](https://user-images.githubusercontent.com/8063631/119233120-04fbe580-bb5a-11eb-9756-802f1656d71c.png)

Everything is normal when using SSH on Sequel Pro, and using the mysql plug-in on Vscode has been unsuccessful.  it may be a bug  🤔

**Comment by cweijan** [comment]
Consider modifying your private key format.

**Comment by cweijan** [comment]
SSH only support private keys generated by ssh-keygen, which means pkcs8 is not support.
