### ISSUE TITLE
What icon style do you use in the database tab?

### ISSUE THREAD

**Issue by Shuai-Xie** [cweijan/vscode-database-client#197]
I've used [Material Icon Theme](https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme). However, the table icons still look not well as yours.

![image](https://user-images.githubusercontent.com/18352713/119290209-aed49280-bc7e-11eb-8003-024a07a9bc58.png)

![image](https://user-images.githubusercontent.com/18352713/119290060-6a48f700-bc7e-11eb-82d7-70926f11e1db.png)

Thanks in advance.

**Comment by cweijan** [comment]
Icon is using product icon, not theme icon.
![image](https://user-images.githubusercontent.com/27798227/119292648-653a7680-bc83-11eb-8d1b-08b60c435716.png)

**Comment by Shuai-Xie** [comment]
Thanks for your quick reply. I use a matched [Material Product Icons](https://marketplace.visualstudio.com/items?itemName=PKief.material-product-icons) now.

![image](https://user-images.githubusercontent.com/18352713/119303429-4692aa80-bc98-11eb-8c6a-a9dd1c572215.png)

![image](https://user-images.githubusercontent.com/18352713/119303437-4abec800-bc98-11eb-9270-c74830263edf.png)

Thanks very much. You've solved my issue.

**Comment by mercurykd** [comment]
> Icon is using product icon, not theme icon.

and in the nosql section? for example file icons in ssh?
