### ISSUE TITLE
[BUG]SQLite can't work

### ISSUE THREAD

**Issue by Kian-Miller** [cweijan/vscode-database-client#198]
- OS INFO : Linux on Docker
- When I want to connect a *sqlite*, I select right file,then is show as follow in vscode:
![image](https://user-images.githubusercontent.com/47779131/119357365-0d7b2a00-bcda-11eb-8f2f-635dd3e6242f.png)

- OUTPUT is: 2021-05-24 21:41:28 Error: Error: spawn /root/.vscode-server/extensions/cweijan.vscode-database-client2-3.8.5/sqlite/sqlite-v3.26.0-linux-x64 EACCES
![image](https://user-images.githubusercontent.com/47779131/119356845-76ae6d80-bcd9-11eb-93cb-5fa957bc42fb.png)

- *When i run in terminal,it shows as follows:*
![image](https://user-images.githubusercontent.com/47779131/119356658-436bde80-bcd9-11eb-9381-d65ba3fe8da7.png)
- **other connect is right, like mysql**

**Comment by Kian-Miller** [comment]
This is because I don't install *sqlite*
when I run those terminal, It solves the problem:
``` bash
sudo apt-get install sqlite 
sudo apt-get install libsqlite3-dev
```

**Comment by cweijan** [comment]
If you don't install SQLite, you will use the built-in SQLite within extension, but it doesn't seem to work in Linux because I haven't tested Linux.
