### ISSUE TITLE
[BUG]连接SqlServer数据库查询日期类型数据错误

### ISSUE THREAD

**Issue by Weijee** [cweijan/vscode-database-client#199]
好像只有MySQL数据库的连接界面有TimeZone的选项，其他的连接都没有该选项。
SqlServer数据库中日期类型的数据总是被增加了8个小时。（中国北京 东八区）
例如：SqlServerManagement中查询的日期数据为 **2021-05-06 09：00：00**
使用该组件查询的数据为 **2021-05-06 17：00：00**

**Comment by cweijan** [comment]
Fix at version 3.8.8.
