### ISSUE TITLE
bug 报告

### ISSUE THREAD

**Issue by JerryCrab** [cweijan/vscode-database-client#2]
run query 无法显示结果，只能出现一个空窗口
vscode 为最新版
mysql版本为5.7.25
![image](https://user-images.githubusercontent.com/45428865/78501156-0539f580-778d-11ea-93c9-8b27ba2f512a.png)

**Comment by cweijan** [comment]
更新下版本试试

**Comment by YannLex** [comment]
@cweijan 你好，最新版2.9.2遇到通用问题
