### ISSUE TITLE
syntax error, insert item into table, by extension query web

### ISSUE THREAD

**Issue by bingoIsCoder** [cweijan/vscode-database-client#20]
```
EXECUTE FAIL:

  INSERT INTO test_table(user_id,meeting_id,text,modified_on,created_on) VALUES(1,1,测试 文本,1588133313,1588133313)

ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '文本,1588133313,1588133313)' at line 1
```

it seams that single quotes has bean omitted with `text` type.

extension version: 1.9.4

**Comment by cweijan** [comment]
you need change sql to 
`  INSERT INTO test_table(user_id,meeting_id,text,modified_on,created_on) VALUES(1,1,'测试 文本',1588133313,1588133313)`

**Comment by bingoIsCoder** [comment]
> you need change sql to
> ` INSERT INTO test_table(user_id,meeting_id,text,modified_on,created_on) VALUES(1,1,'测试 文本',1588133313,1588133313)`

the sql is created automatically, by query web.
![image](https://user-images.githubusercontent.com/22683240/80561343-bc393200-8a16-11ea-9614-340f848a91d6.png)

**Comment by bingoIsCoder** [comment]
> you need change sql to
> ` INSERT INTO test_table(user_id,meeting_id,text,modified_on,created_on) VALUES(1,1,'测试 文本',1588133313,1588133313)`

the sql is created automatically by extension web.
![image](https://user-images.githubusercontent.com/22683240/80561476-310c6c00-8a17-11ea-8e6a-d8b8f222c739.png)

**Comment by cweijan** [comment]
1.9.5 fixed.
