### ISSUE TITLE
[BUG] 点击connect之后侧边栏不显示

### ISSUE THREAD

**Issue by Mrzhangxd** [cweijan/vscode-database-client#200]
- OS INFO : windows10

**Comment by cweijan** [comment]
有两个侧边栏, 你看下旁边的.
![image](https://user-images.githubusercontent.com/27798227/120050321-93d39b00-c04f-11eb-9940-8c9799740a8e.png)

**Comment by Mrzhangxd** [comment]
我还纳闷咋多了一个redis的扩展出来，我手贱给隐藏了

**Comment by Mrzhangxd** [comment]
![image](https://user-images.githubusercontent.com/16274179/120154471-828eb800-c222-11eb-8b97-7b8635f1cdda.png)
为啥加的mysql连接会跑到nosql 这个里面呢？我之前加数据库，DATABASE一直只显示一个，我都怀疑是电脑出问题了

**Comment by cweijan** [comment]
@Mrzhangxd 升级插件版本, 这是老版本的一个bug
