### ISSUE TITLE
[BUG] Redis connection name not showing up on Explorer after "connect success!" message

### ISSUE THREAD

**Issue by Rezwanul-Haque** [cweijan/vscode-database-client#201]
- OS INFO :
            Version: 1.56.2
            Commit: 054a9295330880ed74ceaedda236253b4f39a335
            Date: 2021-05-12T16:45:26.313Z
            Electron: 12.0.4
            Chrome: 89.0.4389.114
            Node.js: 14.16.0
            V8: 8.9.255.24-electron.0
            OS: Linux x64 5.8.0-53-generic
            
          
![redis_issue](https://user-images.githubusercontent.com/22642254/120053243-fc6c4900-c04a-11eb-8c44-713edece67d2.png)

**Comment by cweijan** [comment]
Redis connection in this pannel.
![image](https://user-images.githubusercontent.com/27798227/120054591-61cc3400-c063-11eb-8a31-a792c2f24850.png)
