### ISSUE TITLE
[BUG] Mongodb connection problems

### ISSUE THREAD

**Issue by ceyhunn** [cweijan/vscode-database-client#202]
- OS INFO : Manjaro  Gnome Stable 
I can't connect to manually created db, only works admin db with root user, also admin db connection not saved in database explorer.

**Comment by cweijan** [comment]
Mongo connection in other explorer.
![image](https://user-images.githubusercontent.com/27798227/120070863-1fd0db80-c0bf-11eb-9157-0076fb968c3f.png)

**Comment by ceyhunn** [comment]
Oops, sorry, I saw, many thanks. Seems like pagination doesn't work:
![Screenshot from 2021-05-29 17-42-00](https://user-images.githubusercontent.com/5506156/120072478-31a58500-c0a5-11eb-962f-de6523118666.png)

**Comment by cweijan** [comment]
Support pagination of MongoDB at version 3.8.9.
