### ISSUE TITLE
SOCKS5 proxy

### ISSUE THREAD

**Issue by pwmcintyre** [cweijan/vscode-database-client#203]
hi — firstly, i really like this extension, great work 👌 

I'm wondering if there's a way to use an **_existing_** SOCKS5 proxy with this?
I see there's code which starts up it's own proxy, but i can't use it (or it's prohibitively complicated to) due to the way our company sets up ephemeral keys and what-not ...

I wonder if it would be too much trouble to set existing proxy details in the "Connect to Database Server" config page?

thanks

**Comment by cweijan** [comment]
Socks5 is too rare. This extension does not support it and there is no plan to support it. I recommend you use SSH tunnel.

**Comment by pwmcintyre** [comment]
sorry — i didn't mean SOCKS5 specifically, in reality i have no idea what version of "socks" i'm using

but SOCKS isn't rare — you're literally using it in this repo here:
https://github.com/cweijan/vscode-database-client/blob/79b17b51a6926a56df864af7d1f7f8f1a639e172/src/model/ssh/sshConnectionNode.ts#L58-L65

**Comment by cweijan** [comment]
Do you mean how to turn on the sock5 proxy? If so, the current extension only supports windows.
![image](https://user-images.githubusercontent.com/27798227/120570880-9e28d700-c44b-11eb-8f0b-91ba72408bc3.png)
I think what you said before refers to connecting to the database through the sock5 proxy.

**Comment by pwmcintyre** [comment]
let me try to clarify ...

this extension has a feature where it will:
1. use `ssh` to establish a proxy for you (see link above)
2. route traffic through it

but what if i already have my own proxy? can i bypass step 1 and continue to step 2?

currently there's no way for me to say "use a proxy, but don't attempt to set one up, just use this config"

i figure since there's already code to use a proxy, this might be an easy feature — i just need a way to enter the details (ie. `localhost:1080`)

make sense?

**Comment by cweijan** [comment]
This extension never support traffic through the sock5 proxy, it just supports creating sock5 proxy on windows.
