### ISSUE TITLE
[BUG] Empty string result showing NULL

### ISSUE THREAD

**Issue by eshizhan** [cweijan/vscode-database-client#204]
The result showing NULL while `scope.row[scope.column.title]` is empty string. We need merging these logic, processing on `<template>` or `<script>`.

https://github.com/cweijan/vscode-database-client/blob/45cc8f05bf333864b9604a5874dec42f0ab95ef4/src/vue/result/component/Row/index.vue#L11-L18

https://github.com/cweijan/vscode-database-client/blob/45cc8f05bf333864b9604a5874dec42f0ab95ef4/src/vue/result/component/Row/index.vue#L29-L37

**Comment by cweijan** [comment]
Thanks, fix at version 3.8.6.
