### ISSUE TITLE
DROP IF EXISTS TRIGGER TRIGGER_NAME

### ISSUE THREAD

**Issue by Weijee** [cweijan/vscode-database-client#205]
- OS INFO :
I was trying to connect my mssqlserver by using this tool.
when i double click my table-trigger to view my trigger code,
and i notice there is a bug in the auto-generated code.
![image](https://user-images.githubusercontent.com/13539500/120627815-a1958000-c496-11eb-913b-d304f5144637.png)
the correct code should be **DROP TRIGGER IF EXISTS TRIGGER_NAME**   
  
And another thing is after the DROP sentence, it will be better to add a "GO" 
![image](https://user-images.githubusercontent.com/13539500/120628673-88d99a00-c497-11eb-9a3a-ae83b84ccd37.png)

**Comment by cweijan** [comment]
Thanks, it will fix in next version.

**Comment by cweijan** [comment]
Fix at version 3.8.7.
