### ISSUE TITLE
[BUG] SqlServer "collation conflict" Error getting tables

### ISSUE THREAD

**Issue by ajf1234** [cweijan/vscode-database-client#206]
Not sure if this is something you can resolve on this end, but I don't get this error from any other db connecting app.

- OS INFO : Windows 10

Execute sql fail : SELECT
        TABLE_NAME 'name',ds.row_count rows
      FROM
        INFORMATION_SCHEMA.TABLES t
        join sys.dm_db_partition_stats ds on ds.object_id = object_id(concat(t.TABLE_SCHEMA, '.', t.TABLE_NAME))
        and ds.index_id IN (0, 1)
      WHERE
        TABLE_TYPE = 'BASE TABLE'
        AND TABLE_SCHEMA = 'ReportingMart' order by TABLE_NAME
2021-06-03 20:26:37 RequestError: Cannot resolve the collation conflict between "Latin1_General_100_CI_AS_KS_WS_SC" and "SQL_Latin1_General_CP1_CI_AS" in the concat operation

**Comment by ajf1234** [comment]
Excellent app by the way

**Comment by cweijan** [comment]
I can run this sql, not any mistake.

**Comment by cweijan** [comment]
Fix at version 3.8.9.

**Comment by ajf1234** [comment]
@cweijan Thank you! Now I get a this error, but it's not your fault. I am curious what DBeaver is doing to get the table schemas that is different than this app though.

`2021-06-16 06:35:45 Execute sql fail : SELECT
        TABLE_NAME 'name',ds.row_count rows
      FROM
        INFORMATION_SCHEMA.TABLES t
        join sys.dm_db_partition_stats ds on ds.object_id = object_id(t.TABLE_SCHEMA+ '.'+ t.TABLE_NAME)
        and ds.index_id IN (0, 1)
      WHERE
        TABLE_TYPE = 'BASE TABLE'
        AND TABLE_SCHEMA = 'ReportingMart' order by TABLE_NAME`
`2021-06-16 06:35:45 RequestError: The user does not have permission to perform this action.`

**Comment by cweijan** [comment]
I think it's because DBeaver not join dm_db_ partition_ stats table, I will not join it in the next version. If you still need to use 
this extension, consider using the admin account right now.
