### ISSUE TITLE
[BUG]使用该插件创建完数据库后无法创建表

### ISSUE THREAD

**Issue by vamosdalian** [cweijan/vscode-database-client#208]
- OS INFO :macos 11.2.3 MacBook Pro (13-inch, M1, 2020)
- vscode:Version: 1.56.2 (Universal)
- cweijan.vacode-mysql-client2:v3.8.6
在使用该插件连接到数据库后创建新的数据库,在没有table的情况下,无法将某个database设置为active,没有active database就无法create table,自相矛盾

**Comment by cweijan** [comment]
你点这个按钮就可以.
![image](https://user-images.githubusercontent.com/27798227/120789388-23071400-c564-11eb-914b-cac7abc7435d.png)
