### ISSUE TITLE
Right Click Option Not Showing in 1.9.1

### ISSUE THREAD

**Issue by silverbullettruck2001** [cweijan/vscode-database-client#21]
In issue (https://github.com/cweijan/vscode-mysql/issues/4#event-3271741329) it was noted that the right click option was added, but this is not visible in 1.9.1.

_Originally posted by @cweijan in https://github.com/cweijan/vscode-mysql/issues/4#issuecomment-618436835_

**Comment by cweijan** [comment]
![image](https://user-images.githubusercontent.com/27798227/80658983-35d62c00-8aba-11ea-8ab0-2e566e94a70c.png)
change active db is appear on sql editor context menu.
The db node already has `open query`, so `select db` is unnecessary.
