### ISSUE TITLE
Is there any way to select one or many rows and copied like insert sql string?

### ISSUE THREAD

**Issue by baiyyee** [cweijan/vscode-database-client#210]
Is there any way to select one or many rows and copied like insert sql string?

**For example:**
id, name, age
1,'testuser',18

Copied insert sql string like:
insert into userinfo ('id', 'name', 'age') values (1,'testuser', 18);

**Comment by cweijan** [comment]
Select row then export to sql.
![image](https://user-images.githubusercontent.com/27798227/120912501-46e06c00-c6c2-11eb-9bd0-2ec63bfa9bf6.png)
