### ISSUE TITLE
[BUG] SQLite not found 

### ISSUE THREAD

**Issue by m0t1x** [cweijan/vscode-database-client#213]
- OS INFO : macOS 11.4 Big Sur

I have two installations of SQLite, the macOS orignial and from homebrew. Extension tries to use the binary for macOS from the location `${HOME}/.vscode/extensions/cweijan.vscode-database-client2-3.8.6/sqlite/sqlite-v3.26.0-osx-x86` with error  `EACCES` Since I am using M1 macbook, so x86 can't work (maybe in rosseta).

Anyway, if I create the link `sqlite-v3.26.0-osx-x86 -> /usr/bin/sqlite3` inside `${HOME}/.vscode/extensions/cweijan.vscode-database-client2-3.8.6/sqlite` everything works. 

Question is why extensions did not found the sqlite3 from OS installation?

**Comment by cweijan** [comment]
This seems to be because you don't have permission to execute, I only tested SQLite on windows.

**Comment by m0t1x** [comment]
This error:
```
2021-06-07 13:23:05 Error: Error: spawn /Users/mmatic/.vscode/extensions/cweijan.vscode-database-client2-3.8.6/sqlite/sqlite-v3.26.0-osx-x86 EACCES
``` 
is caused by wrong binary - I have arm cpu, not x86.

My question is why the default sqlite from `/usr/bin/sqlite3` was not found?

**Comment by cweijan** [comment]
This is a bug, I will fix it in the next update.

**Comment by cweijan** [comment]
Hi, try version 3.8.7.

**Comment by m0t1x** [comment]
It is working now. Thank You.

**Comment by nvmker** [comment]
Hi, I have the same issue but on x86 mac with macOS Big Sur 11.5 and latest version of extension(v3.9.9).
There is a `/usr/bin/sqlite3` binary comes preinstalled with macOS.

**Comment by cweijan** [comment]
@nvmker Change sqlite3 to sqlite.

**Comment by nvmker** [comment]
Yep, it works, but it's a kind of dirty hack.
Maybe you can add a config variable for path to sqlite? It will be useful since beside Windows there is also macOS and many kinds of Linux distributions where sqlite can be somewhere else and have a whatever name.
I can make an issue for that enhancement.
