### ISSUE TITLE
[BUG]PostgreSQL tableview can't select checkbox. PostgreSQL的表格视图无法勾选。

### ISSUE THREAD

**Issue by zhangjiankui** [cweijan/vscode-database-client#214]
- OS INFO : MacOS 11.2 
- vscode version: 1.56.2

![image](https://user-images.githubusercontent.com/26133797/121486748-0192a600-ca04-11eb-819e-aa225eac4978.png)

When open a PostgreSQL table，I can't use the select checkbox in the left side of the view.
左边的勾选框用不了

**Comment by cweijan** [comment]
表如果没有主键就无法勾选.
