### ISSUE TITLE
[BUG] Can't edit index in Design table view

### ISSUE THREAD

**Issue by Chronostasys** [cweijan/vscode-database-client#216]
- OS INFO : windows10 2004
- vscode version1.56

all data in the index panel of Design table view is empty and cannot be edit.  

![image](https://user-images.githubusercontent.com/49905799/121498579-217b9700-ca0f-11eb-9ce1-bdb0b3e88225.png)

**Comment by cweijan** [comment]
What is your connection database type.

**Comment by Chronostasys** [comment]
> What is your connection database type.

mysql

**Comment by oleksandr-diudiun** [comment]
same problem on Latest OS X iMac 1M

**Comment by cweijan** [comment]
@noonehos  I think this is caused by the database version, please let me know your database version .

**Comment by kytrun** [comment]
Mysql 8 occurs this problem.

**Comment by cweijan** [comment]
Fix at version 4.1.0.
