### ISSUE TITLE
[BUG] [PostgreSQL] Can't select data from tables, containing capital characters in table name

### ISSUE THREAD

**Issue by MurzNN** [cweijan/vscode-database-client#217]
For example, I have the table `CountryRegions`, when I click on this table - extension generates the SQL query:
```sql
SELECT * FROM CountryRegions LIMIT 100
```
that fails with error:
```
EXECUTE FAIL:
  SELECT * FROM CountryRegions LIMIT 100
Message :
  relation "countryregions" does not exist
```
But for tables, containing only lower case characters in name, such as `country_regions` - all works well.

The source of problem is peculiarity of PSQL - all that is not enclosed in double quotes are case-insensitive, more info here https://www.postgresql.org/docs/9.1/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS

The solution of this problem is enclosing the table name in double quotes like this:
```sql
SELECT * FROM "CountryRegions" LIMIT 100
```
This must be done for all tables, containing non-lowercase characters and other special characters like dashes. But no problem is if extension will always enclose all table names with double quotes.

Can you please add this fix to next versions of extension? Thanks.

**Comment by cweijan** [comment]
Fix at version 3.8.8.
