### ISSUE TITLE
[BUG] 'undefined' while NULL field export to sql or csv

### ISSUE THREAD

**Issue by eshizhan** [cweijan/vscode-database-client#218]
- OS INFO : Linux

Query result `row` missing data while field is `null`.

https://github.com/cweijan/vscode-database-client/blob/9d360f4d376d45c56d6cbe7fcf2e2aea69ac265c/src/service/export/exportService.ts#L94-L103

**Comment by cweijan** [comment]
Fix at version 3.8.8.
