### ISSUE TITLE
Support varbinary fields

### ISSUE THREAD

**Issue by FlorianMoser** [cweijan/vscode-database-client#22]
Definately the best MySQL editor for VSCode. Any chance you support the varbinary field type in the near future?

Currently the addon only shows a number (probably the value of the first byte) in a varbinary field. Editing the field also doesn't work.

**Comment by cweijan** [comment]
Binary type does not support now, I will try to support him.

**Comment by cweijan** [comment]
In the previous version, the display of binary text has been supported. For other binary data, there is currently no better way to support it, so I will close the issue.
