### ISSUE TITLE
Support data editing for Postgres on MacOS

### ISSUE THREAD

**Issue by sbaranov** [cweijan/vscode-database-client#221]
A great extension because it seems like the only extension that supports direct editing of table data. This editing works fine for Postgres on Windows, but unfortunately it looks somehow disabled on MacOS? It's unclear if it's I need to do additional configuration before I can edit data on MacOS?

**Comment by cweijan** [comment]
Table must have primary key.

**Comment by sbaranov** [comment]
The table has a primary key. The editing has just stopped working on Windows too. It looks like something changed around revision 3.8.7 or 3.8.8. All fields are uneditable, and when I click on Open Edit Dialog, I see this incomplete dialog box:

<img width="600" alt="Screen Shot 2021-06-13 at 9 38 14 AM" src="https://user-images.githubusercontent.com/1067150/121815442-7136aa00-cc2b-11eb-98ec-19aadee1e896.png">

**Comment by cweijan** [comment]
Fix at version 3.8.9.

**Comment by sbaranov** [comment]
Verified, thank you!
