### ISSUE TITLE
Privilege management 

### ISSUE THREAD

**Issue by GuimLe** [cweijan/vscode-database-client#222]
This extension seems very good, I'm trying it since few weeks but I like it.
Is it possible to add privilege management to add/edit/delete users, view allowed privileges on tables, views etc ?
I'm running MariaDB 10.3 and I don't know if all others databases are using this system but all SQL based databases should.

**Comment by cweijan** [comment]
You can check below setting to show users, but I have no plan to support the management of privilege.
![image](https://user-images.githubusercontent.com/27798227/122154954-967c2000-ce98-11eb-9ed2-27debb452bf3.png)
