### ISSUE TITLE
Add search content over complete database

### ISSUE THREAD

**Issue by ghost** [cweijan/vscode-database-client#223]
- OS Info: windows 10
It would be fantastic have the option to search content in any columns and tables over complete database.

Something similar to "Database / Search Table Data ..." option in mysql workbench.
:)

**Comment by cweijan** [comment]
I never using mysql workbench, so you need to provide pictures to let me know what the function is.

**Comment by cweijan** [comment]
If you mean table search, you can do it like below picture.
![](https://github.com/cweijan/vscode-database-client/blob/master/images/filter.gif?raw=true)

**Comment by ghost** [comment]
Is this function: [https://dev.mysql.com/doc/workbench/en/wb-develop-sql-editor-table-search.html](https://dev.mysql.com/doc/workbench/en/wb-develop-sql-editor-table-search.html).

You write some content and it is searched in all rows, in all fields in all tables in specific database.

I don't mean search by table name, but table data content. =D

**Comment by cweijan** [comment]
Is mean search data from all table or database?

**Comment by ghost** [comment]
Yes, it is. Sorry about my bad English.

**Comment by ghost** [comment]
pd: search from all database.

**Comment by cweijan** [comment]
I think this function is not practical, so I do not plan to implement it .
