### ISSUE TITLE
Support code-server

### ISSUE THREAD

**Issue by Weijee** [cweijan/vscode-database-client#224]
- OS Info:

**Comment by cweijan** [comment]
1. download extension vsix: `wget https://github.com/cweijan/vscode-database-client/releases/download/3.8.9/vscode-mysql-client2-3.8.9.vsix`
2. then install from vsix, choose vsix path.
![image](https://user-images.githubusercontent.com/27798227/122343347-2f359d00-cf78-11eb-98ce-dd1f939bedf7.png)

**Comment by Weijee** [comment]
I got an error message as below. My vscode-server version is too low?
![image](https://user-images.githubusercontent.com/13539500/122343922-d0245800-cf78-11eb-9ef7-299b510ca7d3.png)

**Comment by cweijan** [comment]
You need upgrade you code-server.
