### ISSUE TITLE
[BUG] [SQLite] The argument 'file' cannot be empty. Received ''

### ISSUE THREAD

**Issue by MurzNN** [cweijan/vscode-database-client#225]
When I trying to open the SQLite database from file - I successfully choose the database file in settings at field "SQLite File Path", but on connect I recieve the error:
```
The argument 'file' cannot be empty. Received ''
```
Here is screenshot:
![image](https://user-images.githubusercontent.com/336662/122376462-d90f2c80-cf6c-11eb-896e-5307b0cfdda8.png)

**Comment by cweijan** [comment]
What are the extension versions and operating systems you use.

**Comment by MurzNN** [comment]
I use connection using VS Code Remote Development, on both sides are Linux (Ubuntu), version is cweijan.vscode-database-client2 v3.8.9

**Comment by cweijan** [comment]
I use the same configuration as you, it works. Consider remove connection name, i think `SQLite File Path` not configured well.
![image](https://user-images.githubusercontent.com/27798227/122503505-24881000-d02b-11eb-8b78-352268ed5e74.png)

**Comment by cweijan** [comment]
Maybe you are not install sqlite, run follow command `sudo apt-get install sqlite`.

**Comment by MurzNN** [comment]
Oh, yes, I forgot to install sqlite on that remote server, thanks! Sorry for noise :confused:
