### ISSUE TITLE
REFERENCES关键字

### ISSUE THREAD

**Issue by Bit0r** [cweijan/vscode-database-client#23]
`REFERENCES`和`CHECK`关键字虽然已经能够高亮，但是还是不能补全，希望作者能够添加？

**Comment by Bit0r** [comment]
还有`CURRENT_TIMESTAMP`和`ON`关键字，例如
```MYSQL
stamp timestamp DEFAULT CURRENT_TIMESTAMP
ON UPDATE CURRENT_TIMESTAMP;
```
以及`WITH`和`AS`关键字
```MYSQL
WITH cte_name (column_list) AS (
    query
) 
SELECT * FROM cte_name;
```

**Comment by cweijan** [comment]
REFERENCES和CHECK我只在create语句内才提示, 主要是考虑到因为这两个关键字不是很常用, 不过貌似加上也不会有影响, as就不加了

**Comment by cweijan** [comment]
下版本加REFERENCES和CURRENT_TIMESTAMP
