### ISSUE TITLE
[BUG][P2] Connetion Target在保存之后无法修改

### ISSUE THREAD

**Issue by chenpey** [cweijan/vscode-database-client#230]
- OS INFO :
&升级到3.9之后 原来的连接串丢失了

**Comment by cweijan** [comment]
可能你是用ssh remote的, 3.9版本把remote的配置单独保存了, Connetion Target确实有问题, 我的失误.

**Comment by chenpey** [comment]
> 你是用ssh远程吗.

是的，平时代码啥的都放在devbox上

**Comment by cweijan** [comment]
你不多的话就重新添加下链接, 不然只能回退了.

**Comment by chenpey** [comment]
> 你不多的话就重新添加下链接, 不然只能回退了.

重新添加了，已经能正常使用了，感谢大佬！

能不能再提一个建议，查询窗口给一个 默认向下拆分的选项，这样看起来就方便多了，不然要切换tab，比较麻烦

**Comment by cweijan** [comment]
你查询的时候不会自动拆分吗, vscode没有提供向下拆分的功能, 只能左右拆分.
![image](https://user-images.githubusercontent.com/27798227/122866437-83ff5c00-d35a-11eb-8d49-8a875cbab078.png)

**Comment by chenpey** [comment]
> 你查询的时候不会自动拆分吗, vscode没有提供向下拆分的功能, 只能左右拆分.
> ![image](https://user-images.githubusercontent.com/27798227/122866437-83ff5c00-d35a-11eb-8d49-8a875cbab078.png)

是自动向右拆了，但是目录树一栏，sql编辑器一栏，查询结果一栏，三栏太挤了
有向下拆分的哈
![](https://files.catbox.moe/jkcuxp.png)

**Comment by chenpey** [comment]
希望的展现形式是这样的：
![](https://files.catbox.moe/31z6kp.png)

**Comment by cweijan** [comment]
那就没办法了, vscode没有提供这个api.

**Comment by chenpey** [comment]
> 那就没办法了, vscode没有提供这个api.

可以看一下 https://marketplace.visualstudio.com/items?itemName=mtxr.sqltools
这个的查询结果是向下拆分的

**Comment by cweijan** [comment]
试了下, 并没有, 以前的版本估计可以, 但他那会是将数据渲染在控制台的.
![image](https://user-images.githubusercontent.com/27798227/122873417-50293400-d364-11eb-92f5-1a06daecc1ad.png)

**Comment by chenpey** [comment]
> 试了下, 并没有, 以前的版本估计可以, 但他那会是将数据渲染在控制台的.
> ![image](https://user-images.githubusercontent.com/27798227/122873417-50293400-d364-11eb-92f5-1a06daecc1ad.png)

So  Sad.

**Comment by chenpey** [comment]
> 试了下, 并没有, 以前的版本估计可以, 但他那会是将数据渲染在控制台的.
> ![image](https://user-images.githubusercontent.com/27798227/122873417-50293400-d364-11eb-92f5-1a06daecc1ad.png)

那执行sql的快捷键 有没有可能提供设置，MBP带bar的按F9 很不方便，Cmd+Enter的话就方便多了

**Comment by cweijan** [comment]
vscode的快捷键都是可以自定义的, ctrl+enter我也想改成这样,  之前忘记改了, 下版本默认加上.
```json
    {
        "key": "ctrl+enter",
        "command": "mysql.runQuery",
        "when": "editorTextFocus"
    },

```

**Comment by chenpey** [comment]
> vscode的快捷键都是可以自定义的, ctrl+enter我也想改成这样, 之前忘记改了, 下版本默认加上.
> 
> ```json
>     {
>         "key": "ctrl+enter",
>         "command": "mysql.runQuery",
>         "when": "editorTextFocus"
>     },
> ```

嗯 我自己改了 谢谢
