### ISSUE TITLE
[BUG] can't show table named 'group'

### ISSUE THREAD

**Issue by yegetables** [cweijan/vscode-database-client#231]
- OS INFO :
(arch)Linux DESKTOP-S5OC1MI-wsl 5.10.16.3-microsoft-standard-WSL2   x86_64 GNU/Linux

I can't show one table named 'group' , other is OK !

![image](https://user-images.githubusercontent.com/37119488/123440869-d617da00-d605-11eb-89e9-34c4531692c6.png)

only other name such as 'groups' can be show for me 

![image](https://user-images.githubusercontent.com/37119488/123441085-0c555980-d606-11eb-9551-0e30392c4743.png)

but when I use shell, all things are OK
Is it BUG?

**Comment by cweijan** [comment]
Thanks for the feedback, I will fix the bug in the next version, and I suggest you don't use keywords as table names.

**Comment by cweijan** [comment]
Fix at version 3.9.3.

**Comment by debugglife** [comment]
@cweijan a similar problem arises when exporting data from table named Order
![image](https://user-images.githubusercontent.com/86830815/130333315-c8ae9b5e-57ea-4689-b276-4243f696b5df.png)
