### ISSUE TITLE
[BUG] Can't load local data

### ISSUE THREAD

**Issue by FenGuo1990** [cweijan/vscode-database-client#232]
- OS INFO :
When I use MySQL to LOAD DATA LOCAL INFILE,There has always been a problem:
> "but as of v2.0 you must provide streamFactory option returning ReadStream."

**Comment by cweijan** [comment]
Although I have fixed this problem recently, your comment made me feel angry because you gave him an unfair score for a feature that is extremely infrequently used. 
![image](https://user-images.githubusercontent.com/27798227/123747052-fb963380-d8e4-11eb-9359-e58ebfdae509.png)

**Comment by cweijan** [comment]
你这种伸手党太恶心了, 赶紧滚, 别用我的插件了.

**Comment by FenGuo1990** [comment]
> 你这种伸手党太恶心了, 赶紧滚, 别用我的插件了.
最高分 5颗星，我给4颗星就要滚了吗？？？4颗星就恶心到你了？？？我只给你这一个插件评论了而已，其它 我都没有评论，在我心中4颗星就是很优秀了。在你心里 四颗星就是恶心，滚？？？

**Comment by FenGuo1990** [comment]
尽管你说话很不礼貌，但是您的插件还想我用过的MYSQL里面最好用的，界面也特别漂亮。经过我测试问题确实得到了解决，感谢您解决了我提出的问题。

**Comment by cweijan** [comment]
因为一个特别小众的功能你给了差评, 你觉得这合理吗??

**Comment by cweijan** [comment]
你之前用的时候没见你打好评, 一发现bug你就立刻打了差评, 这是一个免费软件, 你这种行为对我十分不尊重.

**Comment by FenGuo1990** [comment]
你认为 4星属于差评 就属于差评吧。 豆瓣8分以上的电影 都是神一样的存在，到你这里就成差评了。

**Comment by cweijan** [comment]
@FenGuo1990 伸手党还是别用了, 不要脸.

**Comment by FenGuo1990** [comment]
你会造电脑吗？ 你会写操作系统吗？ 你会写浏览器吗？ 你会写vscode吗？ 整天一个伸手党 一个伸手党的。支付宝微信 也是你自己写的？还伸手党 你是不是伸手党？天天看不上这个 看不上那个的，也不知道优越感从哪来的，每天吃的饭  是你自己亲自种的收割的？是你自己亲手做的？ 能写出这么好的插件给别人共享，却有这种 低劣的思想，真是想不懂。到底是受到了多大的伤害，对别人有这么大的敌意。

**Comment by cweijan** [comment]
@FenGuo1990 你是真的臭不要脸, 怎么会有你这种人

**Comment by cweijan** [comment]
你竟然知道这个插件好用, 那你这个评价又是什么意思?

**Comment by cweijan** [comment]
为什么因为一个不常见的bug给了一个这样评价, 你问问你自己良心.

**Comment by cweijan** [comment]
我花了那么多时间和精力开发这个软件, 一个少见的功能不符合你的需求你就写个评价来恶心我, 你是觉得你很尊重人吗?
