### ISSUE TITLE
[BUG]nothing happened when clicking on 'Add' button

### ISSUE THREAD

**Issue by tian-yan** [cweijan/vscode-database-client#233]
- OS INFO : Mac OS X EI Capitan version 10.11.6
- MS Visual Studio Code version 1.57.1 (Universal)
- Database Client for vscode version 3.9.2

After install the plugin and click on '+' in Database Explorer to add new connection to DB(PostgreSQL), nothing happened.  It is basically not working at all.

**Comment by cweijan** [comment]
What happen when you click connect button.
![image](https://user-images.githubusercontent.com/27798227/123634158-ac9cbf80-d84c-11eb-91dd-74dc48bedd1d.png)
