### ISSUE TITLE
How to add multiple databases in redis explorer with same host

### ISSUE THREAD

**Issue by suraj0805** [cweijan/vscode-database-client#237]
Is there a way to add multiple databases in explorer with same redis host, tried to give databases in comma separated value like '0,1,2,3' but did not work

**Comment by cweijan** [comment]
Create multiple connection with same host and different database.

**Comment by suraj0805** [comment]
Not able to add multiple connections with same host, newly added connection just replaces the existing added connection in redis explorer

**Comment by cweijan** [comment]
@suraj0805 You need upgrade [extension](https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-database-client2).

**Comment by suraj0805** [comment]
@cweijan Still did not work, I am using the version 3.9.4, when I add the second connection with same host and different database with different connection name, it replaces the existing connection
![image](https://user-images.githubusercontent.com/10497623/124473454-fb060d00-ddbc-11eb-9e8c-ebeb2541b171.png)

**Comment by cweijan** [comment]
When you connect success, you need close panel then reopen.
