### ISSUE TITLE
Whether it can support query Clickhouse database？

### ISSUE THREAD

**Issue by WnagoiYy** [cweijan/vscode-database-client#241]
- OS Info:
官网：https://clickhouse.tech/docs/en/
Node库：https://github.com/TimonKK/clickhouse

**Comment by cweijan** [comment]
不考虑小众数据库.

**Comment by mbtolou** [comment]
can you add driver of this database ?

**Comment by mbtolou** [comment]
add clickhouse database.
please review my code.

https://github.com/cweijan/vscode-database-client/pull/418
