### ISSUE TITLE
[BUG] Elasticsearch ssh tunnel not working

### ISSUE THREAD

**Issue by arash-bizcover** [cweijan/vscode-database-client#243]
Trying to connect to elasticsearch through an ssh tunnel, but get this error:

``` log
Ssh tunnel occur error : o: dstPort not set
```

![image](https://user-images.githubusercontent.com/62287461/124563102-16d3e680-de83-11eb-94c8-0fab96b24b73.png)

> My vscode host info:
> 
> ``` yaml
> Version: 1.57.1
> Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
> Date: 2021-06-17T13:26:56.255Z
> Electron: 12.0.7
> Chrome: 89.0.4389.128
> Node.js: 14.16.0
> V8: 8.9.255.25-electron.0
> OS: Linux x64 5.4.0-77-generic

```

**Comment by cweijan** [comment]
Fix at version 3.9.5.
