### ISSUE TITLE
[BUG] SSH tunnel doesn't work!

### ISSUE THREAD

**Issue by intenser** [cweijan/vscode-database-client#244]
- OS INFO :
macOS Big Sur (11.4)
OpenSSH_8.1p1, LibreSSL 2.7.3
Visual Studio Code (1.57.1, arm64)

Trying to connect using SSH tunnel (with private key) but have no success! I've got the message:

"Ssh tunel occur error : Error: All configured authentication methods failed"

Tried different PK types, but neither works. Seems like ed25519 keys not supported? But I can't get it working even for old PEM format (generated with "ssh-keygen -m PEM -t rsa -b 2048").

I can perfectly connect the remote server using terminal.

Could it be an issue related to Apple Silicon (I use MacBook Air M1)?

Maybe I can somehow I enable verbose logging?

**Comment by cweijan** [comment]
I using  PK for `ssh-keygen -m PEM -t rsa -b 2048`, it work normally, I think you need to provide a pair of rsa key.

**Comment by intenser** [comment]
OK, I tried to use another our server and it works. Although it's weird. As connecting via:

ssh user@1.1.1.1 -p 22222 -i /Users/vk/.ssh/id_rsa

... works. But when using the same values in the extension - "All configured authentication methods failed" is shown.

**Comment by cweijan** [comment]
Using ssh command seem it's a good solution, I try using it in next version.

**Comment by intenser** [comment]
Hi there,

The issue was resolved by applying the legacy crypto policies on the server:
`sudo  update-crypto-policies --set LEGACY`

This means that the SSH library used in the extension doesn't support the DEFAULT policy level which is used in the recent Fedora/RedHat releases:

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/security_hardening/using-the-system-wide-cryptographic-policies_security-hardening

https://fedoraproject.org/wiki/Changes/StrongCryptoSettings2

**Comment by cweijan** [comment]
Thanks your feedback.
I try using ssh command to create tunnel, but after implementing it, I found that it was a stupid behavior.
