### ISSUE TITLE
[BUG] UPDATE queries when updating data from table cell not working for tables with Capitals in PostgreSQL

### ISSUE THREAD

**Issue by MurzNN** [cweijan/vscode-database-client#245]
Updating data from table cell (when edit row content of displayed table and press "Enter") for tables  with Capitals in PostgreSQL fails with error:
```
2021-07-07 09:31:10 Execute sql fail : UPDATE Locality SET "name"='Бобруйск' WHERE id=34389232;
2021-07-07 09:31:10 error: relation "locality" does not exist
```
This is similar issue like the #217 
Fix must be like https://github.com/cweijan/vscode-database-client/commit/cf64823b3069534766ad2471306ecb326a92740a but I can't find the right way where to insert it.

**Comment by MurzNN** [comment]
Same problem with deleting rows from table (selected by checkboxes).

**Comment by MurzNN** [comment]
And same when we clicking on column and it displays alter queries, eg:
```
ALTER TABLE Locality ALTER COLUMN name TYPE text;
ALTER TABLE Locality ALTER RENAME COLUMN name TO [newColumnName];

**Comment by cweijan** [comment]
In the latest version it has been automatically detected whether quotation marks are required for all sql.
