### ISSUE TITLE
[BUG] Error occurred while getting table name

### ISSUE THREAD

**Issue by WingchunYip** [cweijan/vscode-database-client#246]
- OS INFO :
Name: MySQL
Id: cweijan.vscode-mysql-client2
Description: Database Client for vscode
Version: 3.9.4
Publisher: cweijan
ERROR INFO: TypeError: Cannot read property 'getChildren' of undefined

![image](https://user-images.githubusercontent.com/38939000/125148512-5e00f680-e165-11eb-8f55-321428abcdd0.png)

**This error only appear while you had activated a database connection. If you didn't activated a connection, it can get some table name among the sql file without TypeError. ** 

![image](https://user-images.githubusercontent.com/38939000/125148583-0020de80-e166-11eb-9071-8a6b5e93cacb.png)

**Comment by brukted** [comment]
the isssue still exists , I don't think the commit actually fixed it.
![Screenshot 2021-08-06 205902](https://user-images.githubusercontent.com/40060643/128552686-9dc9c951-2f5b-471b-bb99-0073faa24fdc.png)

**Comment by cweijan** [comment]
@brukted There are some situations that I didn’t consider, and it will be fixed in a later version.

**Comment by brukted** [comment]
@cweijan Thanks for the quick response. If it helps It appears that It is fine if i changed the active database using the change database command instead of from the query.
