### ISSUE TITLE
USING关键字

### ISSUE THREAD

**Issue by Bit0r** [cweijan/vscode-database-client#25]
希望支持`USING`关键字，这个关键字在连表时非常有用，在`SELECT`，`UPDATE`，`DELETE`中都经常使用
```MYSQL
SELECT column_list
FROM table_1
JOIN table_2 USING (column_name);
```

**Comment by Bit0r** [comment]
还有`REPLACE`语句的支持，很多时候`REPALCE`比`INSERT`更合适

**Comment by cweijan** [comment]
这些语句也太骚了😂

**Comment by Bit0r** [comment]
这些语句可以很方便操作，比在应用逻辑里面实现方便多了

**Comment by Bit0r** [comment]
像`REPLACE`就比`INSERT`操作用户订单要方便，就可以把添加和修改放在一起，而且效率很高

**Comment by cweijan** [comment]
新版本新增大量常见关键字, https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-mysql-client2

**Comment by Bit0r** [comment]
流批
