### ISSUE TITLE
MySQL SSL CA Certificate Option

### ISSUE THREAD

**Issue by ajf1234** [cweijan/vscode-database-client#251]
My DBA is using AWS RDS MySQL and requiring the CA Certificate and nothing else. No verification or anything. When I initially installed the extension it was able to connect, but now the connection times out. Can you expose a CA Certificate setting so we can connect?

![image](https://user-images.githubusercontent.com/43730582/126036180-7515c51c-6154-42e1-a667-41cc9a7e9e3f.png)

Thank you

**Comment by cweijan** [comment]
Version 3.9.8 add ca option, but I not test, you can try it.
![image](https://user-images.githubusercontent.com/27798227/127128951-364b34cf-4242-4651-a8d7-2f66bf959797.png)

**Comment by ajf1234** [comment]
I'm able to connect now! Thank you!
