### ISSUE TITLE
Add Connection to MongoDB using connection url with SRV support

### ISSUE THREAD

**Issue by drtobbyas** [cweijan/vscode-database-client#253]
Can you add support for connecting to MongoDB using connection URL with SRV support

**Comment by drtobbyas** [comment]
I'm picking this up and raising a PR for it implementation soon

**Comment by cweijan** [comment]
I do not plan to maintain mongo, but I am happy to accept PR.

**Comment by cweijan** [comment]
Your code has released to [database-client](https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-database-client2).
