### ISSUE TITLE
[BUG] Connection not saved

### ISSUE THREAD

**Issue by arash-bizcover** [cweijan/vscode-database-client#254]
- Version: 1.58.2
- Commit: c3f126316369cd610563c75b1b1725e0679adfb3
- Date: 2021-07-14T22:30:16.440Z
- Electron: 12.0.13
- Chrome: 89.0.4389.128
- Node.js: 14.16.0
- V8: 8.9.255.25-electron.0
- OS: Linux x64 5.4.0-77-generic

So after trying to add elasticsearch it says connection success, but how can I save it and access this thing?
![image](https://user-images.githubusercontent.com/62287461/126232985-16b41b52-b4dc-420b-a636-3db5b46cb8a1.png)

**Comment by cweijan** [comment]
This plugin will create two panel, you need go to nosql panel.
![image](https://user-images.githubusercontent.com/27798227/126246292-ceb6267e-4da9-4b3e-b0ad-0fd769383f4c.png)

**Comment by arash-bizcover** [comment]
ah damn... Thanks man
Sorry

**Comment by arash-bizcover** [comment]
@cweijan But then it is very weird that I can create a new nosql db from that "+" button in the Relational DB panel. 🤷 

Feel free to close this issue if you want to keep this behaviour though.

**Comment by arash-bizcover** [comment]
Instead of 2 separate panels, I'd like to suggest bringing both of them to the same panel and add a parent category to the list shown.

**Comment by cweijan** [comment]
You can drag nosql into database panel, the separation is because most of the time you need to view the database and redis or es at the same time 
![image](https://user-images.githubusercontent.com/27798227/126252841-04ff6439-b01a-4a72-b8fb-056903f54075.png)

**Comment by arash-bizcover** [comment]
Hehe, What I was proposing, is exactly implemented already, Thanks @cweijan
