### ISSUE TITLE
[BUG] Redis "Connection time out!" but server status and console works

### ISSUE THREAD

**Issue by AKoseki** [cweijan/vscode-database-client#255]
- OS INFO : Windows 10, latest fresh install/download vs code (1.58.2), latest "mysql" database client

As soon as I add the connection, I keep getting connection timeout, but it shows "connection successful!" when I click to connect; I can also check server status and use the console, but the treeview doesn't works, showing "Connection time out!"

![jDAI1iFoce](https://user-images.githubusercontent.com/7014461/126362205-43545a1a-6ce2-460d-9175-0fa9fe339249.gif)

**Comment by cweijan** [comment]
What is your configuration, my redis connection did not encounter this situation.

**Comment by AKoseki** [comment]
Just a basic localhost connection. The server is remote but I tried both methods, either connecting locally through a ssh tunnel or using the tunnel from the module. I'm starting to believe that it's due to we having 200k keys on it, and some few of the keys are almost a megabyte in size. Is there any place I can check logs? I'm kind of new to vsc.

**Comment by cweijan** [comment]
It seems that the extension you are using is not the latest version, try to upgrade the extension.

**Comment by cweijan** [comment]
Sorry I ignored the 200,000 keys you mentioned, try to modify the connection timeout of the redis connetion.
![image](https://user-images.githubusercontent.com/27798227/128110251-d6c1b7c0-9169-4683-90b9-7e8870c39f69.png)
