### ISSUE TITLE
[Feature] Support authentication for elasticsearch connections

### ISSUE THREAD

**Issue by arobert-attraqt** [cweijan/vscode-database-client#258]
Elasticsearch offers tokens based security to connect to secure services. 
From elastic documentation:

> The security features provide two services: the token service and the api key service. You can use these services to exchange the current authentication for a token or key. This token or key can then be used as credentials for authenticating new requests. These services are enabled by default when TLS/SSL is enabled for HTTP.

https://www.elastic.co/guide/en/elasticsearch/reference/current/setting-up-authentication.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/token-authentication-services.html

**Comment by cweijan** [comment]
I think es should not be exposed to the external network, security verification is worthless, so don't plan to support it, only accept pull requests.

**Comment by arobert-attraqt** [comment]
Thank you for taking your time to read my request, elastic does offer an elastic cloud service, so it's exposed to an external network, which is why I thought it would be a nice feature.

**Comment by cweijan** [comment]
Version 3.9.8 has been support auth with token or account.
![image](https://user-images.githubusercontent.com/27798227/127129646-eeda613c-d9eb-452e-8561-49114ae372ac.png)

**Comment by arobert-attraqt** [comment]
Thank you!
