### ISSUE TITLE
[BUG] native ssh expects me to type in passphrase or does not work

### ISSUE THREAD

**Issue by akomm** [cweijan/vscode-database-client#260]
- OS INFO :
ubuntu lts 18.04

Getting  connect ECONNREFUSED 127.0.0.1:8000 using native ssh (works outside the plugin).

I suspect the plugin expects me to enter my passphrase directly in its settings, which would be very stupid and a no-go, if it did. Why not trigger the ssh agent, which would prompt me the passphrase as needed? Every program that uses ssh does that... Or it is supposed to work this way, then its a bug...

**Comment by cweijan** [comment]
Native ssh is still an experiment.

**Comment by cweijan** [comment]
The intention is to solve the problem that complex private keys cannot use program ssh tunnels.

**Comment by akomm** [comment]
can as well create tunnel manually but its really inconvenient

**Comment by cweijan** [comment]
Using the ssh command does not achieve the effect, I will remove it in the next version.
