### ISSUE TITLE
查询窗口能否与查询语句在同一个tab

### ISSUE THREAD

**Issue by YannLex** [cweijan/vscode-database-client#261]
- OS Info: MacOS 11.2.1
你好，首先很感谢提供这样的工具，非常棒。
这里提个小的建议，希望查询结果窗口与查询语句在同一个tab，避免切换到其他tab时，查询结果窗口仍然占半边空间。
（有个thunder client的插件是这样的，感觉切换到其他tab时体验更好点）
![image](https://user-images.githubusercontent.com/3049310/127422718-3c8143ea-3a1f-48ce-b45b-a647e2977f3a.png)

**Comment by cweijan** [comment]
其他插件能在同一个tab是因为他把数据打印到控制台了, 那UI就很丑了, 所以是没办法的.

**Comment by YannLex** [comment]
> 其他插件能在同一个tab是因为他把数据打印到控制台了, 那UI就很丑了, 所以是没办法的.

在同一个tab也可以格式化吧
![image](https://user-images.githubusercontent.com/3049310/127597090-67c0f019-286f-421a-9a85-b65252defca5.png)

**Comment by cweijan** [comment]
你发的这个左侧不是VSCode的编辑器啊, 这是同一个页面, 你把VSCode搞清楚再来提问题.
