### ISSUE TITLE
[Feature] Read only mode

### ISSUE THREAD

**Issue by gerukin** [cweijan/vscode-database-client#262]
Really wonderful extension, thank you very much for your hard work 🙇‍♂️.

It would be very helpful to have a `read only` toggle in the connection settings (or perhaps elsewhere) so that all SQL statements and UI actions making any changes to the database are stopped with a prompt to continue..
> This connection is marked as READ only. Type 'proceed" to proceed.

This is especially useful in production environments where we want to avoid accidental modifications in cases where we cannot use a read only user for any reason, or when infrequent write operations are needed after some confirmation.

**Comment by cweijan** [comment]
This is not a necessary feature, I do not plan to implement this function, only to receive PR.

**Comment by gerukin** [comment]
> This is not a necessary feature, I do not plan to implement this function

Understood. This is a bit strong though, and perhaps you didn't mean it that way.

Regardless, just FYI, it is quite useful in IDEs like [Jetbrain's](https://www.jetbrains.com/datagrip/features/executing.html):
<img width="976" alt="read-only-phpstorm" src="https://user-images.githubusercontent.com/36127103/128426882-2f65be44-26ba-4630-9bfd-71f17afc6cb9.png">

**Comment by cweijan** [comment]
hi, I will implement this feature in the future, there is indeed a read-only necessity for the production server database.

Unlike data-grip, the jdbc used by data-grip is inherently read-only, and this program must be manually identified through program logic through node.js

**Comment by cweijan** [comment]
I'm sorry that I didn't think enough before and spoke too decisively.

**Comment by pmcl77** [comment]
Seems my #475 is sort of a duplicate. I like the readonly mode even better, when running a statement to be prompted if it should be executed really....

**Comment by cweijan** [comment]
Read-only mode is fully implemented in version 5.0.2.
