### ISSUE TITLE
i c'ant find databases after connection with redis , mongodb

### ISSUE THREAD

**Issue by ous24** [cweijan/vscode-database-client#263]
- OS INFO :
![image](https://user-images.githubusercontent.com/63429256/127762422-3ade9408-d8e0-48ed-9a93-d48fb08c172f.png)
i use vscode with ubuntu system , i tried this extension with mysql and it works fine , however for mongodb and redis after connecting sucessufully i c'ant find any shown databases

**Comment by cweijan** [comment]
In this panel.
![image](https://user-images.githubusercontent.com/27798227/127791330-29f275f7-2e4a-4fe8-bf12-4a4136f3bf32.png)
