### ISSUE TITLE
multiple panel support

### ISSUE THREAD

**Issue by michaellifly** [cweijan/vscode-database-client#265]
- OS Info:
 
Could that support multiple panel since sometimes developer want to see result from multiple query side by side?

currently I did not see how to create keep the old panel unless query the new table.(Open in new Panel)

**Comment by cweijan** [comment]
Support at version 4.0.0.
Try to click below button.
![image](https://user-images.githubusercontent.com/27798227/128601733-6c8f8f69-377c-472c-8cbb-a3b56fab1629.png)
