### ISSUE TITLE
[BUG] Issues with SQLite update statements

### ISSUE THREAD

**Issue by JammingBen** [cweijan/vscode-database-client#266]
I'm having a few issues when editing data in a SQLite table directly. When I click on a field, enter a new value, then click enter to save, I get the following message:

```
Execute sql fail : UPDATE users SET displayname=test WHERE uid=test;
Error: Error: near line 3: no such column: test
```

The statement itself seems wrong to me, it should be: `UPDATE users SET displayname = 'test' WHERE uid = 'test';`

Aside from that, what would be the behavior if `uid` is the primary key, but not unique? I've noticed in another scenario that the query is same, which could cause updates across multiple database entries. I just want to update the selected entry though!

And finally: when updating the table via this statement manually, the view does not refresh. And the refresh-button in the list in my explorer has no effect. Then I have to re-open the current table, which is not so nice.

I'm not sure if or how these observations are related to SQLite, but at first glance I didn't experience any issues with Postgres.

Using Mac OS 11.5 (M1 Mac), VsCode 1.58.2, Database Client 3.9.8

**Comment by cweijan** [comment]
Fix at version 4.0.0.
