### ISSUE TITLE
[BUG] "Install SQLite" does not work

### ISSUE THREAD

**Issue by MikeChongCan** [cweijan/vscode-database-client#268]
- OS INFO : `macOS 11.5.1 (20G80)`
- Plugin version: `4.0.0`

https://user-images.githubusercontent.com/2396817/128655626-994222ca-3d27-40db-adf2-6187f0ec442f.mov

**Comment by cweijan** [comment]
Thanks feedback, fix at version 4.0.2, and you need to have brew installed.

**Comment by MikeChongCan** [comment]
@cweijan Thanks for the quick turnaround!

I can verify the fix.

In the future, could we pre-bundle SQLite dependency into the plugin or host it via GitHub packages?
Not every macOS users have homebrew preinstalled.
