### ISSUE TITLE
Change Active Database option not working

### ISSUE THREAD

**Issue by franklinkf** [cweijan/vscode-database-client#269]
Thanks for a great extension.  I am using this extension for managing MySQL database.

The option - Change active database is not working now.  Earlier,  list of all databases used to come.  Now, no response is coming.

Request you to please have a look on this issue

Thank you

Any plans for Oracle integration?

**Comment by cweijan** [comment]
Thanks feedback, fix at version 4.0.3, Oracle does not have an open protocol, so there is no plan to support it.

**Comment by franklinkf** [comment]
Thank you Sir
