### ISSUE TITLE
Using vscode theme color scheme

### ISSUE THREAD

**Issue by sheey11** [cweijan/vscode-database-client#270]
- OS Info: macos
- VSCode: code-server
- Theme: Ayu Dark

![截屏2021-08-10 下午5 23 17](https://user-images.githubusercontent.com/13375959/128842522-fff71225-1652-4188-ac9c-210549e976ec.png)
![截屏2021-08-10 下午5 23 28](https://user-images.githubusercontent.com/13375959/128842545-521691f3-80b8-48b2-98cb-08d5d5f213f6.png)

Color is a little bit weirdo.

**Comment by cweijan** [comment]
You mean border?

**Comment by sheey11** [comment]
both the border and the text color, blue seems not fit here.

btw, to suit so many theme, you should retrive and apply theme-based color scheme when the panel opened.

**Comment by cweijan** [comment]
Update at version 4.1.0.
