### ISSUE TITLE
[BUG]TypeError: Cannot read property 'getChildren' of undefined

### ISSUE THREAD

**Issue by wang19742008** [cweijan/vscode-database-client#272]
sql表名联想可能失败，提示错误信息：
TypeError: Cannot read property 'getChildren' of undefined

**Comment by cweijan** [comment]
Fix at version 4.0.5.

**Comment by wang19742008** [comment]
My version is v4.1.0 and still have this problem

**Comment by afurey0** [comment]
I also have this problem on version 4.1.0.
