### ISSUE TITLE
[BUG] Cannot open settings when installed as a SSH remote extension 

### ISSUE THREAD

**Issue by mgh1** [cweijan/vscode-database-client#275]
I have installed this as an extension via SSH remote (Ubuntu 18) and accessing on a different machine (Windows 10). It works well (thanks for your hard work!), but I cannot access the settings of this extension. I'm not sure if it is because I installed it as a remote extension or because settings is disabled somehow. 

I noticed this extension has settings based on the "Feature Contributions" tab in the VS Code Marketplace. I'd like to manage some settings like "database-client.defaultSelectLimit" but I cannot. All my other extensions installed on my remote server allow me access to their settings except for this extension.

**Comment by cweijan** [comment]
I didn't understand what is ` I cannot access the settings of this extension`, setting is manager by vscode.
