### ISSUE TITLE
Add proper support for scores (for Redis ZSETs)

### ISSUE THREAD

**Issue by hankovich** [cweijan/vscode-database-client#276]
There's no way to see scores in sorted sets in Redis at the moment. 

How ZSETs are visualized now:
![](https://user-images.githubusercontent.com/22914850/129563726-80bd864d-1de5-4868-8dd7-8fb9714d6984.png)
---

How ZSETs are visualized in Redis Commander:
![](https://user-images.githubusercontent.com/22914850/129563445-49527cfd-7824-4372-965b-743e2ea192d0.png)
---
Version of extension beeing used: v4.1.0

OS version: Windows 10 Pro 19042.1110

**Comment by cweijan** [comment]
Support on version 4.1.1.

**Comment by hankovich** [comment]
Nice stuff, thanks!
I've opened a small PR(https://github.com/cweijan/vscode-database-client/pull/282) which fixes case for the `score` label to be in sync with other columns (`ID`, `Value` and `Operations`).
