### ISSUE TITLE
mongodb无法正常添加[BUG]

### ISSUE THREAD

**Issue by ermaozi** [cweijan/vscode-database-client#277]
- OS INFO :
版本: 1.59.0 (user setup)
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.18363

- BUG
填写正确的mongodb信息后点击Connect, 提示 connect success! 左侧数据库列表没有反应.

**Comment by cweijan** [comment]
mongodb的连接在这个不同的容器.
![image](https://user-images.githubusercontent.com/27798227/129723111-307c73e0-f104-44b9-b91d-d89a76e180e5.png)
