### ISSUE TITLE
[BUG] 格式化界定符 DELIMITER 导致错误

### ISSUE THREAD

**Issue by ganglee** [cweijan/vscode-database-client#284]
- OS INFO : macOS Big Sur, 
- vscode 版本: 1.59.1
提交: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
日期: 2021-08-19T11:53:52.479Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 20.5.0

你好，安装插件以后，我开启了自动保存格式化功能，发现无法正确的格式化 界定符 DELIMITER，比如：
`DELIMITER ;` 会被格式化为：`DELIMITER;`
`DELIMITER //`  会被格式化为：`DELIMITER / / create` 把下一行的数据放上来了。

因为导致无法使用，目前只能无奈先禁用掉，希望能抽空看下。

**Comment by cweijan** [comment]
格式化程序不再维护, 如不满意则禁用它.
