### ISSUE TITLE
[BUG] MongoDB Sorting doesn't work

### ISSUE THREAD

**Issue by jordandelozier** [cweijan/vscode-database-client#286]
- Database: MongoDB

Attempting to sort by a field in Mongo fails. The query generated uses SQL instead of MQL. 

### Steps to recreate
Load any MongoDB and click on a sort arrow (desc or asc). 

### Expected result
A sorted list.

### Actual result
```
EXECUTE FAIL:

  db('name').collection('collection').find({}). ORDER BY _id desc limit(100).toArray() ;

Message :

  Unexpected identifier
```

### Fix
Replace the SQL with MQL: `db('name').collection('collection').find({}).sort("_id": -1).limit(1000).toArray();`

**Comment by cweijan** [comment]
Fix at version 4.1.5.
