### ISSUE TITLE
extensive VScode cache at %appdata%\Code\Service Worker\

### ISSUE THREAD

**Issue by thuan00** [cweijan/vscode-database-client#287]
First, I d like to thank u for building such an useful extension, its great.

There's just this problem that the extension 's been doing **a lot of cache**.

I 've been inspecting the service worker cache and found that there is a cache of **at least 6mb** generated everytime I run a select query.
This has built up a total of 3 GB in two weeks.

I can delete this cache manually 
but is there anything you can do to cut down this cache ?

OS Info:
- windows 10
- vscode 1.60.0

**Comment by cweijan** [comment]
I found that every time I open a webview, it will be cached. This is controlled by vscode. If you know how to solve it, you can let me know.

**Comment by thuan00** [comment]
I think I found the config that led to the cache : `retainContextWhenHidden: true`

https://github.com/cweijan/vscode-database-client/blob/0365f8642ef59719f08dbcf33ad78cc57e6a8bb4/src/common/viewManager.ts#L96

Below is the VScode API reference of `retainContextWhenHidden` that said it has a high memory overhead and should only be used if your panel's context cannot be quickly saved and restored.
https://code.visualstudio.com/api/references/vscode-api#WebviewPanelOptions

I wonder if the context of hidden WebviewPanel is really necessary for all views ?
Maybe you can try disable this option for certain types of view like the result view ?

**Comment by cweijan** [comment]
I have tried this option, and he will still create a cache.

**Comment by thuan00** [comment]
Okay thanks, guess I ll be deleting the cache occassionally.

**Comment by cweijan** [comment]
I think this is a serious problem. I have created an [issue](https://github.com/microsoft/vscode/issues/132376) to vscode. I look forward to getting feedback. If it can’t be solved, I will consider using cdn in the future.

**Comment by cweijan** [comment]
I have always wondered why vscode takes up so much disk, you helped me find the problem😄.

**Comment by cweijan** [comment]
Try version 4.1.3, Now extension should only generate a 4kb cache.

**Comment by thuan00** [comment]
Thats great, thanks, Im actually using the general extension for Postgres https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-database-client2
Looking forward to the update :D

**Comment by cweijan** [comment]
Now i have updated this too .

**Comment by YoussofH** [comment]
I tried assigning `retainContextWhenHidden: false` but the same old webview kept showing up no matter how many times i build/close/relaunch VS code and the extension I am developing.

It insists on showing an old version of the html which I have already deleted a while ago.

Have anyone found any feasible solution for mac users?
