### ISSUE TITLE
[BUG]redis的hash类型，值太多就会卡死

### ISSUE THREAD

**Issue by 89333367** [cweijan/vscode-database-client#288]
- OS INFO :
我连接了redis，cluster模式。在访问一个key时，每次都会卡死。
这个key类型是hash类型，里面有50多万的值。

**Comment by cweijan** [comment]
感觉这么多值卡是正常的吧, 你用其他客户端或者redis-cli表现如何呢.

**Comment by 89333367** [comment]
使用redis desktop manager是没问题的。可以正常显示。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cweijan/vscode-database-client"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月5日(星期天) 凌晨0:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cweijan/vscode-database-client] [BUG]redis的hash类型，值太多就会卡死 (#288)





 
感觉这么多值卡是正常的吧, 你用其他客户端或者redis-cli表现如何呢.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 89333367** [comment]
估计RDM是使用scan的方式
```
HSCAN
HSCAN key cursor [MATCH pattern] [COUNT count]
```
一点一点获取的，这样就不会卡死或者不显示了

**Comment by cweijan** [comment]
4.1.5版本做了分页处理, 现在不会导致卡死了, 不过为了方便, 还是在点击的时候加载全部数据, 所以加载会比较慢.

**Comment by 89333367** [comment]
太好了，期待中。目前vscode中还没有提示升级。
还有什么时候能支持一下H2数据库呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cweijan/vscode-database-client"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月12日(星期天) 晚上9:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cweijan/vscode-database-client] [BUG]redis的hash类型，值太多就会卡死 (#288)





 
4.1.5版本做了分页处理, 现在不会导致卡死了, 不过为了方便, 还是在点击的时候加载全部数据, 所以加载会比较慢.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cweijan** [comment]
H2一般是测试用的, 应用场景不广泛, 我没计划支持呢.
