### ISSUE TITLE
[BUG] database content not more showing after  update

### ISSUE THREAD

**Issue by jnkconsult** [cweijan/vscode-database-client#289]
- OS INFO :
CPUs | Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 x 2900)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: disabled_off opengl: enabled_on rasterization: disabled_software skia_renderer: enabled_on video_decode: disabled_software vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) | 1, 1, 1
Memory (System) | 31.27GB (24.15GB free)
Process Argv | --no-sandbox --force-user-env --unity-launch --crash-reporter-id 3eacb05c-200a-480d-aa3d-b03c06fb160d
Screen Reader | no
VM | 0%

Remote | Container ecom_php (ecom-php)
-- | --
OS | Linux x64 5.12.19-1-MANJARO
CPUs | Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 x 2900)
Memory (System) | 31.27GB (24.25GB free)
VM | 0%

after the update to the 4.1.3 version, when I want open a table, the panel with the date stay empty.....I can not more showing the content of the table. I have make a downgrade to the 4.1.2 and everthing is back OK.

I don't know if I can give you a logs or something like that to help you

**Comment by kapr1k0rn** [comment]
I am having the same issue, downgrading resolved it

**Comment by cweijan** [comment]
The new version is intended to reduce the cache generated by WebView. You can try to select CDN in the new version settings, If not work, try using file option.
![image](https://user-images.githubusercontent.com/27798227/132279102-de15a054-4bbf-43d3-b616-81f0b99e9137.png)

**Comment by jnkconsult** [comment]
Using CDN is ok. thanks you
