### ISSUE TITLE
Support to execute query from selected text from any file.

### ISSUE THREAD

**Issue by humayunghani** [cweijan/vscode-database-client#29]
I'm already loving your extension bro. Awesome work. I gave you 5 star on Marketplace and stared on github already. **Keep up the good work**.

Just a suggestion only if you got enough time to support this. I found this feature in some other mysql client extension that you can execute a mysql query from any file selected text. The selected text query must end with a semi colon so the parser can pick query easily. And then execute it on the current connected session.
I couldn't find this feature in your extension, if it's already there let me know and I'll be happy to use it.

**Comment by cweijan** [comment]
Thanks for support, this extension have this feature a long time ago.
![image](https://user-images.githubusercontent.com/27798227/82695451-b510e700-9c97-11ea-9748-c0aaf1cae8cd.png)
