### ISSUE TITLE
Instalé MYSQL en mi VSCodium de Debian

### ISSUE THREAD

**Issue by Cgspc** [cweijan/vscode-database-client#290]
Está instalado MySQL v4.1.1 de cweijan y Database Client v4.1.0 cweijan, pero no aparece en el menú  ni en la barra lateral, me pueden ayudar por favor, para no tener que estar saliendo de codium y entrando a phpmyadmin
![VSCodium](https://user-images.githubusercontent.com/34277444/132237518-51f30931-77bd-483e-afde-1f18cee75323.png)

**Comment by cweijan** [comment]
You only need to install one of them.

**Comment by Cgspc** [comment]
Thanks for answering.
I have installed all the ones that appear in the list and none have worked for me, the only one that did not install was PostgreSQL.
Attached image.
![VSCodium](https://user-images.githubusercontent.com/34277444/132342970-18de6f6c-c321-4763-8b60-fb02a76fc940.png)

The only one where I can make a connection was vscode-database v2.2.3 from bajdzis, but I couldn't access the databases either

**Comment by cweijan** [comment]
Try right click in the left pannel.
![image](https://user-images.githubusercontent.com/27798227/132357448-691095fa-0a04-4b55-b5e2-ff919bae4440.png)

**Comment by Cgspc** [comment]
Thank you very much for the help, the problem has already been solved and Mysql V4.1.1 was installed
