### ISSUE TITLE
[BUG] Viewing Table Content Hangs with new empty query window.

### ISSUE THREAD

**Issue by ccfredbaum** [cweijan/vscode-database-client#291]
- OS INFO :
Windows 10 - VS Code. 

Running SSH connected shell to a database. Connection establishes successfully, and I can see tables, look at their schema. I can even drop a table successfully. Refresh buttons work as well. 

Clicking on any table object however just crashes on a new empty query window that does nothing. 

I can use SQL workbench fine into the client, and it connects as normal, so its not the database. 

Has anyone else had this issue ?
![clickbugPNG](https://user-images.githubusercontent.com/76839421/132325936-c7861ab9-49ee-4914-8f89-e08cc56eac25.PNG)

**Comment by cweijan** [comment]
The new version is intended to reduce the cache generated by WebView. You can try to select CDN in the new version settings, If not work, try using file option.
![image](https://user-images.githubusercontent.com/27798227/132279102-de15a054-4bbf-43d3-b616-81f0b99e9137.png)

**Comment by cweijan** [comment]
I've changed the CDN to the default setting, so you just need to upgrade to version 4.1.4.

**Comment by ccfredbaum** [comment]
Thank you so much, I use your code every day, and it makes a huge difference. Thank you for your response as well :)- Very much appreciated it, and the work you do.
