### ISSUE TITLE
[BUG] cannot success elastic search

### ISSUE THREAD

**Issue by PreziosiR** [cweijan/vscode-database-client#292]
- OS INFO : MacOS Big Sur 11.2.3 / VSCode 1.60

Hello, I'm trying to connect to my elastic DB via https, I have a toast "SUCCESS" with the following message "connect success". I'm stuck in this step. I don't have the DB tab. 
![Capture d’écran 2021-09-07 à 12 16 56](https://user-images.githubusercontent.com/20641065/132328438-d7b07d3b-f021-46bf-9d95-d778192cb614.png)

**Comment by cweijan** [comment]
ES connection in nosql pannel.
![image](https://user-images.githubusercontent.com/27798227/132329335-cb5cf1df-bfdb-4af2-bdb3-82f272a2f0c8.png)

**Comment by PreziosiR** [comment]
Thanks but by default vscose don't open the SQL and other panel on the left bar, so I was thinking it was not working. It's necessary to press cmd + man + p and write "other explorer" in order to display this panel.

**Comment by cweijan** [comment]
You can drag nosql into database panel, the separation is because most of the time you need to view the database and redis or es at the same time 
![image](https://user-images.githubusercontent.com/27798227/126252841-04ff6439-b01a-4a72-b8fb-056903f54075.png)
