### ISSUE TITLE
Enhancement: Use Workspace path as default path when exporting sql

### ISSUE THREAD

**Issue by luckcolors** [cweijan/vscode-database-client#293]
Hello.
Thank you for making this exstension, it's working pretty well for my needs.

I only have a small suggestion, coul you change the default path when saving (exporting sql structs or data)? As to by default default to the workspace root folder see [here](https://code.visualstudio.com/docs/editor/variables-reference)?

This i would argue is a better defaults, as when working in a workspace it is most likely that you'll want to save in the repo.
Maybe this could be overwritten with a setting?

Thanks for your time.

**Comment by cweijan** [comment]
Support at version 4.1.5.

**Comment by luckcolors** [comment]
I  have 4.1.6 installed and this is not working. It still defaults to /.
For testing i did Database -> Table-> Export Struct

**Comment by luckcolors** [comment]
@cweijan Can you reopen the issue please? I can't for some reason

**Comment by cweijan** [comment]
I modified is the result page export, not dump, It seems that I misunderstood your issue.

**Comment by luckcolors** [comment]
I see, no worries. :)
I meant it more as a general rule for any vscode file prompt the extension uses.

**Comment by cweijan** [comment]
Support at version 4.1.8.

**Comment by cweijan** [comment]
This feature will cause the file chooser to fail to remember the last selected path, I removed this feature in version 4.2.0.

**Comment by luckcolors** [comment]
Okay.
Thanks anyways. Maybe a better solution can be found.
