### ISSUE TITLE
would be nice to highlight SQL statements within a String literal

### ISSUE THREAD

**Issue by tigerinus** [cweijan/vscode-database-client#294]
There is an extension https://github.com/0x00000001A/es6-string-html that does this, but it's for ES6 JavaScript. There is also its fork for Python language.

Would be nice to include this feature in your extension just for SQL. 

So it would highlight the SQL statement in the literal like:

```java
String select = /*sql*/"SELECT * FROM table;"
```

Other extensions use `/*sql*` inline comment to identify the string literal that contains SQL statement

**Comment by cweijan** [comment]
I referenced this project and found two problems. So I do not intend to embed this function in the extension.
1. Syntax highlighting is achieved through regular expressions, which means that there must be a certain identifier to be highlighted, such as /*sql*/
2. There is no way to autocomplete SQL after highlighting
