### ISSUE TITLE
[BUG][SqlServer] 生成DDL没包含字段注释内容

### ISSUE THREAD

**Issue by WingchunYip** [cweijan/vscode-database-client#295]
- OS INFO :
名称: MySQL
ID: cweijan.vscode-mysql-client2
说明: Database Client for vscode
版本: 4.1.4
发布者: cweijan
VS Marketplace 链接: https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-mysql-client2

老师好，我创建了一个SqlServer的连接，使用"查看表源码"、“导出数据”、“导出表结构”三种操作生成的DDL脚本中都没有包含各字段的注释内容。

表的排序规则可能有点奇怪，为：```Japanese_Bushu_Kakusu_140_CI_AI_UTF8```。

**Comment by cweijan** [comment]
SQLServer没法通过一条SQL拿到注释, 所以不支持注释呢.

**Comment by WingchunYip** [comment]
好吧...感谢回复！
