### ISSUE TITLE
[BUG] can't list shema and connect to mysql db

### ISSUE THREAD

**Issue by Jiadi-Cheng** [cweijan/vscode-database-client#297]
- OS INFO :
since mysql db  upgraded to 8.0.26,  character_set changed to utf8mb4, utf8mb3,  i can't connect to mysql db

![Uploading QQ图片20210911094651.png…]()
![Uploading QQ图片20210911094722.png…]()

**Comment by Jiadi-Cheng** [comment]
![QQ图片20210911094651](https://user-images.githubusercontent.com/45381244/132932376-aa08992a-1506-4fc6-b779-dcbd60b0a57f.png)
![QQ图片20210911094722](https://user-images.githubusercontent.com/45381244/132932381-7258b21b-ae31-4916-b1fd-e8f86b8603f7.png)

**Comment by cweijan** [comment]
I don't think this is related to character_set . I suggest you delete the MySQL connection and reconnect.

**Comment by Jiadi-Cheng** [comment]
it works now, thank you.
