### ISSUE TITLE
[BUG]PostgreSQL运行任意执行计划卡死

### ISSUE THREAD

**Issue by AtlantisWing** [cweijan/vscode-database-client#298]
- OS INFO :Windows 10 + WSL2 Ubuntu + PostgreSQL 12
执行任何EXPLAIN 语句都会出现等待画面并无限循环

**Comment by cweijan** [comment]
Postgres 执行explain返回的不是和mysql一样的数据, 所以解析错误了, 我已经不会让他继续转圈了, 但无法显示他的分析结果.

**Comment by AtlantisWing** [comment]
今后能把这个纳入日程不～分析领域pgsql会越来越普及，执行计划需要经常看

**Comment by cweijan** [comment]
插件是使用node-pg这个库连接的, 然后这个库执行explain后没有返回explain的结果, 所以没办法呢

**Comment by AtlantisWing** [comment]
难受……不过还是非常感谢耐心作答～

**Comment by cweijan** [comment]
发现是我搞错了, 原来是有返回的.

**Comment by cweijan** [comment]
4.1.6版本修复了.
