### ISSUE TITLE
NoSQL DATE 

### ISSUE THREAD

**Issue by albertomarun** [cweijan/vscode-database-client#299]
- OS INFO : WINDOWS 10 + MONGODB 5

When viewing a collection and the field is date and the display screen appears string  and if you modify a date directly from the edit box and press enter transforms it into a string.

![2021-09-11_163721](https://user-images.githubusercontent.com/11788637/132961073-7610556b-97b0-41dd-ae81-a41e7856f1ed.jpg)

... in compass the field is date

![2](https://user-images.githubusercontent.com/11788637/132961144-f63f7388-1e62-4985-8977-0324030ba78e.jpg)

**Comment by cweijan** [comment]
This extension has very low support for mongo, so it is only recommended for browsing data .

**Comment by cweijan** [comment]
Mongodb stop maintenance.
