### ISSUE TITLE
Is it possible to bind a shortcut to `Run Query` in ElasticSearch query? If possible, how?

### ISSUE THREAD

**Issue by Mr--WhaT** [cweijan/vscode-database-client#300]
I want to bind a shortcut to `Run Query` in es just like the `Cmd + Enter` shortcut to run sql in sql.

I tried binding  `MySQL:Run This Query` command. But when I press the shortcut, an error shows in the output panel: `TypeError: Cannot read property 'run' of undefined`.

 So is it possible to bind a shortcut to `Run Query` in ElasticSearch query?

**Comment by cweijan** [comment]
Version 4.1.6 bind ctrl+enter to run es query.
