### ISSUE TITLE
Issue upon installation

### ISSUE THREAD

**Issue by ericlimshen** [cweijan/vscode-database-client#31]
Hi,

Not sure whether I missed something out but the extension doesn't seem to work I get
command 'mysql.connection.add' not found upon clicking + .

Do I need to configure or install something first before using this plugin.  Thanks.

**Comment by Gabriel-Goldschmitt** [comment]
Hey, 
I have installed this extension today.
It was enough for me to restart VS-Code.

Let's hope it works.

**Comment by cweijan** [comment]
Can you provide OS version and vscode version?

**Comment by ericlimshen** [comment]
Windows 10.  Details of vscode version is as per below

**Comment by ericlimshen** [comment]
Hi,

It works after I restarted vscode.  Thks
