### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by fengshe** [cweijan/vscode-database-client#32]
- Issue Type: `Performance`
- Extension Name: `vscode-mysql-client2`
- Extension Version: `2.1.8`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.45.1`
can't connect
:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\29220\cweijan.vscode-mysql-client2-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by cweijan** [comment]
Add below setting to vscode.
`
{
  "vscode-mysql.loadMetaOnConnect":false
}
`
