### ISSUE TITLE
command 'mysql.connection.config' not found[BUG]

### ISSUE THREAD

**Issue by dongyaohong** [cweijan/vscode-database-client#330]
- OS INFO :
安装了mysql的插件，之后点击哪个数据库的按钮都会显示这个 command 'mysql.connection.config' not found。我本地安装了一个mysql  Ver 15.1 Distrib 5.5.68-MariaDB 版本的。卸载了几次也不行。刚用VSCODE不太会用

**Comment by cweijan** [comment]
可能是你安装了其他什么扩展导致冲突了.
