### ISSUE TITLE
Feature Request: Button duplicate value for record

### ISSUE THREAD

**Issue by cvphat4796** [cweijan/vscode-database-client#333]
- OS Info: Windows
- It's great if we have one more button next to Insert new row button when we tick some of record to duplicate them
![image](https://user-images.githubusercontent.com/22562250/138269735-0fdbcdf7-c882-44de-984e-f9ff7bef22c4.png)

**Comment by cweijan** [comment]
Right click then choose open copy dialog.
![image](https://user-images.githubusercontent.com/27798227/138382691-bb53945c-dcc6-492e-9999-79d01a7b328f.png)

**Comment by cvphat4796** [comment]
> Right click then choose open copy dialog. ![image](https://user-images.githubusercontent.com/27798227/138382691-bb53945c-dcc6-492e-9999-79d01a7b328f.png)

It only copy one record. I want a button when we tick  some of records to duplicate them. I will update description of the issue

**Comment by cweijan** [comment]
Multi-select copy operation is too complicated, I have no plans to support .

**Comment by cvphat4796** [comment]
Thanks for your response
