### ISSUE TITLE
[BUG] Opening SQL file, has option to run the code but doesn't show errors/output

### ISSUE THREAD

**Issue by adair-kovac** [cweijan/vscode-database-client#335]
- OS INFO :
  - macOS Mojave 10.14.6
  - Visual Studio Code 1.58.2 (Universal)
  - MySQL plugin v4.1.7
  
When I open a pre-existing SQL file, it lets me right-click and "Run Selected SQL", but I don't get output or an error message. I'm unsure whether the code ran. It also has options to "Run All SQL" and "Change Active Database". 

I can run the code and get output if I create the .sql file by clicking the page icon next to the db in the sidebar for the plugin.

Is this a bug, or does the plugin only support sql files it created? If the latter, that seems like it should be explicitly documented, and/or the misleading menu options should be removed on unsupported .sql files. (I verified that the menu options go away when I disable this plugin.)

**Comment by cweijan** [comment]
The extension supports running from any SQL file, you need to change active database first.
