### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by fsoft72** [cweijan/vscode-database-client#35]
The Table view should feature a dark mode to best fit with VSCode dark mode themes,

**Comment by cweijan** [comment]
I am willing to develop dark mode, but I cannot design a good-looking UI. If you can give some reference, it will promote the development of dark mode.

**Comment by dhonx** [comment]
@cweijan I will do it if you wish...

**Comment by cweijan** [comment]
@dhonx Thanks, you can implement it and create PR.

**Comment by cweijan** [comment]
@dhonx  I didn’t create a dev-server for the webview page, and I reopened the webview after modifying the page source. Modifying the page is cumbersome.

**Comment by dhonx** [comment]
Sure! I can setup it

**Comment by jpagarcia** [comment]
Looking forward to this! 

@cweijan I've been looking for a good MySQL extension for VSCode, I tried a lot, yours is perfect for me!

**Comment by cweijan** [comment]
New version 2.3.0 has bean add dark theme.

**Comment by jpagarcia** [comment]
How do you enable it?

**Comment by jpagarcia** [comment]
Found it, just update the setting to "dark"

![image](https://user-images.githubusercontent.com/2853613/86983461-848cfa00-c1be-11ea-99c4-4b298a7d4408.png)

**Comment by jpagarcia** [comment]
or just update it in the results page itself

![image](https://user-images.githubusercontent.com/2853613/86983585-ce75e000-c1be-11ea-9d46-9be7605fcfce.png)

**Comment by cweijan** [comment]
Theme switching is extremely friendly.

**Comment by RedstoneExpert** [comment]
It will be maybe good idea to make the background #1e1e1e, so it has same color as other editor windows.
