### ISSUE TITLE
Can we input one more db names on "Connect to MySQL server" Panel?

### ISSUE THREAD

**Issue by baiyyee** [cweijan/vscode-database-client#36]
For now, we only two choices for database field  on "Connect to MySQL server" Panel: one db or empty( all db),  but for some scenarios, we got so many dbs here and only want some of them to show on connect items, can we input one more db names on "Connect to MySQL server" Panel? or, provide a setting item on the UI to display or hidden the specified dbs?
![only two choices here - one db or empty( all dbs)](https://user-images.githubusercontent.com/4414171/83943469-fa541d80-a82e-11ea-9b01-a81303f4dbf1.png)

**Comment by cweijan** [comment]
This is a good suggestion. I will add it in the next version.

**Comment by cweijan** [comment]
In order not to cause semantic errors, I do not intend to support this feature, you can exclude the specified database in excludeDatabases.

**Comment by cweijan** [comment]
The newest version has been support.
![image](https://user-images.githubusercontent.com/27798227/105798341-ec752780-5fcc-11eb-9996-82bfdd259a42.png)

**Comment by zcysxy** [comment]
@cweijan Hello! What's the syntax of this field? I tried `db1, db2`, `db1; db2`, and `[db1, db2]`, none of these works. They either display only one database or none at all.

**Comment by cweijan** [comment]
@zcysxy db1,db2

**Comment by zcysxy** [comment]
@cweijan Thanks for the fast reply! It doesn't work for me now, but it's not a big deal. I'll try again sometime later. By the way I'm adding/editing Postgresql connections.
