### ISSUE TITLE
Is it possiable to transfer "Generate Mock Data" feature into Python library?

### ISSUE THREAD

**Issue by baiyyee** [cweijan/vscode-database-client#37]
"Generate Mock Data" is such a awesome feature for me, so I want bring it to my python code and try to generate db data with your way, so I wonder if Is this possiable to transfer "Generate Mock Data" feature into Python library?

**Comment by cweijan** [comment]
The extension is written in typescript, if you want to implement this function, obviously you need to use Python to rewrite,
A total of three steps are required
1. Query information_schema.TABLES to get the table structure
2. Create insert sql and mock options based on table information
3. Merge insert sql and mock data, run final insert sql.
