### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by HemantVashist** [cweijan/vscode-database-client#38]
- Issue Type: `Performance`
- Extension Name: `vscode-mysql-client`
- Extension Version: `1.9.8`
- OS Version: `Linux x64 5.3.0-61-generic`
- VSCode version: `1.46.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/hemant/cweijan.vscode-mysql-client-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by cweijan** [comment]
Add to setting.
```jsonc
{
  // Load database meta info when connected, If your machine's performance is low, turn it off.
  "vscode-mysql.loadMetaOnConnect":false
}
```
