### ISSUE TITLE
F9 Dead (v2.2.5 or more)

### ISSUE THREAD

**Issue by nn-hh** [cweijan/vscode-database-client#39]
Sorry I can't speak english.

Run MYSQL Query(F9) is Dead

mysql password is null

v2.2.4 is work

windows10
xampp
Confirmed with php 5.6, 7.2

**Comment by cweijan** [comment]
Can you support screenshot?

**Comment by nn-hh** [comment]
↓ v2.2.5,v2.2.6 F9 is don't work
![test](https://user-images.githubusercontent.com/38947828/86478650-87828780-bd85-11ea-9423-7dc2f8a39582.jpg)

↓ v2.2.4 F9 is work
![test2](https://user-images.githubusercontent.com/38947828/86478663-8fdac280-bd85-11ea-91eb-58f67ffe1ce4.jpg)

↓ config
![test3](https://user-images.githubusercontent.com/38947828/86478672-936e4980-bd85-11ea-99f5-95dec6c3a319.jpg)

**Comment by cweijan** [comment]
Update to 2.2.7 fix.

**Comment by nn-hh** [comment]
Thank you.
quick response.
It's fixed.
