### ISSUE TITLE
[BUG] Fail to dump from PostgreSQL if password contains special characters

### ISSUE THREAD

**Issue by yuxiao-indeed** [cweijan/vscode-database-client#394]
- OS: Mac (connecting to a remote Linux machine)
- Database Type: PostgreSQL

The error message says: `failed: FATAL:  password authentication failed for user "postgres"`.

If I understand it correctly, this is because the password contains special characters (`$`). The command is like `export "PGPASSWORD=$abc" && pg_dump ...`. In this case `$abc` will be expanded, and thus it will be different from the real password.

We probably need to escape in the export command.

**Comment by cweijan** [comment]
Try version 4.3.3.

**Comment by yuxiao-indeed** [comment]
It still doesn't work :(

**Comment by yuxiao-indeed** [comment]
I see you are doing `export "PGPASSWORD='${password}'"`. Assuming password is "$abc", the actual command will be 

```bash
export "PGPASSWORD='$abc'" && ...
```

When shell executes the command it will do expansion first. Assuming `$abc` is not defined, the command will become

```bash
export "PGPASSWORD=''" && ...
```

So it still doesn't work.

I see you are already using `exec` in `child_process`. `exec` already supports an `env` option: https://nodejs.org/api/child_process.html#child_processexeccommand-options-callback.
It's probably better to pass the password through `env` option. I can try to make a PR if you are ok with it.

**Comment by cweijan** [comment]
I think just need to remove the double quotes.

**Comment by cweijan** [comment]
Try version 4.3.5, I have tested it can work normally.

**Comment by yuxiao-indeed** [comment]
Yes this worked. Thanks!
