### ISSUE TITLE
Add right click to change databases

### ISSUE THREAD

**Issue by silverbullettruck2001** [cweijan/vscode-database-client#4]
Add an ability to change database context via right click option instead of requiring a new query

**Comment by cweijan** [comment]
Since version 1.7.30, the query file will bind database, you change database when switch query file.

**Comment by silverbullettruck2001** [comment]
But if I have a query file with scripts in it and I want to run the same scripts on different databases that I am connected to,  would need to have separate files for each database or I would have to fully qualify the database names and change them between executions.  It would be easier if I could just right click on a server and say "Select DB" and then it would run in that context.  Then pick the next database, and run the same script in the same file.  Rather than have multiple instances of the same scripts, just in different files to maintain the DB context.  Could that be done?

**Comment by cweijan** [comment]
It's a good idea to add switching database context on the menu, I'll add this feature.

**Comment by cweijan** [comment]
I added this feature since version 1.8.0.

**Comment by silverbullettruck2001** [comment]
@cweijan I tried using this feature but when I right click on a database it doesn't have a "Select DB" option.  I verified I am on 1.9.1 so it should include this feature.  Can you clarify how this should work?
