### ISSUE TITLE
[BUG] On the VSCode update, it just shows blank.

### ISSUE THREAD

**Issue by jpagarcia** [cweijan/vscode-database-client#40]
- OS INFO :

![image](https://user-images.githubusercontent.com/2853613/87120061-28a39d80-c2b2-11ea-9e98-6d284eb1342c.png)

**Comment by cweijan** [comment]
I'm sorry I didn't have this problem, you need to open the console to give me the error message.
1. Open Command Palette.
![image](https://user-images.githubusercontent.com/27798227/87121344-2727a480-c2b5-11ea-818e-ba4b261d8d61.png)
![image](https://user-images.githubusercontent.com/27798227/87121362-3149a300-c2b5-11ea-97dc-f0e718d5940c.png)

**Comment by xwillq** [comment]
I have the same problem, both on Windows and inside wsl. Here is the error and the stack trace:

![image](https://user-images.githubusercontent.com/38136135/87136973-6a3e4380-c2c6-11ea-9617-09a255ed2446.png)

**Comment by cweijan** [comment]
Update to 2.3.2 fix.
