### ISSUE TITLE
Add row limit in Settings JSON

### ISSUE THREAD

**Issue by ilan274** [cweijan/vscode-database-client#41]
- OS Info: Xubuntu 18.04

Hello!
First of all, I would like to say this is the best extension I've found so far for MySQL.

The only feature I miss is the same as the MySQL workbench, where you can limit the row count, not having to specify the LIMIT XX in every query.

Thank you :)

**Comment by cweijan** [comment]
In fact, most clients will automatically add limit, but they hide it. In the next version, I will add an option to set the default limit size.

**Comment by ilan274** [comment]
That would be perfect!

Thanks

**Comment by cweijan** [comment]
2.3.7 has been add this feature.
![image](https://user-images.githubusercontent.com/27798227/87890810-90a07380-ca6a-11ea-8695-99953fac55c3.png)

**Comment by ilan274** [comment]
Hey, Cweijan!
Not sure why, but it's not working here.
I've limited to 20 rows (screenshots below), and even though it's printing all 195 rows from the actor table (sakila).

Settings: http://i.imgur.com/6jUeU1M.png divided with results.
Settings.json also OK with ""vscode-mysql.defaultLimit": 20".
PS: all the other options work fine, like max table count.

Thank you for your quick response and for adding this amazing feature, btw :)

Edit: I've also tried uninstalling, removing it from the ./vscode/extensions folder, and installing again but nothing changed.

**Comment by cweijan** [comment]
There is no limit to directly executing select, This needs improvement, please wait for the next version.

**Comment by cweijan** [comment]
Version 2.3.12 has been auto add limit for select.

**Comment by ilan274** [comment]
Thank you very much, @cweijan :+1: :100:
