### ISSUE TITLE
Improve active database selection

### ISSUE THREAD

**Issue by Maunzerle** [cweijan/vscode-database-client#42]
- OS INFO: Win 10 2004

I work with multiple hosts and databases at the same time and this MySQL client helps a lot!

However, there is a high risk of code running for the wrong host (even with the little host-IP in the status-bar).

The following changes would be a great asset to me:
- Set active DB via Explorer: "Explorer / Host or Database / context menu / Set as active for current query"
- Show active DB via Explorer - highlight the current active host and db when you switch through the queries / tabs
- "Query / context menu / Change Active Database" is far too confusing because the host is only in front of the name if databasenames exist twice in all hosts. My suggestion would be to always put the connection name in front

![change_active_database_example](https://user-images.githubusercontent.com/68692066/88284946-94442c80-ccee-11ea-88e1-09b8acc9c2df.png)

Thanks for reading!

BTW: Keep the work up! This is by far the best client vor VSCode! Star nr. 100 for you!

**Comment by cweijan** [comment]
This is a good idea, I will release in the next version, but I am busy at the moment, please wait for the next release.

**Comment by cweijan** [comment]
Version 2.3.11. has been support highlight active connection.
