### ISSUE TITLE
[BUG] Freeze when calling procedures

### ISSUE THREAD

**Issue by Ming-Han** [cweijan/vscode-database-client#43]
- OS INFO : WINDOWS 10

When I try to call any store procedure, the output display only freezes on the loading page. I am not sure this feature is not supported yet or it's a bug, or there is something wrong in my vscode's settings. Additionally, if I click a procedure in the left control bar, the system will show "Error: ER_SP_DOES_NOT_EXIST: PROCEDURE undefined does not exist".

**Comment by cweijan** [comment]
The expected action of clicking the stored procedure is to view the source code, which has been fixed, I have no plan to support the output of stored procedures.
