### ISSUE TITLE
I'm a criminal

### ISSUE THREAD

**Issue by jbnv** [cweijan/vscode-database-client#437]
I'm a piece of shit in the world.

**Comment by cweijan** [comment]
You need to uninstall this extension immediately, I do not welcome you to be my user, fuck off.

**Comment by cweijan** [comment]
You talk to the author in a commanding tone, have you paid a dime for this software? You should really fuck off, I don't owe you anything.

**Comment by cweijan** [comment]
Yes, you are right😂.
