### ISSUE TITLE
[BUG] Auto generated SQL statements don't have backtics around table and column names

### ISSUE THREAD

**Issue by xwillq** [cweijan/vscode-database-client#44]
- OS INFO : Any OS

SQL statements generated by extension don't use backtics, which breaks them when table or column names are reserved words.
Example:
![sql-error](https://user-images.githubusercontent.com/38136135/88454088-048db200-ce97-11ea-97fe-e3ef603ae45b.png)

**Comment by cweijan** [comment]
update to 2.3.9 fix.

**Comment by xwillq** [comment]
Works great, thank you!
