### ISSUE TITLE
IBM Informix DB

### ISSUE THREAD

**Issue by iliev72** [cweijan/vscode-database-client#445]
Please add support for IBM Informix DB.

**Comment by cweijan** [comment]
Sorry, not this plan.

**Comment by ceinmart** [comment]
Hi, +1 for informix ... 
@cweijan , 
Informix drivers can be easly get on https://mvnrepository.com/artifact/com.ibm.informix/jdbc . 
As far I know, informix jdbc is very standard compliance. 
Check here , it's type 4 , https://help.hcl-software.com/hclinformix/15.0/jdbc/ids_jdbc_012.html

Is there no way to add it in customization mode?  something like dbeaver client do ?
