### ISSUE TITLE
[BUG] All "NOT NULL" colums show as "required" in the insertion dialog

### ISSUE THREAD

**Issue by ARitz-Cracker** [cweijan/vscode-database-client#47]
- OS INFO : Ubuntu 20.04, Linux 5.4.0-42-generic, x64

Hello! I'm really enjoying this plugin! It's very useful!

I'd like to report a small issue. When you click the (+) button to insert a new row in a table within the transactions menu, all `NOT NULL` columns are showed as "required", but this isn't true under the following conditions:

1. Columns with `AUTO_INCREMENT` applied
2. Columns with a `DEFAULT` value

**Comment by cweijan** [comment]
This is good feature, I has bean add it to version 2.3.11.

**Comment by ARitz-Cracker** [comment]
Thank you!
