### ISSUE TITLE
[BUG] column display bug

### ISSUE THREAD

**Issue by miaoyiwang** [cweijan/vscode-database-client#50]
- OS INFO :

 when I selected id (bigint(20)) from table,  then it display like this:

1292434711813128200
1292434718599512000
1292434961730732000
1292434968399675400 
1292434968399675400

The last two digits are carried forward.

Here's the real story：
+---------------------+
| id                  |
+---------------------+
| 1292434711813128194 |
| 1292434718599512065 |
| 1292434961730732034 |
| 1292434968399675393 |
| 1292434968399675394 |
+---------------------+
5 rows in set (0.00 sec)

**Comment by cweijan** [comment]
Update to 2.4.5 fix.

**Comment by miaoyiwang** [comment]
> Update to 2.4.5 fix.

thanks a lot
