### ISSUE TITLE
[BUG]IP address connection error

### ISSUE THREAD

**Issue by mengyilingjian** [cweijan/vscode-database-client#52]
- OS INFO : Windos 10:Windows_NT x64 10.0.19041, vscode : 1.47.3, vscode-mysql :v2.4.6
172.18.56.185

- When I enter host as 172.18.56.185, I find that the IP address prompted is not correct. The specific information is as follows：
`Connection error! ER_HOST_NOT_PRIVILEGED: Host '172.18.48.1' is not allowed to connect to this MySQL server`
- When I enter host as 10.0.10.27, I find that the IP address prompted is not correct. The specific information is as follows: 
 `Connection error! ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'10.222.0.1' (using password: YES)`
![image](https://user-images.githubusercontent.com/34885772/90084835-01287080-dd49-11ea-99ee-5443850bc004.png)

**Comment by cweijan** [comment]
![image](https://user-images.githubusercontent.com/27798227/90095186-7f454100-dd62-11ea-9df6-6c0ca66e3f9c.png)
These is mysql server error, you should search on google.
