### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by spiderneo** [cweijan/vscode-database-client#525]
I'm using the new version with Premium plan. 
I'm using the ssh connection a lot to edit some conf directly on server. But iI having an issue when iI got 2 files on 2 servers with the same name, 1 will replace the other when selected and write to the wrong remote file if i'm not carefull.

Maybe a workaround would be to add a "context" like server name or else to the temporary file edited on local machine to solve this issue ?

I want to point out that the new version and the possibility to add group to a connection is just so handy :) Thx

**Comment by cweijan** [comment]
Hi, please try the version after 5.0.2, now I have generated a tree structure to avoid same file name.

**Comment by spiderneo** [comment]
Hi i'm on 5.0.3.
The tree structure don't include the name of the ssh server ? Because i don't see it on the temp path file. 
In my case path are generally the same, but not the files. 
For example, on server 1, I have /srv/example.sh, and on server 2 exactly the same path and name. Files are override.

Also since upgrade to 5.0.2, i have double icones and context menu on file. I removed old version "ssh client" and reinstall database client but no change.

![Capture d’écran 2022-03-30 à 17 20 29](https://user-images.githubusercontent.com/3339248/160871169-977e2c0a-1365-4b97-92d5-dd07017ea242.png)
![Capture d’écran 2022-03-30 à 17 22 22](https://user-images.githubusercontent.com/3339248/160871396-50b714dc-6a20-4e45-82c0-2c3983773559.png)

**Comment by cweijan** [comment]
Ok, this problem does exist on different services, I will fix it in the next version.

When you uninstall the extension, you need to restart vscode.

**Comment by spiderneo** [comment]
ok thx for the next version ;)

For the other issue do you prefer i make another issue ? I did restart Vscode (multiple time actually). 

My guess is there is some ref to a previous version which are not correctly uninstall. 
Because like i said, i come from the plugin "ssh client" if i use 1.8.3 version, i have the old icons and the new one, and only the are not double in the new one :) with 1 extension (these tests was made with only ssh client extension )^^ not SUR if i'm very clear :s 

Where are the settings for the list of remote server are written ? i found this /Users/xxx/Library/Application Support/Code/User/globalStorage/cweijan.vscode-database-client2/config.json but if i remove it, the list of server are still here. so must be somewhere another json  ?

**Comment by cweijan** [comment]
I have released several extensions with different names but the same function, you only need to install one.

The configuration file is only temporarily generated, but only for editing. The actual data storage is only accessible by this extension, this is for data security

**Comment by spiderneo** [comment]
Ok ... found the issue  then ;)
Before your update, i had 2 extensions, ssh client and mysql. 
But now both are the same, and when i installed database client (the main one) i uninstall ssh client but not mysql. so double conf, double icones ^^

Maybe you could make a message or something when you detect the same extension is installed ;)

thx for your anwser

**Comment by cweijan** [comment]
Fix in version 5.0.4.

**Comment by spiderneo** [comment]
Perfect, thank you ;)
