### ISSUE TITLE
[BUG] Why the query didn't show nothing? 

### ISSUE THREAD

**Issue by wsh3776** [cweijan/vscode-database-client#54]
- OS INFO :
The query can show me sql result. And it worked in the past week. But when I use it and `Run MySQL Query` today, it somehow gets in trouble and show nothing. I don't do anything why this happens?

![image](https://user-images.githubusercontent.com/46078304/90643056-b5545a80-e265-11ea-93f2-a0926f1e658b.png)

**Comment by cweijan** [comment]
Press ctrl+shift+i to open developer tool show error, this helps me find the problem.

**Comment by wsh3776** [comment]
I have reinstalled the old version of MySQL plugin. And it works now.
