### ISSUE TITLE
[BUG] Delete All rows in table not working.

### ISSUE THREAD

**Issue by ahmdhsn-dev** [cweijan/vscode-database-client#56]
When I try to select all rows and delete the rows on provided GUI it does not perform the required action. The reason is it prepends a comma(,) before the first id which makes an invalid SQL syntax. You can see from the image below.
![Screenshot from 2020-08-25 10-08-29](https://user-images.githubusercontent.com/30392509/91125347-f8c22500-e6ba-11ea-903b-9760258d97f5.png)

- OS INFO : Ubuntu 18.04

**Comment by cweijan** [comment]
Update to 2.5.3 fix.

**Comment by ahmdhsn-dev** [comment]
Great! It is fixed
