### ISSUE TITLE
[BUG] Errors in autogenerated sql queries

### ISSUE THREAD

**Issue by xwillq** [cweijan/vscode-database-client#57]
- OS INFO : Ubuntu WSL

Double backtics around column name:
![image](https://user-images.githubusercontent.com/38136135/91176641-c6d9ae80-e70c-11ea-9402-0dbbc4ce5a9e.png)
No backtics around column name in where:
![image](https://user-images.githubusercontent.com/38136135/91176668-cf31e980-e70c-11ea-8db0-212c7eedf903.png)
![image](https://user-images.githubusercontent.com/38136135/91176910-2768eb80-e70d-11ea-8209-0c628d8c93e1.png)

Queries were generated in ui.

**Comment by cweijan** [comment]
update to 2.5.4 fix.
