### ISSUE TITLE
[BUG]无法区分空字符串字段和null的结果展示

### ISSUE THREAD

**Issue by pinyht** [cweijan/vscode-database-client#579]
- OS: macos12.3.1
- Database Type: mysql 8.0.26

在查询结果表格中,无法区分空字符串字段和null字段,在其他数据库工具中,如果是空字符串,当前单元格什么都不会显示,如果是null,就会显示null,但是在这个插件上,不管是空字符串还是null,显示的都是 "(NULL)", 无法进行区分, 希望可以改进展示

**Comment by cweijan** [comment]
已经发布5.2.7版本修复了这个问题。

**Comment by pinyht** [comment]
已经正常,谢谢
