### ISSUE TITLE
Adding multiple connections

### ISSUE THREAD

**Issue by wywarren** [cweijan/vscode-database-client#58]
Based on the screenshots in the description there seems to be a way to add multiple connections but whenever I make a new server connection the previous one is replaced only showing one blue database icon at a time. Is there something else that needs to be done to have more than one stored database? Thanks

**Comment by cweijan** [comment]
If you want to create multiple connections, you need to use other users. Currently, host + root is used as the unique identifier of the connection.

**Comment by makkuro-kuroe** [comment]
Hi, I'm the same problem... 
I'm trying to create 2 connections on the same proxy-host and user, but with different DBs. ( if i clear the database field on the connection settings neither of the DBs appears on the list) 

It could be better if there is not a restriction based on the host+user, but with the connection name...
