### ISSUE TITLE
提一个建议，表字段使用默认排序而不是字段名称排序

### ISSUE THREAD

**Issue by re2953** [cweijan/vscode-database-client#59]
- OS Info:
windows,mac

这个工具很好用，再也不用寻找各平台的数据库工具了

我加了个排序就可以实现，这样看上去正常点，希望下个版本可以加上去

```
vi +4282 ./out/extension.js
 ORDER BY ORDINAL_POSITION
```

![image](https://user-images.githubusercontent.com/72176016/94756069-0f018600-03c9-11eb-9767-ae0359ef0c12.png)

**Comment by cweijan** [comment]
你的mysql和操作系统是什么版本可以说下吗, 我在windows默认就是按表的原来顺序排序的, 隐约记得以前也有人跟我反馈过这个.

**Comment by re2953** [comment]
最新的版本8.0，在windows和mac上都是按字段顺序，而不是按表结构顺序。
你看测一下那个语句在6.0或者7.0有没有问题，我感觉加个ORDER应该不影响，兼容性更好，就看那个字段在不在的问题了。



在 2020-10-01 13:31:09，"Chen WeiJian" <notifications@github.com> 写道：

你的mysql和操作系统是什么版本可以说下吗, 我在windows默认就是按表的原来顺序排序的, 隐约记得以前也有人跟我反馈过这个.

**Comment by cweijan** [comment]
2.5.9 已经加了排序.
