### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by druidemaxd** [cweijan/vscode-database-client#6]
- Issue Type: `Performance`
- Extension Name: `vscode-mysql-client`
- Extension Version: `1.7.20`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.45.0-insider`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\druide\cweijan.vscode-mysql-client-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by cweijan** [comment]
Can you upload C:\Users\druide\cweijan.vscode-mysql-client-unresponsive.cpuprofile.txt?
