### ISSUE TITLE
Update SQLite version

### ISSUE THREAD

**Issue by JonatasAmaral** [cweijan/vscode-database-client#602]
As found in the `.vscode/extensions` directory, the SQLite version used is still v3.26

This version doesn't support SQLite's Generated Columns, and fails to completely load any table, reporting a sintax error on "AS" statement.
A simple replacement of the `sqlite3[...].exe` file in extension folder, with the most recent one from SQLite site, solved this issue locally.

**Comment by cweijan** [comment]
Hi, I released version 5.3.9, upgraded sqlite3 to the latest version.

**Comment by JonatasAmaral** [comment]
Hey, real nice!
thanks for that
