### ISSUE TITLE
尚不支持登录验证方式为caching_sha2_password的账户

### ISSUE THREAD

**Issue by kairlec** [cweijan/vscode-database-client#63]
- OS Info: 无需  

- 提示:
```
Client does not support authentication protocol requested by server; consider upgrading MySQL client
```

**Comment by cweijan** [comment]
![image](https://user-images.githubusercontent.com/27798227/95720019-41519400-0ca3-11eb-959c-e3453ed2f442.png)
 不支持mysql8mo默认方式, 需要修改
