### ISSUE TITLE
Limited number of tables visible

### ISSUE THREAD

**Issue by t-schroeder** [cweijan/vscode-database-client#64]
I have a Moodle installation with a few plugins which already has more tables than can be displayed. I can't even see the user table because it cuts off at tables starting with 's'. In its current state the extension is therefore not usable for me.

**Comment by cweijan** [comment]
I not understand your mean, can you support screenshot?

**Comment by t-schroeder** [comment]
I have a database with 584 tables and only the first 500 are shown under TABLE.

**Comment by t-schroeder** [comment]
Nevermind, I just noticed I can raise this limit through settings.
