### ISSUE TITLE
Table filter

### ISSUE THREAD

**Issue by t-schroeder** [cweijan/vscode-database-client#65]
It would be nice if you had a text input field where you could type something, hit &lt;enter&gt; and it would only show the tables whose name contains your filter term. Like in phpMyAdmin.

**Comment by cweijan** [comment]
I also want this function, but vscode does not have such an API at present. If it is supported in the future, I will add it.

**Comment by cweijan** [comment]
The best practices is double click table, then type you table name.
![image](https://user-images.githubusercontent.com/27798227/95989265-9d134d00-0e5c-11eb-83d6-15901bb6f4a5.png)

**Comment by t-schroeder** [comment]
Thanks, I didn't even know about this feature.
