### ISSUE TITLE
[BUG]usingSSH 无法使用，相同的信息navicate可以正常访问

### ISSUE THREAD

**Issue by reake** [cweijan/vscode-database-client#66]
- OS INFO :
usingSSH 无法使用，相同的信息navicate可以正常访问
vscode Mysql 工具会报错误信息：Ssh tunel occur error : Error: Handshake failed: no matching client->server cipher

**Comment by cweijan** [comment]
老哥知道你ssh服务器用的什么算法吗.

**Comment by cweijan** [comment]
![image](https://user-images.githubusercontent.com/27798227/104413794-f436d400-55a9-11eb-9df3-332f5cd27243.png)
新版本连接时可以指定ssh的加密算法.
