### ISSUE TITLE
Workspace based database config

### ISSUE THREAD

**Issue by kissunda** [cweijan/vscode-database-client#67]
Hi, I have a config where I have a mix of host machine and virtual machine databases. The problem is that the virtual machines only running for specific projects, so when I open a workspace which does not need the virtual machine, this plugin frequently shows an error that it cant connect to that database.

A feature would be awesome where i can config or at least disable connections based on workspace, so it does not want to connect.

**Comment by cweijan** [comment]
This is a good suggestion, I will add this option in the future.

**Comment by cweijan** [comment]
Version 2.6.0 has been support create workspace connection.
![image](https://user-images.githubusercontent.com/27798227/96551629-2d321600-12e5-11eb-9ddb-cc8ac4c5caca.png)

**Comment by kissunda** [comment]
thank you, ill check this out

**Comment by kissunda** [comment]
the workspace separation seems working good. the problem is that i cannot move existing connections to workspace (the switch is ineffective in that case). maybe you can remove the switch for existing connections.
further problem is that i cannot delete existing connection to recreate with workspace setting

**Comment by cweijan** [comment]
Hi, you can edit connection then change mode.
![image](https://user-images.githubusercontent.com/27798227/96553991-89e30000-12e8-11eb-9a1a-2477b4f85541.png)

**Comment by kissunda** [comment]
yep, i can see the edit sceen and the global switch. what i'm saying is that it has no effect. it seemingly saves the state, but its name is still **_global and its active on every workspace

**Comment by cweijan** [comment]
Maybe you were misled by my screenshot. I indicated that this is a switch. If you want to set it to non global, you should turn it off
![image](https://user-images.githubusercontent.com/27798227/96555460-6456f600-12ea-11eb-85c1-cc2eb0b63d7a.png)

**Comment by kissunda** [comment]
again, i know how it should work and i saw switches before :D the problem is that it wont move the existing connection to workspace mode. it stays global. newly created connections are fine

**Comment by cweijan** [comment]
Thanks your feedback, It's really my fault. Try version 2.6.2. I think it works.

**Comment by kissunda** [comment]
Thanks, it works now
