### ISSUE TITLE
Got an error when I run file but the file has no error

### ISSUE THREAD

**Issue by j-clavoie** [cweijan/vscode-database-client#68]
Hello,

I tried to RUN a sql file that contains the following lines:
```
insert into Articles ( nom ) VALUES ( 'The name of the Articles' );
set @last_articleID = LAST_INSERT_ID();
insert into Acquisitions ( mode_paiement_id, fournisseur_id, article_id ) VALUES ( 1, 1, @last_articleID );
-- Comment here

```
When I run  this file with directly with mysql, everything is working very well. 
But when I tried to run this file with F9, I got error.
It seems that the value of @last_articleID is empty, and this field is mandatory.

Why this file, that works well, is not working when I run it inside Visual Code with the F9 key?

Does each line is executed separately?
How the way to fix that?

It's the only issue I got with your extension. The rest is very excellent.

Thanks..

**Comment by cweijan** [comment]
I try run your code, it work ,please provide the error information.
![image](https://user-images.githubusercontent.com/27798227/96805912-4e117d00-1445-11eb-8e24-bf2b9a4a80c5.png)

**Comment by j-clavoie** [comment]
Hello,

Thank you for your fast reply.
So, there is a screen shot of the error I got when I try to use F9 to
execute my sql file.
[image: image.png]

Thanks



Le mer. 21 oct. 2020, à 21 h 03, Chen WeiJian <notifications@github.com> a
écrit :

**Comment by cweijan** [comment]
Your image not showed.

**Comment by j-clavoie** [comment]
Sorry, I attached it now instead of paste it.
I hope that work now
Thanks

Le mer. 21 oct. 2020, à 22 h 34, Chen WeiJian <notifications@github.com> a
écrit :

**Comment by cweijan** [comment]
I understand what you mean. When you press F9, this plugin execute sql of active row, not all sql, solution is press ctrl+a to select all sql, then press f9.

**Comment by j-clavoie** [comment]
Thanks 😁

Le mer. 11 nov. 2020 20:11, Chen WeiJian <notifications@github.com> a
écrit :

**Comment by blacksheepaul** [comment]
> I understand what you mean. When you press F9, this plugin execute sql of active row, not all sql, solution is press ctrl+a to select all sql, then press f9.

First, thanks for your working !
Then, I think that should be in the user guide. XD

**Comment by blacksheepaul** [comment]
Because that against my human insinct.( maybe not most of users )
