### ISSUE TITLE
how can i input a timespan like now() in gui?

### ISSUE THREAD

**Issue by zfdok** [cweijan/vscode-database-client#69]
I press the intsert button and jump to a form named "Insert To xxx",
need enter a time stamp type data in a certain column, so i input `now()`,
But it was recognized as a string and throw an error, how can i solve this,bro? thanks!

**Comment by cweijan** [comment]
The function is currently not supported in the GUI, thanks for the feedback, I will implement this feature in the future.

**Comment by cweijan** [comment]
Add on 2.7.3.
