### ISSUE TITLE
Plug-in versions available at Open-VSX is 4 months old

### ISSUE THREAD

**Issue by sivaraam** [cweijan/vscode-database-client#70]
It looks like the latest version of the plug-in isn't available at [Open-VSX](https://open-vsx.org/extension/cweijan/vscode-mysql-client2) yet. The version available there is 2.2.3 while the latest version appears to be 2.6.3.

It would be great if the latest version of the plug-in is available via Open-VSX too.

**Comment by sivaraam** [comment]
Looks like I accidentally filed this issue under the bug label. Sorry about that.

**Comment by cweijan** [comment]
Thanks for using, I have released the latest version to openvsx.

**Comment by sivaraam** [comment]
Great! Thanks for the quick response :)
