### ISSUE TITLE
Open table in new Tab

### ISSUE THREAD

**Issue by yokenji** [cweijan/vscode-database-client#71]
Is it possible to open a new panel when i click on a table, if i have code in a panel and click on an other table to view the colums is loose my tab en my code.

**Comment by cweijan** [comment]
![image](https://user-images.githubusercontent.com/27798227/98184341-217d5b00-1f45-11eb-9ede-92d6fd43997b.png)
Click this button, man.

**Comment by yokenji** [comment]
Hi, Yes this I known but it isn't user friendly, it would be great to open a new tab once you click or double click
on a table because this is what you do a lot change tables and don't wanne loose you current code.
Thanks in advance

**Comment by robfrancken** [comment]
What about having the default action as a config option? I also prefer my table to be opened in a new tab.
