### ISSUE TITLE
Deep black theme 

### ISSUE THREAD

**Issue by TheIgnatious** [cweijan/vscode-database-client#72]
It would be great if there was a deep black theme for the query window. I think its not a lot of work, but also you can tellme how to do it myself.

**Comment by cweijan** [comment]
I think query window is dark, you need provide a screenshot.

**Comment by TheIgnatious** [comment]
In the end I have edited the querydark.js file and replaced the colors to make it look like this:
![image](https://user-images.githubusercontent.com/58629627/98353126-2c0c2300-201f-11eb-845e-60bb864d1a13.png)

**Comment by ghost** [comment]
I'd like the theme to match the current theme used by VS Code. (Personally, I like [One Dark Pro](https://github.com/Binaryify/OneDark-Pro).) To me, an ideal solution would be to make all themes what the user has already chosen.

**Comment by cweijan** [comment]
I has been add auto detect theme to version 1.7.0.

**Comment by cweijan** [comment]
If any one want to improve skin, fork and edit this [css](https://github.com/cweijan/vscode-mysql/blob/master/public/theme/auto.css) file.
