### ISSUE TITLE
[BUG] 2 connections with same Host+user

### ISSUE THREAD

**Issue by makkuro-kuroe** [cweijan/vscode-database-client#73]
- OS INFO : MacOS catalina

Hi, I'm the same problem... described on #58 

I'm trying to create 2 connections on the same proxy-host and user, but with different DBs. ( if i clear the database field on the connection settings neither of the DBs appears on the list)

It could be better if there is not a restriction based on the host+user, but with the connection name...

**Comment by cweijan** [comment]
Since 2.7.3, you can special multi database on this.
![image](https://user-images.githubusercontent.com/27798227/98901782-4c405400-24ef-11eb-8499-9153a23a173e.png)
The idea of this plugin is to manage all databases with only one connection
