### ISSUE TITLE
Adding search to the database tree

### ISSUE THREAD

**Issue by IndrekV** [cweijan/vscode-database-client#74]
- OS Info: MacOs

It would speed up the usage if cmd+f would act as a search trigger and search through all the data listed.

Step by step logic
- Press "Cmd+f"  -> search field is shown in the top
- Typing in this field will search through: database name, table name, field names

I'm willing to look into it myself if I get some guidance on how the left side panel is rendered.

**Comment by cweijan** [comment]
https://github.com/cweijan/vscode-mysql/issues/65#issuecomment-708371497
