### ISSUE TITLE
horizontal scroll issue

### ISSUE THREAD

**Issue by gcasaro** [cweijan/vscode-database-client#75]
I cant scroll horizontally when there is a large number of columns on a single table.
The scrollbar fill the bottom side like it is showing me all columns. 
I can only select the text using mouse to scroll horizontally
![issue](https://user-images.githubusercontent.com/52107055/98820069-fb1c5b80-242d-11eb-8eae-9a2f2bdc666b.PNG)

**Comment by cweijan** [comment]
![image](https://user-images.githubusercontent.com/27798227/98881510-243bfb00-24c5-11eb-8c28-05e077d33b35.png)
This scroll bar can work on my pc.
