### ISSUE TITLE
离线环境的机器无法使用，后续能否支持？

### ISSUE THREAD

**Issue by GitYub** [cweijan/vscode-database-client#76]
- OS Info:
离线环境的机器，查询界面显示不出来。

**Comment by cweijan** [comment]
啥意思, 你的电脑能访问数据库那就能连接

**Comment by GitYub** [comment]
> 啥意思, 你的电脑能访问数据库那就能连接

你好，query查询界面是一片空白的，可能是什么原因呢？

**Comment by cweijan** [comment]
可以截图看看嘛

**Comment by GitYub** [comment]
> 可以截图看看嘛

我发截图给你的163邮箱了~

**Comment by cweijan** [comment]
Hi, 看下邮箱

**Comment by YannLex** [comment]
@cweijan 你好，请问遇到空白的问题怎么解决？

**Comment by cweijan** [comment]
> @cweijan 你好，请问遇到空白的问题怎么解决？

你开个issue说明情况

**Comment by YannLex** [comment]
> > @cweijan 你好，请问遇到空白的问题怎么解决？
> 
> 你开个issue说明情况

谢谢。new issue：https://github.com/cweijan/vscode-mysql/issues/92
