### ISSUE TITLE
Visual Studio 2019 usage?

### ISSUE THREAD

**Issue by sevprgmr** [cweijan/vscode-database-client#77]
- OS Info: Windows 10 Pro

Dear cweijan,

     I love your extension.  It's the remote connect feature that I wish I could use in Visual Studio, which is where I'm having to update a bunch of old ASP.Net/MS Sql Server websites to MySql and the newest versions of .Net/Core that I can get to work.  My main hang-up is securing connection strings from Web.config files into MySqlStringBuilder and such and your Connect feature/code in Visual Code is the best that I have found.  I got so frustrated in VS that I ran some tests in VC to see if I could connect from there.  I just want to be able to develop, design, etc. against one MySql Server and not one local and one remote. The remote connection I need is to the MySql server on Godaddy using SSH over Tcp/Ip and your Connect did it right the very first time, but I'm still having issues with MySql's Connector/Net in VS.  Is there anyway I can get your extension to work in VS?  Thanks.

**Comment by cweijan** [comment]
Visual studio code and visual studio architecture are completely different, so there is no way to migrate this extension to visual studio.
