### ISSUE TITLE
the color of selected filed is the same as backgroup

### ISSUE THREAD

**Issue by wayland3** [cweijan/vscode-database-client#78]
<img width="919" alt="WX20201120-103730@2x" src="https://user-images.githubusercontent.com/23661071/99751109-8677aa00-2b1c-11eb-87d7-5f35655e4805.png">
<img width="863" alt="WX20201120-103810@2x" src="https://user-images.githubusercontent.com/23661071/99751120-8a0b3100-2b1c-11eb-92f7-595568a3540d.png">

**Comment by dmGusai15** [comment]
i think it's your theme issue

**Comment by cweijan** [comment]
Version 2.9.2 support highlight edit row.
