### ISSUE TITLE
Md Abul 

### ISSUE THREAD

**Issue by MDSHEAKHRAFID** [cweijan/vscode-database-client#781]
- Operating system:
- Database type and version:

**Comment by cweijan** [comment]
Please describe your problem. If you need to purchase the premium version, please go to https://database-client.com/#/.

**Comment by cweijan** [comment]
Hi, I released version 6.2.5, now the configurations will no longer have premium restrictions, you can disable the code len by checking below option.
![image](https://user-images.githubusercontent.com/27798227/224908788-40025b39-f51b-482f-a7ea-b0a6de297be5.png)
