### ISSUE TITLE
[BUG] Plug-in doesn't work in Theia

### ISSUE THREAD

**Issue by sivaraam** [cweijan/vscode-database-client#79]
When trying to use the plug-in as a [Theia extension](https://eclipsesource.com/blogs/2019/10/17/how-to-add-extensions-and-plugins-to-eclipse-theia/) in Chrome it loads properly. But when trying to add a connection, I get the following errors in the console:

```js
GET http://0d1333a9-5168-4ada-95fd-ac55af880111.webview.localhost:3000/webview/theia-resource/file///REDACTED/PATH/TO/theia/plugins/vscode-mysql/extension/out/webview/js/antv.js net::ERR_ABORTED 404 (Not Found)
GET http://0d1333a9-5168-4ada-95fd-ac55af880111.webview.localhost:3000/webview/theia-resource/file///REDACTED/PATH/TO/plugins/vscode-mysql/extension/out/webview/js/vendor.js net::ERR_ABORTED 404 (Not Found)
GET http://0d1333a9-5168-4ada-95fd-ac55af880111.webview.localhost:3000/webview/theia-resource/file///REDACTED/PATH/TO/plugins/vscode-mysql/extension/out/webview/js/app.js net::ERR_ABORTED 404 (Not Found)
```

**Steps to reproduce**
1. Clone the Theia repository
    ```bash
    git clone --depth=1 https://github.com/eclipse-theia/theia/
    ```
2. In the `package.json` found in the repository root, add "vscode-mysql" to the plug-ins like so:
    ```js
      ...

      "theiaPluginsDir": "plugins",
      "theiaPlugins": {
        ...,
        "vscode-mysql": "https://open-vsx.org/api/cweijan/vscode-mysql-client2/2.7.3/file/cweijan.vscode-mysql-client2-2.7.3.vsix"
      }

      ...
    ```
3. Run `yarn` in the root directory.
4. Switch to the `examples/browser` directory.
5. Run `yarn start` to start the server.
6. Open the theia window in a browser and execute the "MySQL: Add connection" command.
7. Observe the error noted before in the console.

This was observed in v2.7.3 but is also reproducible with v2.7.7. Note that the plug-in seems to be working fine on Firefox (albeit [with a workaround](https://github.com/eclipse-theia/theia/pull/6465#issuecomment-556443218) to make the webview work properly for local testing)

- OS INFO : Windows 10

**Comment by cweijan** [comment]
I try using on gitpod, it work properly.maybe your eclipse theia needs to be configured.
![image](https://user-images.githubusercontent.com/27798227/100168463-4a698e00-2efc-11eb-852e-21b65651b15b.png)

**Comment by sivaraam** [comment]
It's a weird bug, actually. It works fine for me on Firefox. It just fails to work with Chrome. Can you check if it works fine for you on Chrome?

**Comment by cweijan** [comment]
The file uri is generated using standard api, if there is a bug, it is also due to the incompatibility of eclipse thiea.

**Comment by sivaraam** [comment]
> 
> 
> The file uri is generated using standard api, if there is a bug, it is also due to the incompatibility of eclipse thiea.

Makes sense. I've filed an issue in the Theia repository about this: https://github.com/eclipse-theia/theia/issues/8874

**Comment by cweijan** [comment]
This problem is eclipse theia not support localStorage in webview, version 3.2.5 has been fix.
