### ISSUE TITLE
table list is not sorted

### ISSUE THREAD

**Issue by agungdhewe** [cweijan/vscode-database-client#8]
it will be easier for user to find a table if table list is sorted.
thx for your great tools.

**Comment by cweijan** [comment]
The table list has always been sorted alphabetically.

**Comment by agungdhewe** [comment]
i mean this one

![image](https://user-images.githubusercontent.com/16076253/79670431-24a13b80-81ed-11ea-9aa0-415b79c7dd60.png)

i run this vs code in ubuntu 18

regards

**Comment by cweijan** [comment]
Since version 1.8.0, It sort correctly.
