### ISSUE TITLE
Export View, SP & Function

### ISSUE THREAD

**Issue by dmGusai15** [cweijan/vscode-database-client#80]
- OS Info:
First of all create such a great product.
Export Data function working so fast till time i ever seen, used many product for this is fast.
Need feature regarding Export View, SP & Function which is created.
So, developer don't require any other application for that.

**Comment by cweijan** [comment]
Version 2.8.0 has been support.

**Comment by dmGusai15** [comment]
> Version 2.8.0 has been support.

Thanks for reply !
When i do right click on DBS Name > Export Data occur and click on that give me only Table & View Names not SP & Function.
So, how would i get this all in Export File ? 

![mysql_issue](https://user-images.githubusercontent.com/44797408/100599173-b0537c80-3325-11eb-9a52-e932934679de.png)
