### ISSUE TITLE
Error "This Table has not primary key, update fail"

### ISSUE THREAD

**Issue by DerKleene** [cweijan/vscode-database-client#81]
Hello,

I have the problem above in the subject from version 2.8.0
in version 2.7.7 everything still works fine.
A primary key is available.
Update and insert do not work since version 2.8.0,
I've tried all the versions, it works again in 2.7.7.
Sorry for my bad english, but my english is not the best.
![error](https://user-images.githubusercontent.com/19396070/100588044-a57ef480-32f1-11eb-8a8c-d9af4a5ed480.png)

What could this be?

Many thanks.
greeting
Heiko

**Comment by cweijan** [comment]
Fix at 2.8.3

**Comment by DerKleene** [comment]
Hello,

Thank you for the update, now it works again.

greeting
Heiko
