### ISSUE TITLE
Export SP & Function > Version 2.8.0 has been support.

### ISSUE THREAD

**Issue by dmGusai15** [cweijan/vscode-database-client#82]
> Version 2.8.0 has been support.

Thanks for reply !
Export Data give me only Table & View Names not SP & Function.
So, how would i get this all in Export File ? 

![mysql_issue](https://user-images.githubusercontent.com/44797408/100599173-b0537c80-3325-11eb-9a52-e932934679de.png)

_Originally posted by @dmGusai15 in https://github.com/cweijan/vscode-mysql/issues/80#issuecomment-735701803_

**Comment by cweijan** [comment]
Only table and view can be selected here, Procedure and Function will export by default.

**Comment by dmGusai15** [comment]
Yes @cweijan it's working on 2.8.0 only. 
but why it's not working on further version buddy ?

**Comment by cweijan** [comment]
Sorry, is my mistake, fix at 2.8.4.

**Comment by dmGusai15** [comment]
Man it's ok. i just tell you due to i really need this type of product that don't need any other software for operating DBS.
if you provide 1 more facility regarding Create Table from this extension if possible.
