### ISSUE TITLE
Require Alter View Query 

### ISSUE THREAD

**Issue by dmGusai15** [cweijan/vscode-database-client#83]
- OS Info:
Hey,
The last update was to work perfectly and really helpful to our team.
If possible please generate a feature as below regarding operation in order to avoid using other software for changes and all.

- Create Table
- Alter View

**Comment by cweijan** [comment]
![image](https://user-images.githubusercontent.com/27798227/101130507-8e683b80-363e-11eb-9f59-e498250bcfee.png)
1. Click this button to open create table sql template, I will not enhance the interaction in a short time. 
2. Alter the view is a good feature. I will add it in the next version.

**Comment by dmGusai15** [comment]
Thanks man :+1: Alter View feature work great...
