### ISSUE TITLE
[BUG] JSON form is veiled like `[object Object],[object Object]..`

### ISSUE THREAD

**Issue by sa9sha9** [cweijan/vscode-database-client#84]
- OS INFO : macOS Catalina ver 10.15.7
- VSCode : v1.51.1
- vscode-mysql :  v2.8.5

---

JSON form is veiled like `[object Object],[object Object]..`  when focusing on a json typed data cell.

<img width="630" alt="スクリーンショット 2020-12-08 11 37 14" src="https://user-images.githubusercontent.com/14252323/101431168-ba8b0180-3949-11eb-8777-f458530c19ff.png">

**Comment by cweijan** [comment]
What is the data shown as [object], I cannot reproduce it.

**Comment by bgpark-argonet** [comment]
Column type is json in Mysql

**Comment by cweijan** [comment]
Fix at version 3.0.

**Comment by bgpark-argonet** [comment]
This issue closed but.....
![image](https://user-images.githubusercontent.com/53858707/104414450-a32bdd80-55b3-11eb-98a3-cd6a3a38b29f.png)

Check this plz....
Text field is broken. But another field is ok.
Thanks man! 👍

**Comment by cweijan** [comment]
@bgpark-argonet fix at 3.0.1

**Comment by bgpark-argonet** [comment]
Thanks man :) 
Plz check this..
The bug occurs when Json field null 
![image](https://user-images.githubusercontent.com/53858707/104427316-6fa67e80-55c6-11eb-8900-feca3b624ba4.png)
You'r good man! 👍

**Comment by cweijan** [comment]
3.0.2 fix.
