### ISSUE TITLE
[BUG]修改某个connection的配置时，保存后报错，导致所有connection不展示

### ISSUE THREAD

**Issue by chenpey** [cweijan/vscode-database-client#85]
- OS INFO :
请问一下配置文件的位置，我好删除之后重新设置，谢谢

![1.jpg](https://upload.cc/i1/2020/12/08/d2fnyK.jpg)

![2.jpg](https://upload.cc/i1/2020/12/08/gJOKv1.jpg)

**Comment by cweijan** [comment]
你是修改了什么, 跟我说下, 得更新版本解决bug后才能修复.

**Comment by chenpey** [comment]
设置了一下 database，然后保存

能不能先给我说一下，配置文件在本地的位置，我好先删掉，谢谢

**Comment by cweijan** [comment]
这个是由vscode管理的, 你先安装回旧版本.

**Comment by cweijan** [comment]
![image](https://user-images.githubusercontent.com/27798227/101785665-fbe10400-3b37-11eb-8379-63140d13324f.png)

**Comment by cweijan** [comment]
老哥你还在使用该插件不, 新版本我已经修复了, 如果ok我就关闭issue了.

**Comment by chenpey** [comment]
> 老哥你还在使用该插件不, 新版本我已经修复了, 如果ok我就关闭issue了.

看到了，更新了，非常感谢。
