### ISSUE TITLE
[BUG] Horizontal scrolling not working

### ISSUE THREAD

**Issue by DorinMol** [cweijan/vscode-database-client#86]
- OS INFO : Ubuntu 18.04.5 LTS
After selecting all columns (*), which are over a dozen, the horizontal scroll appears to be fixed, even though not all columns are visible. Please check the picture below.
![Screenshot from 2020-12-15 13-05-51](https://user-images.githubusercontent.com/5896720/102207489-d73db100-3ed6-11eb-8ecf-6fadecb5fac1.png)

The only "fix" i'm using currently is just to select the neccessary columns and not all of them.
Thanks.

**Comment by DorinMol** [comment]
It seems that this is only happening if you also have the vscode terminal opened :), otherwise it works as expected.

**Comment by cweijan** [comment]
This is a bug of the form component, it has a certain probability, I will try to fix it later.

**Comment by cweijan** [comment]
I have not reproduced the issue in the new version, can it work on your side? If it works, I will close the issue.
