### ISSUE TITLE
UI/UX Improvement's

### ISSUE THREAD

**Issue by itsdonnix** [cweijan/vscode-database-client#87]
I try to make some improvements on UI/UX.
I am just eager to help since I always work with mysql databases on my daily client projects, this extension helps me so much.  I think it will may break a lot of changes on UI/UX.

I planned to use [tailwindcss](https://tailwindcss.com/) instead.

So what do you think guys?

**Comment by cweijan** [comment]
I am not a professional front-end, so I certainly welcome someone to help improve the interaction, [This](https://github.com/cweijan/vscode-mysql/blob/master/src/vue/result/App.vue) is source file of result view, you can try do it.

**Comment by itsdonnix** [comment]
Thank's man!  yeah I already made changes on that. I will create draft PR soon!

**Comment by cweijan** [comment]
I has been merge PR and release on 2.8.6, it work fine.

**Comment by itsdonnix** [comment]
I do some changes on `result` view. How do you think @cweijan ?

![2020-12-21_06-39](https://user-images.githubusercontent.com/16399020/102726162-5445ac00-4357-11eb-9bfe-986cec21d556.png)

**Comment by cweijan** [comment]
It looks good, but it looks like there is no delete and edit feature, and I suggest to keep the original table component, because he optimized the big data rendering, you can try to query with limit 10000 .

**Comment by itsdonnix** [comment]
Thanks... Yeah, I'm working on it... I will make a PR when all is done

**Comment by cweijan** [comment]
Looking forward to your work, I really like the layout you designed.

**Comment by itsdonnix** [comment]
Thanks man! But unfortunately I can't do this right now. So I stashed my changes for now and just editing your existing layout

**Comment by cweijan** [comment]
I closed the issue, if there are have new changes, welcome submit a PR.
