### ISSUE TITLE
element with id ****  is already registered

### ISSUE THREAD

**Issue by PtCu** [cweijan/vscode-database-client#9]
连接的时候出现"element with id ****  is already registered"是怎么回事啊

**Comment by cweijan** [comment]
提供个截图.

**Comment by PtCu** [comment]
刚开始还能连接，然后点击新建连接后就报这个错误了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chen WeiJian"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月18日(星期六) 晚上6:04
收件人:&nbsp;"cweijan/vscode-mysql"<vscode-mysql@noreply.github.com&gt;;
抄送:&nbsp;"PtCu"<1365699009@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cweijan/vscode-mysql] element with id ****  is already registered (#9)





 
提供个截图.

**Comment by cweijan** [comment]
你是不是发错仓库了, 我的代码内没有这个提示.

**Comment by cweijan** [comment]
又或者你按装了其他Mysql插件, 导致冲突了.

**Comment by cweijan** [comment]
抱歉, 我知道是怎么回事了, 等下更新.

**Comment by PtCu** [comment]
谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chen WeiJian"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月18日(星期六) 晚上6:17
收件人:&nbsp;"cweijan/vscode-mysql"<vscode-mysql@noreply.github.com&gt;;
抄送:&nbsp;"PtCu"<1365699009@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cweijan/vscode-mysql] element with id ****  is already registered (#9)





 
抱歉, 我知道是怎么回事了, 等下更新.

**Comment by cweijan** [comment]
重启vscode, 更新到1.7.32版本即可解决.

**Comment by PtCu** [comment]
已经解决了，谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chen WeiJian"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月18日(星期六) 晚上6:26
收件人:&nbsp;"cweijan/vscode-mysql"<vscode-mysql@noreply.github.com&gt;;
抄送:&nbsp;"PtCu"<1365699009@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cweijan/vscode-mysql] element with id ****  is already registered (#9)





 
重启vscode, 更新到1.7.32版本即可解决.

**Comment by cweijan** [comment]
如果觉得好用可以点个star哦.

**Comment by ljyf5593** [comment]
我这里也出现这个错误，版本是2.6.2
![image](https://user-images.githubusercontent.com/960459/97242519-0e74d780-182f-11eb-9918-83ea769bf0a9.png)

**Comment by cweijan** [comment]
@ljyf5593 试下2.6.3

**Comment by ljyf5593** [comment]
更新到2.6.3也不行，报同样的错误，并且我发现只有一个数据库会出现该问题，同一个数据库连接下的其他库是正常的
