### ISSUE TITLE
Unable to Connect to Databases - Error Loading WebView

### ISSUE THREAD

**Issue by lexman1958** [cweijan/vscode-database-client#901]
- Operating system: Windows 10
- Database type and version: SQLite and Mariadb
- Extension Version: 6.6.8

When Connecting I am getting this error:

**Error loading webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..**

**Comment by cweijan** [comment]
This is a bug of VS Code, just restart your VS Code

**Comment by lexman1958** [comment]
@cweijan Yesterday, i tried restarting many times and the error was still there. I even reinstall the extension but the error still there. Today started vs code and there was update on your extension and reloaded. Now it seems to be ok.

Why are there updates everyday?

**Comment by cweijan** [comment]
Hi, the extension is not updated every day. Recently, due to many serious problems reported, I update it more frequently.

**Comment by lexman1958** [comment]
Ok
