### ISSUE TITLE
[BUG] 查询结果页面显示空白

### ISSUE THREAD

**Issue by YannLex** [cweijan/vscode-database-client#92]
- OS INFO :
macOS Catalina Version 10.15.6

- VS Code:
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z (8 mos ago)
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0

- Issue Desc:
数据库连接正常，可显示table list，但查询时弹出结果页面空白。
截图如下：
![image](https://user-images.githubusercontent.com/3049310/103727124-786ee180-5015-11eb-91f9-9662fdfcd7cc.png)

**Comment by cweijan** [comment]
你先回退旧版本, 过几天发布新版本.
![image](https://user-images.githubusercontent.com/27798227/103733320-752f2200-5024-11eb-8547-488c132369a2.png)

**Comment by YannLex** [comment]
我尝试退到2.8.x, 2.7.x, 2.6.x 都是显示空白；尝试了2.4.3 可以了

**Comment by cweijan** [comment]
这就有点奇怪了, 我估计是因为你的vscode版本不是最新的, 新版本的插件不兼容旧版本vscode.

**Comment by YannLex** [comment]
大兄弟，我的错，我的vscode的确很旧了，刚刚手动更新了，并且mysql plugin也更新到最新版2.9.2，一切正常。
非常感谢！
