### ISSUE TITLE
[BUG] copy按钮弹出插入框

### ISSUE THREAD

**Issue by YannLex** [cweijan/vscode-database-client#93]
- OS INFO :
MacOS Catalina version 10.15.6

- VS INFO：
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Desc：
查询后选中点击copy按钮，没有copy，弹出插入框（左边按钮是编辑）
![image](https://user-images.githubusercontent.com/3049310/104089086-d6febe80-52a6-11eb-9f46-3c3a03f2e8d4.png)
![image](https://user-images.githubusercontent.com/3049310/104089120-21803b00-52a7-11eb-875b-b59336517d46.png)

**Comment by cweijan** [comment]
现在复制就是显示插入的, 下版本会改.

**Comment by cweijan** [comment]
版本3.0已经更改标题为copy.

**Comment by YannLex** [comment]
👍 体验了，感觉复制出insert语句更好用些。
