### ISSUE TITLE
[BUG]在多表查询时结果显示出错

### ISSUE THREAD

**Issue by NinelieZ** [cweijan/vscode-database-client#95]
- OS INFO :
  Windows 10 专业工作站版 Insider Preview Build 21286.1000
- VSCode : 1.52.1
- vscode-mysql : 2.9.2
- 初学MySQL，执行如下语句时输出错误
```
-- 1.查询所有工作在NEW YORK和CHICAGO的员工姓名，员工编号，以及他们的经理姓名，经理编号。
SELECT e.ename,e.empno,m.ename,e.mgr
FROM emp e,emp m,dept
WHERE dept.deptno = e.deptno AND loc IN ('NEW YORK','CHICAGO') AND e.mgr = m.empno;

```
![image](https://user-images.githubusercontent.com/44182970/104259954-71d0e600-54bd-11eb-8d6c-a94597f4c35d.png)

在Sqlyog中和使用SQLTools执行结果正确
![image](https://user-images.githubusercontent.com/44182970/104260079-ae9cdd00-54bd-11eb-8d1f-acf580b4c5dd.png)
![image](https://user-images.githubusercontent.com/44182970/104260129-cecc9c00-54bd-11eb-8940-272f8a449b9b.png)

**Comment by cweijan** [comment]
列重名的话列就无法定位了.

**Comment by NinelieZ** [comment]
明白了，谢谢，打扰了

**Comment by cweijan** [comment]
话说你的vscode主题好丑, 建议用[one dark pro](https://marketplace.visualstudio.com/items?itemName=zhuangtongfa.Material-theme)

**Comment by NinelieZ** [comment]
我比较喜欢这种深蓝色的😂
