### ISSUE TITLE
[BUG]最近版本连接数据库有问题

### ISSUE THREAD

**Issue by sacter** [cweijan/vscode-database-client#96]
- OS INFO :
2.8.2版本连接数据库无问题，插件自动更新以后数据库可以连接上，但连接上的是所有库，并且database数据库表不存在了，报Id已被注册错误。

**Comment by cweijan** [comment]
老哥先回退旧版本, 过几天发布新版本后就不会有这个问题了.

**Comment by cweijan** [comment]
版本3.0已经发布, 现在不会再出现该问题了.
