### ISSUE TITLE
[BUG] Please detail if there is a way to change execute current line or selected keyboard shortcut 

### ISSUE THREAD

**Issue by myusrn** [cweijan/vscode-database-client#97]
- OS Info: Windows 10 20H2

Please detail if there is a way to change execute current line or selected keyboard shortcut, e.g. i'd like to change it from F9 to the mysql workbench defaults ctrl+enter [ all or selected ] and ctrl+shift+enter [ current line cursor is on ] which shouldn't create conflict / overlap with microsoft sql server extension keyboard shortcut ctrl+e [ all or selected ] and ctrl+shift+e [ current line cursor is on ] for .sql files.

**Comment by cweijan** [comment]
You need change default shortcut, open keybindings.json, then adding
```json
 {
        "key": "f9",
        "command": "mysql.runQuery",
        "when": "editorLangId == 'sql'"
    }
```
Change to the shortcut you want to bind.
![image](https://user-images.githubusercontent.com/27798227/104886594-faabbe00-59a4-11eb-9de6-3ec35c9d3c04.png)

**Comment by myusrn** [comment]
Thanks for the details that let me wire up preferred ctrl+enter or ctrl+shift+enter option instead of default f9.

q1. I'm finding that if the cursor is at the start of the line mysql.runQuery executes that line as expected.  If the cursor is at the end of the line it executes the following line not the line it is on.  Would it be feasible and make sense for mysql.runQuery to run the line the cursor is on even when cursor is parked at end of the line?

q2. Is there any sense in having a mysql.runQueryAll command introduced that would enable ctrl+enter for running line cursor is on or all currently selected lines and ctrl+shift+enter to run all lines in .sql file?  Perhaps the latter is not something the user base often does.

```
[
    { "key": "ctrl+enter", "command": "mysql.runQuery", "when": "editorTextFocus && editorLangId == 'sql'" }, // run line cursor is on or all currently selected lines
    //{ "key": "ctrl+shift+enter", "command": "mysql.runQueryAll", "when": "editorTextFocus && editorLangId == 'sql'" } // run all lines in sql file 
]
```

fyi - used the macros extension to enable a ctrl+enter keyboard shortcut that mysql.runQuery on current line and then moves cursor to the next line so you can repeat without having to move it yourself.  Perhaps of little interest if its considered that most sql involves multiple lines.

```
    // add @name:macros @publisher:geddski extension and then ctrl+, | user settings | open settings (json) | 
   "macros": { "mysqlRunQueryAndCursorDown": [ "mysql.runQuery", "cursorDown" ]  }

    // and then ctrl+k,ctrl+s | open keyboard shortcuts (json) | 
    { "key": "ctrl+enter", "command": "macros.mysqlRunQueryAndCursorDown", "when": "editorTextFocus && editorLangId == 'sql'" } // run line cursor is on or all currently selected lines and cursor down
```

**Comment by cweijan** [comment]
1. RunQuery is not to run the current line, it to find the SQL closest to the cursor.
2. runQueryAll currently there is no such feature, but i think it is a good idea, I will try to implement it in the future.

**Comment by myusrn** [comment]
Thanks for the additional details.  Added comment about a RunQueryAndCursorDown behavior that may be of interest.  Let me know if i should close this issue or leave it for you to do so.

**Comment by cweijan** [comment]
It find sql by cursor and delimiter.
example
1. Run current line.
![image](https://user-images.githubusercontent.com/27798227/104899937-6d716500-59b6-11eb-94a1-780ac7b76d34.png)
2. Run next line.
![image](https://user-images.githubusercontent.com/27798227/104899941-6e09fb80-59b6-11eb-8121-e0cf97cdab8a.png)
3. If next line is empty, run current line.
![image](https://user-images.githubusercontent.com/27798227/104900155-b1fd0080-59b6-11eb-9dd9-ad5fad3f8e26.png)

**Comment by myusrn** [comment]
Would be excellent if it was feasible without too much work to add command: "mysql.runQueryAndCursorDown" support that one could wire up ctrl+enter or shift+enter keyboard shortcut to that is intelligent enough to know when it has to move cursor down 1 line or several lines in order to place it at start of next sql statement when dealing with multi-line sql expressions.

I would say just leave users to create this using the macros extension support i noted above but i don't know how you could do it there as it doesn't have to intelligence of knowing how to link togehter a "mysql.runQuery" command with more than one "cursorDown" commands. 

Looking for experience one has in msft python and jupyter notebook extensions where "ctrl+enter" and "shift+enter keyboard shortcuts respectively will step you though .py script blocks and .ipynb code blocks one at a time when looking to test and debug ones code.

**Comment by cweijan** [comment]
Since 3.2.0, I add sql code len, I think the editor should be simple and not add more extra commands to the editor.
![image](https://user-images.githubusercontent.com/27798227/105624134-499c9c00-5e5a-11eb-80db-93119e39a044.png)
