### ISSUE TITLE
[BUG] Incorect activity bar title

### ISSUE THREAD

**Issue by itsdonnix** [cweijan/vscode-database-client#98]
- OS INFO : Linux DEV 5.10.6-051006-generic #202101091334 SMP Sat Jan 9 13:40:22 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- VSCode Version: 1.52.1 ea3859d4ba2f3e577a159bc91e3074c5d85c0523 x64
- Extension Version: Commit ecbaa30

https://user-images.githubusercontent.com/16399020/105119963-49c03300-5b0c-11eb-83c1-253da7f52987.mp4

**Comment by cweijan** [comment]
Has been update.

**Comment by itsdonnix** [comment]
Ahhh... I just working on it... 😀

**Comment by itsdonnix** [comment]
@cweijan I will make a PR soon

**Comment by cweijan** [comment]
![image](https://user-images.githubusercontent.com/27798227/105122055-74ac8600-5b10-11eb-958a-07a09f9b66ce.png)
II think it might be better to show two columns in one row, how do you think?

**Comment by itsdonnix** [comment]
Yeah... I agree! It's been my consideration since then... Well... I will working on that.

**Comment by itsdonnix** [comment]
I close it
